import type { Exercise } from '../../types';

/** Mở rộng bài tập cho các chuyên đề DH chưa ưu tiên, hướng tới 6–8 bài/chuyên đề. */
export const dhExpandExercises: Exercise[] = [
  // DH-04: hai tỉ số
  {
    id: 'DH-04-EX4',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số bi đỏ và bi xanh có tỉ số $5:3$. Nếu bớt đi 6 viên bi đỏ thì tỉ số bi đỏ và bi xanh là $1:1$. Tính số bi xanh (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi đỏ $=5k \\to 5k-6$, xanh $=3k$ (không đổi): $(5k-6):3k=1:1$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$5k-6=3k \\Rightarrow 2k=6 \\Rightarrow k=3$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số bi xanh $=3\\times3=9$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-04-EX5',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số sách Văn và Toán có tỉ số $3:5$. Nếu nhập thêm 10 quyển Văn thì tỉ số Văn và Toán là $2:3$. Tính số sách Toán (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi Văn $=3k \\to 3k+10$, Toán $=5k$ (không đổi): $(3k+10):5k=2:3$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$3(3k+10)=2\\times5k \\Rightarrow 9k+30=10k \\Rightarrow k=30$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số sách Toán $=5\\times30=150$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['150'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-04-EX6',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số học sinh nam và nữ có tỉ số $5:6$. Nếu chuyển 4 bạn nữ sang lớp khác thì tỉ số nam và nữ là $5:4$. Tính số học sinh nam (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi nam $=5k$ (không đổi), nữ $=6k \\to 6k-4$: $5k:(6k-4)=5:4$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$4\\times5k=5\\times(6k-4) \\Rightarrow 20k=30k-20 \\Rightarrow k=2$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số học sinh nam $=5\\times2=10$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-04-EX7',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số cam và táo có tỉ số $4:5$. Nếu bán đi 9 quả cam thì tỉ số cam và táo là $1:2$. Tính số quả táo (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi cam $=4k \\to 4k-9$, táo $=5k$ (không đổi): $(4k-9):5k=1:2$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$2(4k-9)=5k \\Rightarrow 8k-18=5k \\Rightarrow k=6$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số quả táo $=5\\times6=30$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['30'], tolerance: 0, isInteger: true },
  },

  // DH-05: hai hiệu số
  {
    id: 'DH-05-EX4',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 4kg nho và 3kg xoài hết 340 000đ. Mua 4kg nho và 8kg xoài hết 440 000đ. Tính giá 1kg xoài.',
    solutionSteps: [
      { order: 1, content: 'Số nho bằng nhau (4kg); chênh lệch xoài $=8-3=5$kg, chênh lệch tiền $=440\\,000-340\\,000=100\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1kg xoài $=100\\,000:5=20\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['20000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-05-EX5',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 6 vé loại A và 2 vé loại B hết 380 000đ. Mua 6 vé loại A và 5 vé loại B hết 470 000đ. Tính giá 1 vé loại B.',
    solutionSteps: [
      { order: 1, content: 'Số vé A bằng nhau (6 vé); chênh lệch vé B $=5-2=3$, chênh lệch tiền $=470\\,000-380\\,000=90\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1 vé B $=90\\,000:3=30\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['30000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-05-EX6',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 5 quyển sách và 3 cây bút hết 175 000đ. Mua 5 quyển sách và 8 cây bút hết 225 000đ. Tính giá 1 cây bút.',
    solutionSteps: [
      { order: 1, content: 'Số sách bằng nhau (5 quyển); chênh lệch bút $=8-3=5$, chênh lệch tiền $=225\\,000-175\\,000=50\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1 cây bút $=50\\,000:5=10\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-05-EX7',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 2 con gà và 3 con vịt hết 560 000đ. Mua 2 con gà và 7 con vịt hết 800 000đ. Tính giá 1 con vịt.',
    solutionSteps: [
      { order: 1, content: 'Số gà bằng nhau (2 con); chênh lệch vịt $=7-3=4$, chênh lệch tiền $=800\\,000-560\\,000=240\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1 con vịt $=240\\,000:4=60\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['60000'], tolerance: 0, isInteger: true },
  },

  // DH-10: trồng cây
  {
    id: 'DH-10-EX4',
    topicIds: ['DH-10'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một con đường dài 96m, trồng cây ở cả hai đầu, khoảng cách 8m. Hỏi cần bao nhiêu cây?',
    solutionSteps: [{ order: 1, content: '$96:8+1=13$ cây.', rationale: 'Đường thẳng có 2 đầu nên cộng thêm 1.' }],
    numeric: { kind: 'single', acceptedValues: ['13'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-10-EX5',
    topicIds: ['DH-10'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Trồng cây quanh một hồ hình tròn chu vi 150m, khoảng cách 6m. Hỏi cần bao nhiêu cây?',
    solutionSteps: [{ order: 1, content: 'Đường khép kín: $150:6=25$ cây.', rationale: 'Không cộng thêm 1 vì đường khép kín.' }],
    numeric: { kind: 'single', acceptedValues: ['25'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-10-EX6',
    topicIds: ['DH-10'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một hàng rào dài 63m, cắm cọc ở cả hai đầu với khoảng cách giữa hai cọc là 7m. Hỏi cần bao nhiêu cọc?',
    solutionSteps: [{ order: 1, content: '$63:7+1=10$ cọc.', rationale: 'Hàng rào thẳng có 2 đầu nên cộng thêm 1.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-10-EX7',
    topicIds: ['DH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trồng cây quanh một công viên hình vuông có cạnh 80m, khoảng cách 10m. Hỏi cần bao nhiêu cây?',
    solutionSteps: [
      { order: 1, content: 'Chu vi công viên $=80\\times4=320$m.', rationale: 'Tính chu vi hình vuông.' },
      { order: 2, content: 'Đường khép kín: số cây $=320:10=32$.', rationale: 'Không cộng thêm 1 vì đường khép kín.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['32'], tolerance: 0, isInteger: true },
  },

  // DH-11: giả thiết tạm
  {
    id: 'DH-11-EX4',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Vừa gà vừa chó có 25 con và 70 chân. Tính số con chó.',
    solutionSteps: [
      { order: 1, content: 'Giả sử tất cả là gà: $25\\times2=50$ chân; thiếu $70-50=20$ chân.', rationale: 'Giả thiết tạm toàn bộ là gà.' },
      { order: 2, content: 'Mỗi con chó hơn gà 2 chân; số chó $=20:2=10$.', rationale: 'Chia số chân thiếu cho mức chênh lệch mỗi con.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-11-EX5',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Vừa gà vừa chó có 25 con và 70 chân. Tính số con gà.',
    solutionSteps: [{ order: 1, content: 'Số chó $=10$; số gà $=25-10=15$.', rationale: 'Lấy tổng số con trừ số chó.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-11-EX6',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có một số xe máy (2 bánh) và ô tô (4 bánh), tất cả có 18 xe và 56 bánh. Tính số ô tô.',
    solutionSteps: [
      { order: 1, content: 'Giả sử tất cả là xe máy: $18\\times2=36$ bánh; thiếu $56-36=20$ bánh.', rationale: 'Giả thiết tạm toàn bộ là xe máy.' },
      { order: 2, content: 'Mỗi ô tô hơn xe máy $4-2=2$ bánh; số ô tô $=20:2=10$.', rationale: 'Chia số bánh thiếu cho mức chênh lệch mỗi xe.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-11-EX7',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement:
      'Một lớp có 32 học sinh làm một bài kiểm tra gồm các câu, mỗi bạn làm đúng được cộng 5 điểm, làm sai bị trừ 2 điểm (mỗi bạn chỉ tính đúng hoặc sai). Tổng điểm cả lớp là 118. Tính số bạn làm sai.',
    solutionSteps: [
      { order: 1, content: 'Giả sử cả 32 bạn đều đúng: tổng điểm $=32\\times5=160$.', rationale: 'Giả thiết tạm toàn bộ đều đúng.' },
      { order: 2, content: 'Số điểm thừa ra so với thực tế $=160-118=42$.', rationale: 'So sánh với tổng điểm thực tế.' },
      { order: 3, content: 'Mỗi bạn làm sai (thay vì đúng) làm giảm $5-(-2)=7$ điểm; số bạn sai $=42:7=6$.', rationale: 'Chia số điểm chênh lệch cho mức giảm mỗi bạn làm sai.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, isInteger: true },
  },

  // DH-12: tính ngược từ cuối
  {
    id: 'DH-12-EX4',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số, sau khi cộng 8 rồi chia 3 thì được 12. Tìm số ban đầu.',
    solutionSteps: [
      { order: 1, content: 'Trước khi chia 3 để được 12, số đó là $12\\times3=36$.', rationale: 'Tính ngược phép chia thành phép nhân.' },
      { order: 2, content: 'Trước khi cộng 8 để được 36, số ban đầu là $36-8=28$.', rationale: 'Tính ngược phép cộng thành phép trừ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['28'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-12-EX5',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số, sau khi trừ 15 rồi nhân 4 thì được 60. Tìm số ban đầu.',
    solutionSteps: [{ order: 1, content: '$(60:4)+15=15+15=30$.', rationale: 'Tính ngược từ phép nhân đến phép trừ.' }],
    numeric: { kind: 'single', acceptedValues: ['30'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-12-EX6',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số, sau khi nhân 4 rồi trừ 12 thì được 28. Tìm số ban đầu.',
    solutionSteps: [{ order: 1, content: '$(28+12):4=10$.', rationale: 'Tính ngược từ phép trừ đến phép nhân.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-12-EX7',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số, sau khi chia 5 rồi trừ 3 thì được 9. Tìm số ban đầu.',
    solutionSteps: [{ order: 1, content: '$(9+3)\\times5=60$.', rationale: 'Tính ngược từ phép trừ đến phép chia.' }],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true },
  },

  // DH-13: tỉ lệ thuận nghịch
  {
    id: 'DH-13-EX4',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Mua 6 cái kẹo hết 18 000đ. Hỏi mua 10 cái kẹo hết bao nhiêu tiền?',
    solutionSteps: [{ order: 1, content: 'Giá 1 cái $=18\\,000:6=3\\,000$đ; 10 cái hết $3\\,000\\times10=30\\,000$đ.', rationale: 'Rút về đơn vị rồi nhân với số lượng cần tìm.' }],
    numeric: { kind: 'single', acceptedValues: ['30000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-13-EX5',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: '8 người làm xong việc trong 9 ngày. Hỏi 6 người làm xong việc đó trong bao nhiêu ngày?',
    solutionSteps: [{ order: 1, content: 'Người-ngày $=8\\times9=72$; với 6 người: $72:6=12$ ngày.', rationale: 'Tỉ lệ nghịch giữa số người và thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-13-EX6',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một ô tô đi 120km hết 10 lít xăng. Hỏi đi 180km hết bao nhiêu lít xăng?',
    solutionSteps: [{ order: 1, content: '1km hết $10:120=\\dfrac{1}{12}$ lít; 180km hết $180\\times\\dfrac{1}{12}=15$ lít.', rationale: 'Rút về đơn vị (1km) rồi nhân với quãng đường cần tìm.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true, unit: 'lít' },
  },
  {
    id: 'DH-13-EX7',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: '3 máy dệt dệt xong một lô vải trong 8 giờ. Hỏi 4 máy (cùng năng suất) dệt xong lô vải đó trong bao nhiêu giờ?',
    solutionSteps: [{ order: 1, content: 'Máy-giờ $=3\\times8=24$; với 4 máy: $24:4=6$ giờ.', rationale: 'Tỉ lệ nghịch giữa số máy và thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, isInteger: true },
  },

  // DH-14: năng suất, mật độ
  {
    id: 'DH-14-EX4',
    topicIds: ['DH-14'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một xưởng may may được 450 cái áo trong 5 ngày. Tính năng suất (áo/ngày).',
    solutionSteps: [{ order: 1, content: '$450:5=90$ áo/ngày.', rationale: 'Chia khối lượng công việc cho thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['90'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-14-EX5',
    topicIds: ['DH-14'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Với năng suất 90 áo/ngày, xưởng đó may được bao nhiêu áo trong 8 ngày?',
    solutionSteps: [{ order: 1, content: '$90\\times8=720$ áo.', rationale: 'Nhân năng suất với thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['720'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-14-EX6',
    topicIds: ['DH-14'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một cánh đồng 800m² thu hoạch 360kg lúa. Một cánh đồng khác cùng năng suất có diện tích 1500m². Tính sản lượng thu hoạch của cánh đồng thứ hai.',
    solutionSteps: [
      { order: 1, content: 'Năng suất $=360:800=0{,}45$kg/m².', rationale: 'Chia sản lượng cho diện tích.' },
      { order: 2, content: 'Sản lượng cánh đồng thứ hai $=0{,}45\\times1500=675$kg.', rationale: 'Nhân năng suất với diện tích mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['675'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-14-EX7',
    topicIds: ['DH-14'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một công nhân trong 6 giờ lắp được 90 sản phẩm. Tính năng suất (sản phẩm/giờ).',
    solutionSteps: [{ order: 1, content: '$90:6=15$ sản phẩm/giờ.', rationale: 'Chia khối lượng công việc cho thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
];
