import type { Exercise } from '../../types';

export const dhMoreExercises: Exercise[] = [
  {
    id: 'DH-02-EX1',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 72, tỉ số là $2:7$. Tìm số bé.',
    solutionSteps: [
      { order: 1, content: 'Tổng số phần $=2+7=9$. Giá trị 1 phần $=72:9=8$.', rationale: 'Chia tổng cho tổng số phần.' },
      { order: 2, content: 'Số bé $=8\\times2=16$.', rationale: 'Nhân giá trị 1 phần với số phần của số bé.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['16'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX2',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 72, tỉ số là $2:7$. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: 'Giá trị 1 phần $=8$; số lớn $=8\\times7=56$.', rationale: 'Nhân giá trị 1 phần với số phần của số lớn.' }],
    numeric: { kind: 'single', acceptedValues: ['56'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX3',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 100. Số thứ nhất gấp 4 lần số thứ hai. Tìm số thứ nhất.',
    solutionSteps: [
      { order: 1, content: 'Tỉ số $1:4$, tổng số phần $=5$. Giá trị 1 phần $=100:5=20$.', rationale: 'Số thứ nhất gấp 4 lần nghĩa là tỉ số 1:4.' },
      { order: 2, content: 'Số thứ nhất $=20\\times4=80$.', rationale: 'Nhân giá trị 1 phần với số phần.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['80'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX4',
    topicIds: ['DH-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đội có 45 người gồm nam và nữ. Số nam bằng $\\dfrac{4}{5}$ số nữ. Tính số nam.',
    solutionSteps: [
      { order: 1, content: 'Tỉ số nam:nữ $=4:5$, tổng số phần $=9$. Giá trị 1 phần $=45:9=5$.', rationale: 'Đổi tỉ lệ phân số thành tỉ số phần.' },
      { order: 2, content: 'Số nam $=5\\times4=20$.', rationale: 'Nhân giá trị 1 phần với số phần của nam.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX1',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 45, tỉ số là $4:7$. Tìm số bé.',
    solutionSteps: [
      { order: 1, content: 'Hiệu số phần $=7-4=3$. Giá trị 1 phần $=45:3=15$.', rationale: 'Chia hiệu cho hiệu số phần.' },
      { order: 2, content: 'Số bé $=15\\times4=60$.', rationale: 'Nhân giá trị 1 phần với số phần của số bé.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX2',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 45, tỉ số là $4:7$. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: 'Giá trị 1 phần $=15$; số lớn $=15\\times7=105$.', rationale: 'Nhân giá trị 1 phần với số phần của số lớn.' }],
    numeric: { kind: 'single', acceptedValues: ['105'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX3',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 36. Số lớn gấp 3 lần số bé. Tìm số bé.',
    solutionSteps: [
      { order: 1, content: 'Tỉ số $1:3$, hiệu số phần $=2$. Giá trị 1 phần $=36:2=18$.', rationale: 'Số lớn gấp 3 lần số bé nghĩa là tỉ số 1:3.' },
      { order: 2, content: 'Số bé $=18$.', rationale: 'Số bé ứng với 1 phần.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['18'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX4',
    topicIds: ['DH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tuổi bố hơn tuổi con 24 tuổi. Tuổi bố gấp 4 lần tuổi con. Tính tuổi con.',
    solutionSteps: [
      { order: 1, content: 'Tỉ số con:bố $=1:4$, hiệu số phần $=3$. Giá trị 1 phần $=24:3=8$.', rationale: 'Áp dụng dạng hiệu-tỉ.' },
      { order: 2, content: 'Tuổi con $=8$.', rationale: 'Con ứng với 1 phần.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-04-EX1',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số học sinh nam và nữ của một lớp có tỉ số $4:5$. Nếu chuyển 3 bạn nam sang lớp khác thì tỉ số nam và nữ là $1:2$. Tính số học sinh nữ (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi nam $=4k$, nữ $=5k$ (không đổi): $(4k-3):5k=1:2$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$2(4k-3)=5k \\Rightarrow 8k-6=5k \\Rightarrow k=2$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số nữ $=5\\times2=10$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-04-EX2',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số bi đỏ và bi xanh có tỉ số $3:2$. Nếu thêm 10 viên bi xanh thì tỉ số bi đỏ và bi xanh là $3:4$. Tính số bi đỏ (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi đỏ $=3k$ (không đổi), xanh $=2k \\to 2k+10$: $3k:(2k+10)=3:4$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$4\\times3k=3\\times(2k+10) \\Rightarrow 12k=6k+30 \\Rightarrow k=5$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số bi đỏ $=3\\times5=15$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-04-EX3',
    topicIds: ['DH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số vở Toán và vở Văn của một cửa hàng có tỉ số $5:4$. Nếu bán đi 12 quyển vở Toán thì tỉ số Toán và Văn là $1:2$. Tính số vở Văn (không đổi).',
    solutionSteps: [
      { order: 1, content: 'Gọi Toán $=5k \\to 5k-12$, Văn $=4k$ (không đổi): $(5k-12):4k=1:2$.', rationale: 'Lập phương trình theo tỉ số mới.' },
      { order: 2, content: '$2(5k-12)=4k \\Rightarrow 10k-24=4k \\Rightarrow k=4$.', rationale: 'Giải tìm k.' },
      { order: 3, content: 'Số vở Văn $=4\\times4=16$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['16'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-05-EX1',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 6 quyển vở và 4 chiếc bút hết 68 000đ. Mua 6 quyển vở và 9 chiếc bút hết 108 000đ. Tính giá 1 chiếc bút.',
    solutionSteps: [
      { order: 1, content: 'Số vở bằng nhau (6 quyển); chênh lệch bút $=9-4=5$, chênh lệch tiền $=108\\,000-68\\,000=40\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1 bút $=40\\,000:5=8\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-05-EX2',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 3kg thịt và 2kg cá hết 350 000đ. Mua 3kg thịt và 6kg cá hết 550 000đ. Tính giá 1kg cá.',
    solutionSteps: [
      { order: 1, content: 'Số thịt bằng nhau (3kg); chênh lệch cá $=6-2=4$kg, chênh lệch tiền $=550\\,000-350\\,000=200\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1kg cá $=200\\,000:4=50\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['50000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-05-EX3',
    topicIds: ['DH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 10 vé loại A và 5 vé loại B hết 675 000đ. Mua 10 vé loại A và 12 vé loại B hết 885 000đ. Tính giá 1 vé loại B.',
    solutionSteps: [
      { order: 1, content: 'Số vé A bằng nhau (10 vé); chênh lệch vé B $=12-5=7$, chênh lệch tiền $=885\\,000-675\\,000=210\\,000$đ.', rationale: 'Xác định đại lượng không đổi và tính hai hiệu số.' },
      { order: 2, content: 'Giá 1 vé B $=210\\,000:7=30\\,000$đ.', rationale: 'Chia chênh lệch tiền cho chênh lệch số lượng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['30000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-06-EX1',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiện nay tuổi bố gấp 5 lần tuổi con. Hiệu tuổi bố con là 32 tuổi. Tính tuổi con hiện nay.',
    solutionSteps: [
      { order: 1, content: 'Tỉ số con:bố $=1:5$, hiệu số phần $=4$. Giá trị 1 phần $=32:4=8$.', rationale: 'Áp dụng dạng hiệu-tỉ tại thời điểm hiện tại.' },
      { order: 2, content: 'Tuổi con $=8$.', rationale: 'Con ứng với 1 phần.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX2',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiện nay tuổi bố gấp 5 lần tuổi con. Hiệu tuổi bố con là 32 tuổi. Tính tuổi bố hiện nay.',
    solutionSteps: [{ order: 1, content: 'Giá trị 1 phần $=8$; tuổi bố $=8\\times5=40$.', rationale: 'Bố ứng với 5 phần.' }],
    numeric: { kind: 'single', acceptedValues: ['40'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX3',
    topicIds: ['DH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Năm nay tuổi An là 12. Hỏi 3 năm trước An bao nhiêu tuổi?',
    solutionSteps: [{ order: 1, content: '$12-3=9$ (tuổi).', rationale: 'Trừ số năm đã trôi qua.' }],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX4',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiện nay tuổi cô gấp 4 lần tuổi cháu. Hiệu tuổi hai cô cháu là 27 tuổi. Hỏi 5 năm nữa cháu bao nhiêu tuổi?',
    solutionSteps: [
      { order: 1, content: 'Tỉ số cháu:cô $=1:4$, hiệu số phần $=3$. Tuổi cháu hiện nay $=27:3=9$.', rationale: 'Áp dụng dạng hiệu-tỉ để tìm tuổi cháu hiện tại.' },
      { order: 2, content: 'Sau 5 năm nữa, cháu $=9+5=14$ (tuổi).', rationale: 'Cộng thêm số năm trong tương lai.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['14'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-07-EX1',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai ô tô cách nhau 240km xuất phát cùng lúc, đi ngược chiều với vận tốc 55km/h và 65km/h. Hỏi sau bao lâu (giờ) hai xe gặp nhau?',
    solutionSteps: [{ order: 1, content: 'Tổng vận tốc $=55+65=120$km/h; thời gian gặp nhau $=240:120=2$ giờ.', rationale: 'Áp dụng công thức thời gian gặp nhau khi đi ngược chiều.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0 },
  },
  {
    id: 'DH-07-EX2',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người đi xe đạp vận tốc 15km/h xuất phát trước một người đi xe máy 2 giờ. Xe máy đuổi theo với vận tốc 35km/h. Hỏi sau bao lâu (giờ, tính từ lúc xe máy xuất phát) xe máy đuổi kịp xe đạp?',
    solutionSteps: [
      { order: 1, content: 'Khi xe máy xuất phát, xe đạp đã đi được $15\\times2=30$km.', rationale: 'Tính khoảng cách ban đầu giữa hai xe.' },
      { order: 2, content: 'Hiệu vận tốc $=35-15=20$km/h; thời gian đuổi kịp $=30:20=1{,}5$ giờ.', rationale: 'Áp dụng công thức thời gian đuổi kịp.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['1.5'], tolerance: 0 },
  },
  {
    id: 'DH-07-EX3',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai tàu hỏa cách nhau 300km đi ngược chiều nhau, vận tốc lần lượt 70km/h và 80km/h. Tính quãng đường tàu thứ nhất đi được cho đến khi gặp tàu thứ hai.',
    solutionSteps: [
      { order: 1, content: 'Tổng vận tốc $=70+80=150$km/h; thời gian gặp nhau $=300:150=2$ giờ.', rationale: 'Tính thời gian gặp nhau trước.' },
      { order: 2, content: 'Quãng đường tàu thứ nhất $=70\\times2=140$km.', rationale: 'Nhân vận tốc tàu thứ nhất với thời gian.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['140'], tolerance: 0, isInteger: true, unit: 'km' },
  },
  {
    id: 'DH-07-EX4',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một xe máy đi từ A lúc 6 giờ với vận tốc 36km/h. Một ô tô đi từ A lúc 8 giờ đuổi theo với vận tốc 60km/h. Hỏi ô tô đuổi kịp xe máy lúc mấy giờ (nhập số giờ trong ngày, ví dụ 9)?',
    solutionSteps: [
      { order: 1, content: 'Khi ô tô xuất phát (8 giờ), xe máy đã đi được $36\\times2=72$km.', rationale: 'Xe máy đi trước 2 giờ (từ 6 đến 8 giờ).' },
      { order: 2, content: 'Hiệu vận tốc $=60-36=24$km/h; thời gian đuổi kịp $=72:24=3$ giờ.', rationale: 'Áp dụng công thức thời gian đuổi kịp.' },
      { order: 3, content: 'Ô tô đuổi kịp lúc $8+3=11$ giờ.', rationale: 'Cộng thời gian đuổi kịp vào giờ xuất phát của ô tô.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['11'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX1',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một ca nô xuôi dòng vận tốc 26km/h, ngược dòng vận tốc 18km/h. Tính vận tốc thực của ca nô.',
    solutionSteps: [{ order: 1, content: '$(26+18):2=22$km/h.', rationale: 'Áp dụng công thức tính vận tốc thực.' }],
    numeric: { kind: 'single', acceptedValues: ['22'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX2',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một ca nô xuôi dòng vận tốc 26km/h, ngược dòng vận tốc 18km/h. Tính vận tốc dòng nước.',
    solutionSteps: [{ order: 1, content: '$(26-18):2=4$km/h.', rationale: 'Áp dụng công thức tính vận tốc dòng nước.' }],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX3',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một ca nô có vận tốc thực 20km/h, vận tốc dòng nước 3km/h. Tính vận tốc ca nô khi đi ngược dòng.',
    solutionSteps: [{ order: 1, content: '$20-3=17$km/h.', rationale: 'Vận tốc ngược dòng bằng vận tốc thực trừ vận tốc dòng nước.' }],
    numeric: { kind: 'single', acceptedValues: ['17'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX4',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người đi xe máy từ A đến B hết 5 giờ kể cả thời gian nghỉ, trong đó nghỉ 2 lần, mỗi lần 30 phút. Vận tốc đi là 30km/h. Tính quãng đường AB.',
    solutionSteps: [
      { order: 1, content: 'Tổng thời gian nghỉ $=2\\times30=60$ phút $=1$ giờ.', rationale: 'Đổi thời gian nghỉ về giờ.' },
      { order: 2, content: 'Thời gian đi thực tế $=5-1=4$ giờ; quãng đường $=30\\times4=120$km.', rationale: 'Trừ thời gian nghỉ rồi nhân với vận tốc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['120'], tolerance: 0, isInteger: true, unit: 'km' },
  },
  {
    id: 'DH-09-EX1',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Người thứ nhất làm xong việc trong 6 giờ, người thứ hai làm xong trong 12 giờ. Làm chung thì sau bao lâu (giờ) xong việc?',
    solutionSteps: [{ order: 1, content: 'Năng suất chung $=\\dfrac{1}{6}+\\dfrac{1}{12}=\\dfrac{2}{12}+\\dfrac{1}{12}=\\dfrac{3}{12}=\\dfrac{1}{4}$; thời gian $=4$ giờ.', rationale: 'Cộng năng suất rồi lấy nghịch đảo.' }],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0 },
  },
  {
    id: 'DH-09-EX2',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đội 6 người làm xong việc trong 10 ngày. Nếu có 5 người thì xong việc trong bao nhiêu ngày?',
    solutionSteps: [{ order: 1, content: 'Tổng người-ngày $=6\\times10=60$; với 5 người: $60:5=12$ ngày.', rationale: 'Số người và thời gian tỉ lệ nghịch.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-09-EX3',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Vòi thứ nhất chảy đầy bể trong 3 giờ, vòi thứ hai chảy đầy bể trong 6 giờ. Nếu mở cả hai vòi cùng lúc thì sau bao lâu (giờ) đầy bể?',
    solutionSteps: [{ order: 1, content: 'Năng suất chung $=\\dfrac{1}{3}+\\dfrac{1}{6}=\\dfrac{2}{6}+\\dfrac{1}{6}=\\dfrac{3}{6}=\\dfrac{1}{2}$; thời gian $=2$ giờ.', rationale: 'Cộng năng suất rồi lấy nghịch đảo.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0 },
  },
  {
    id: 'DH-09-EX4',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một công việc cần 12 người làm trong 5 ngày mới xong. Hỏi cần bao nhiêu người để làm xong công việc đó trong 4 ngày (năng suất mỗi người như nhau)?',
    solutionSteps: [{ order: 1, content: 'Tổng người-ngày $=12\\times5=60$; với 4 ngày cần $60:4=15$ người.', rationale: 'Số người và thời gian tỉ lệ nghịch.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-10-EX1',
    topicIds: ['DH-10'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một con đường dài 84m, trồng cây ở cả hai đầu, khoảng cách 6m. Hỏi cần bao nhiêu cây?',
    solutionSteps: [{ order: 1, content: '$84:6+1=15$ cây.', rationale: 'Đường thẳng có 2 đầu nên cộng thêm 1.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-10-EX2',
    topicIds: ['DH-10'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Trồng cây quanh một sân vận động hình chữ nhật có chu vi 200m, khoảng cách 10m. Hỏi cần bao nhiêu cây?',
    solutionSteps: [{ order: 1, content: 'Đường khép kín: $200:10=20$ cây.', rationale: 'Không cộng thêm 1 vì đường khép kín.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-10-EX3',
    topicIds: ['DH-10'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một hàng rào dài 45m, cắm cọc ở cả hai đầu với khoảng cách giữa hai cọc là 5m. Hỏi cần bao nhiêu cọc?',
    solutionSteps: [{ order: 1, content: '$45:5+1=10$ cọc.', rationale: 'Hàng rào thẳng có 2 đầu nên cộng thêm 1.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-11-EX1',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    hint: 'Thử giả sử TẤT CẢ đều là gà (loại có ít chân hơn), tính xem số chân thiếu bao nhiêu so với thực tế — phần thiếu đó chia cho mức chênh lệch chân giữa chó và gà sẽ ra số con chó.',
    statement: 'Vừa gà vừa chó có 30 con và 80 chân. Tính số con chó.',
    solutionSteps: [
      { order: 1, content: 'Giả sử tất cả là gà: $30\\times2=60$ chân; thiếu $80-60=20$ chân.', rationale: 'Giả thiết tạm toàn bộ là gà.' },
      { order: 2, content: 'Mỗi con chó hơn gà 2 chân; số chó $=20:2=10$.', rationale: 'Chia số chân thiếu cho mức chênh lệch mỗi con.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-11-EX2',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    hint: 'Trước tiên tìm số con chó bằng phương pháp giả thiết tạm (giả sử toàn bộ là gà rồi so sánh số chân), sau đó lấy tổng số con trừ đi số chó.',
    statement: 'Vừa gà vừa chó có 30 con và 80 chân. Tính số con gà.',
    solutionSteps: [
      { order: 1, content: 'Giả sử tất cả là gà: $30\\times2=60$ chân; thiếu $80-60=20$ chân; mỗi con chó hơn gà 2 chân nên số chó $=20:2=10$.', rationale: 'Giả thiết tạm để tìm số con chó trước.' },
      { order: 2, content: 'Số gà $=30-10=20$.', rationale: 'Lấy tổng số con trừ số chó.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-11-EX3',
    topicIds: ['DH-11'],
    level: 'advanced',
    answerType: 'numeric',
    hint: 'Thử giả sử TẤT CẢ đều là xe đạp (loại có ít bánh hơn), tính xem số bánh thiếu bao nhiêu so với thực tế — phần thiếu đó chia cho mức chênh lệch bánh giữa xe ba bánh và xe đạp sẽ ra số xe ba bánh.',
    statement: 'Có một số xe đạp (2 bánh) và xe ba bánh, tất cả có 25 xe và 58 bánh xe. Tính số xe ba bánh.',
    solutionSteps: [
      { order: 1, content: 'Giả sử tất cả là xe đạp: $25\\times2=50$ bánh; thiếu $58-50=8$ bánh.', rationale: 'Giả thiết tạm toàn bộ là xe đạp.' },
      { order: 2, content: 'Mỗi xe ba bánh hơn xe đạp 1 bánh; số xe ba bánh $=8:1=8$.', rationale: 'Chia số bánh thiếu cho mức chênh lệch mỗi xe.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-12-EX1',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    hint: 'Làm ngược lại các phép tính theo đúng thứ tự ngược của đề bài — phép tính nào làm SAU thì tính ngược TRƯỚC. Trừ ngược lại là cộng, chia ngược lại là nhân.',
    statement: 'Một số, sau khi trừ 7 rồi chia 4 thì được 9. Tìm số ban đầu.',
    solutionSteps: [
      { order: 1, content: 'Trước khi chia 4 để được 9, số đó là $9\\times4=36$.', rationale: 'Tính ngược phép chia thành phép nhân.' },
      { order: 2, content: 'Trước khi trừ 7 để được 36, số ban đầu là $36+7=43$.', rationale: 'Tính ngược phép trừ thành phép cộng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['43'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-12-EX2',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    hint: 'Làm ngược lại các phép tính theo đúng thứ tự ngược của đề bài — phép tính nào làm SAU thì tính ngược TRƯỚC. Cộng ngược lại là trừ, nhân ngược lại là chia.',
    statement: 'Một số, sau khi nhân 5 rồi cộng 6 thì được 56. Tìm số ban đầu.',
    solutionSteps: [
      { order: 1, content: 'Trước khi cộng $6$ để được $56$, số đó là $56-6=50$.', rationale: 'Tính ngược phép cộng thành phép trừ.' },
      { order: 2, content: 'Trước khi nhân $5$ để được $50$, số ban đầu là $50:5=10$.', rationale: 'Tính ngược phép nhân thành phép chia.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-12-EX3',
    topicIds: ['DH-12'],
    level: 'advanced',
    answerType: 'numeric',
    hint: 'Làm ngược lại các phép tính theo đúng thứ tự ngược của đề bài — phép tính nào làm SAU thì tính ngược TRƯỚC. Cộng ngược lại là trừ, chia ngược lại là nhân.',
    statement: 'Một số, sau khi chia 3 rồi cộng 8 thì được 20. Tìm số ban đầu.',
    solutionSteps: [
      { order: 1, content: 'Trước khi cộng $8$ để được $20$, số đó là $20-8=12$.', rationale: 'Tính ngược phép cộng thành phép trừ.' },
      { order: 2, content: 'Trước khi chia $3$ để được $12$, số ban đầu là $12\\times3=36$.', rationale: 'Tính ngược phép chia thành phép nhân.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['36'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-13-EX1',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Mua 4 cái bút hết 24 000đ. Hỏi mua 9 cái bút hết bao nhiêu tiền?',
    solutionSteps: [{ order: 1, content: 'Giá 1 bút $=24\\,000:4=6\\,000$đ; 9 bút hết $6\\,000\\times9=54\\,000$đ.', rationale: 'Rút về đơn vị rồi nhân với số lượng cần tìm.' }],
    numeric: { kind: 'single', acceptedValues: ['54000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-13-EX2',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: '5 công nhân làm xong một công việc trong 12 ngày. Hỏi 6 công nhân làm xong công việc đó trong bao nhiêu ngày?',
    solutionSteps: [{ order: 1, content: 'Người-ngày $=5\\times12=60$; với 6 người: $60:6=10$ ngày.', rationale: 'Tỉ lệ nghịch giữa số người và thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-13-EX3',
    topicIds: ['DH-13'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một ô tô đi 100km hết 8 lít xăng. Hỏi đi 250km hết bao nhiêu lít xăng?',
    solutionSteps: [{ order: 1, content: '1km hết $8:100=0{,}08$ lít; 250km hết $0{,}08\\times250=20$ lít.', rationale: 'Rút về đơn vị (1km) rồi nhân với quãng đường cần tìm.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true, unit: 'lít' },
  },
  {
    id: 'DH-14-EX1',
    topicIds: ['DH-14'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một máy dệt dệt được 900m vải trong 3 giờ. Tính năng suất (m/giờ).',
    solutionSteps: [{ order: 1, content: '$900:3=300$ m/giờ.', rationale: 'Chia khối lượng công việc cho thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['300'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-14-EX2',
    topicIds: ['DH-14'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Với năng suất 300m/giờ, máy dệt đó dệt được bao nhiêu mét vải trong 5 giờ?',
    solutionSteps: [{ order: 1, content: '$300\\times5=1500$m.', rationale: 'Nhân năng suất với thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['1500'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-14-EX3',
    topicIds: ['DH-14'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một cánh đồng 1000m² thu hoạch 450kg lúa. Một cánh đồng khác cùng năng suất có diện tích 2000m². Tính sản lượng thu hoạch của cánh đồng thứ hai.',
    solutionSteps: [
      { order: 1, content: 'Năng suất $=450:1000=0{,}45$kg/m².', rationale: 'Chia sản lượng cho diện tích.' },
      { order: 2, content: 'Sản lượng cánh đồng thứ hai $=0{,}45\\times2000=900$kg.', rationale: 'Nhân năng suất với diện tích mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['900'], tolerance: 0, isInteger: true },
  },
];
