import type { Exercise } from '../../types';

/**
 * Bổ sung bài tập cho các chuyên đề ưu tiên nhóm DH theo Mục 4.7 URD
 * (DH-01→03, DH-06→09), hướng tới mục tiêu 12–15 bài/chuyên đề.
 */
export const dhPriorityMoreExercises: Exercise[] = [
  // DH-01: Tổng và hiệu
  {
    id: 'DH-01-EX7',
    topicIds: ['DH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 150, hiệu hai số là 30. Tìm số bé.',
    solutionSteps: [{ order: 1, content: '$(150 - 30) : 2 = 60$.', rationale: 'Áp dụng công thức số bé = (Tổng - Hiệu) : 2.' }],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-01-EX8',
    topicIds: ['DH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 150, hiệu hai số là 30. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: '$(150 + 30) : 2 = 90$.', rationale: 'Áp dụng công thức số lớn = (Tổng + Hiệu) : 2.' }],
    numeric: { kind: 'single', acceptedValues: ['90'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-01-EX9',
    topicIds: ['DH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hai kho gạo chứa tổng cộng 850 tấn. Kho thứ nhất chứa ít hơn kho thứ hai 120 tấn. Tính số tấn gạo kho thứ nhất.',
    solutionSteps: [{ order: 1, content: 'Kho thứ nhất là số bé: $(850 - 120) : 2 = 365$ (tấn).', rationale: 'Kho chứa ít hơn ứng với số bé.' }],
    numeric: { kind: 'single', acceptedValues: ['365'], tolerance: 0, isInteger: true, unit: 'tấn' },
  },
  {
    id: 'DH-01-EX10',
    topicIds: ['DH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng số học sinh hai lớp 5A và 5B là 88. Lớp 5A có nhiều hơn lớp 5B 4 học sinh. Tính số học sinh lớp 5A.',
    solutionSteps: [{ order: 1, content: 'Lớp 5A là số lớn: $(88 + 4) : 2 = 46$ (học sinh).', rationale: 'Lớp có nhiều học sinh hơn ứng với số lớn.' }],
    numeric: { kind: 'single', acceptedValues: ['46'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-01-EX11',
    topicIds: ['DH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Tổng hai số là 60, hiệu hai số là 12. Số bé là số nào?',
    solutionSteps: [{ order: 1, content: '$(60 - 12) : 2 = 24$.', rationale: 'Áp dụng công thức số bé.' }],
    mcq: { options: ['20', '24', '28', '32'], answerIndex: 1 },
  },
  {
    id: 'DH-01-EX12',
    topicIds: ['DH-01'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một hình chữ nhật có nửa chu vi là 45cm. Biết chiều dài hơn chiều rộng 7cm. Tính chiều rộng.',
    solutionSteps: [
      { order: 1, content: 'Nửa chu vi chính là tổng chiều dài và chiều rộng: $45$.', rationale: 'Nửa chu vi = dài + rộng.' },
      { order: 2, content: 'Chiều rộng $= (45 - 7) : 2 = 19$ (cm).', rationale: 'Áp dụng công thức số bé cho bài toán tổng-hiệu.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['19'], tolerance: 0, isInteger: true, unit: 'cm' },
  },

  // DH-02: Tổng và tỉ
  {
    id: 'DH-02-EX5',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 84, tỉ số là 3:4. Tìm số bé.',
    solutionSteps: [{ order: 1, content: 'Tổng số phần $=3+4=7$; 1 phần $=84:7=12$; số bé $=12\\times3=36$.', rationale: 'Áp dụng phương pháp tổng-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['36'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX6',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 84, tỉ số là 3:4. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: '1 phần $=12$; số lớn $=12\\times4=48$.', rationale: 'Áp dụng phương pháp tổng-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['48'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX7',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 120. Số thứ hai gấp 5 lần số thứ nhất. Tìm số thứ nhất.',
    solutionSteps: [{ order: 1, content: 'Tỉ số $1:5$, tổng số phần $=6$; 1 phần $=120:6=20$.', rationale: 'Số thứ hai gấp 5 lần nghĩa là tỉ số 1:5.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX8',
    topicIds: ['DH-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đội có 63 người gồm nam và nữ. Số nam bằng $\\dfrac{2}{5}$ số nữ. Tính số nữ.',
    solutionSteps: [{ order: 1, content: 'Tỉ số nam:nữ $=2:5$, tổng số phần $=7$; 1 phần $=63:7=9$; nữ $=9\\times5=45$.', rationale: 'Đổi tỉ lệ phân số thành tỉ số phần.' }],
    numeric: { kind: 'single', acceptedValues: ['45'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX9',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tổng hai số là 96, tỉ số là 5:7. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: 'Tổng số phần $=12$; 1 phần $=96:12=8$; số lớn $=8\\times7=56$.', rationale: 'Áp dụng phương pháp tổng-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['56'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX10',
    topicIds: ['DH-02'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Tổng hai số là 42, tỉ số là 2:5. Số bé là bao nhiêu?',
    solutionSteps: [{ order: 1, content: 'Tổng số phần $=7$; 1 phần $=6$; số bé $=12$.', rationale: 'Áp dụng phương pháp tổng-tỉ.' }],
    mcq: { options: ['10', '12', '14', '16'], answerIndex: 1 },
  },
  {
    id: 'DH-02-EX11',
    topicIds: ['DH-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một thư viện có 245 quyển sách gồm sách Toán và sách Văn. Số sách Toán bằng $\\dfrac{3}{4}$ số sách Văn. Tính số sách Văn.',
    solutionSteps: [{ order: 1, content: 'Tỉ số Toán:Văn $=3:4$, tổng số phần $=7$; 1 phần $=245:7=35$; Văn $=35\\times4=140$.', rationale: 'Đổi tỉ lệ phân số thành tỉ số phần.' }],
    numeric: { kind: 'single', acceptedValues: ['140'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-02-EX12',
    topicIds: ['DH-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tổng hai số là 108. Tỉ số của số thứ nhất và số thứ hai là 4:5. Tìm hiệu hai số.',
    solutionSteps: [
      { order: 1, content: 'Tổng số phần $=9$; 1 phần $=108:9=12$.', rationale: 'Chia tổng cho tổng số phần.' },
      { order: 2, content: 'Số thứ nhất $=48$, số thứ hai $=60$; hiệu $=60-48=12$.', rationale: 'Tính từng số rồi lấy hiệu.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },

  // DH-03: Hiệu và tỉ
  {
    id: 'DH-03-EX5',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 56, tỉ số là 3:7. Tìm số bé.',
    solutionSteps: [{ order: 1, content: 'Hiệu số phần $=7-3=4$; 1 phần $=56:4=14$; số bé $=14\\times3=42$.', rationale: 'Áp dụng phương pháp hiệu-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['42'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX6',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 56, tỉ số là 3:7. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: '1 phần $=14$; số lớn $=14\\times7=98$.', rationale: 'Áp dụng phương pháp hiệu-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['98'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX7',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 48. Số lớn gấp 5 lần số bé. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: 'Tỉ số $1:5$, hiệu số phần $=4$; 1 phần $=12$; số lớn $=12\\times5=60$.', rationale: 'Số lớn gấp 5 lần số bé nghĩa là tỉ số 1:5.' }],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX8',
    topicIds: ['DH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một cửa hàng có số áo sơ mi nhiều hơn số áo thun 84 chiếc. Số áo thun bằng $\\dfrac{2}{5}$ số áo sơ mi. Tính số áo sơ mi.',
    solutionSteps: [{ order: 1, content: 'Tỉ số thun:sơ mi $=2:5$, hiệu số phần $=3$; 1 phần $=84:3=28$; sơ mi $=28\\times5=140$.', rationale: 'Đổi tỉ lệ phân số thành tỉ số phần.' }],
    numeric: { kind: 'single', acceptedValues: ['140'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX9',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 72, tỉ số là 5:8. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: 'Hiệu số phần $=3$; 1 phần $=24$; số lớn $=24\\times8=192$.', rationale: 'Áp dụng phương pháp hiệu-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['192'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-03-EX10',
    topicIds: ['DH-03'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Hiệu hai số là 27, tỉ số là 2:5. Số bé là bao nhiêu?',
    solutionSteps: [{ order: 1, content: 'Hiệu số phần $=3$; 1 phần $=9$; số bé $=18$.', rationale: 'Áp dụng phương pháp hiệu-tỉ.' }],
    mcq: { options: ['15', '18', '21', '24'], answerIndex: 1 },
  },
  {
    id: 'DH-03-EX11',
    topicIds: ['DH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tuổi mẹ hơn tuổi con 28 tuổi. Tuổi con bằng $\\dfrac{1}{5}$ tuổi mẹ. Tính tuổi con.',
    solutionSteps: [{ order: 1, content: 'Tỉ số con:mẹ $=1:5$, hiệu số phần $=4$; 1 phần $=28:4=7$.', rationale: 'Đổi tỉ lệ phân số thành tỉ số phần.' }],
    numeric: { kind: 'single', acceptedValues: ['7'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-03-EX12',
    topicIds: ['DH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiệu hai số là 63. Tỉ số của số bé và số lớn là 4:7. Tìm số lớn.',
    solutionSteps: [{ order: 1, content: 'Hiệu số phần $=7-4=3$; 1 phần $=63:3=21$; số lớn $=21\\times7=147$.', rationale: 'Áp dụng phương pháp hiệu-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['147'], tolerance: 0, isInteger: true },
  },

  // DH-06: Toán tính tuổi
  {
    id: 'DH-06-EX5',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiện nay tuổi bố gấp 6 lần tuổi con. Hiệu tuổi bố con là 40 tuổi. Tính tuổi con hiện nay.',
    solutionSteps: [{ order: 1, content: 'Tỉ số con:bố $=1:6$, hiệu số phần $=5$; 1 phần $=40:5=8$.', rationale: 'Áp dụng dạng hiệu-tỉ.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX6',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiện nay tuổi bố gấp 6 lần tuổi con. Hiệu tuổi bố con là 40 tuổi. Tính tuổi bố hiện nay.',
    solutionSteps: [{ order: 1, content: '1 phần $=8$; tuổi bố $=8\\times6=48$.', rationale: 'Bố ứng với 6 phần.' }],
    numeric: { kind: 'single', acceptedValues: ['48'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX7',
    topicIds: ['DH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Năm nay tuổi Hoa là 10. Hỏi 4 năm nữa Hoa bao nhiêu tuổi?',
    solutionSteps: [{ order: 1, content: '$10+4=14$ (tuổi).', rationale: 'Cộng thêm số năm trong tương lai.' }],
    numeric: { kind: 'single', acceptedValues: ['14'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX8',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hiện nay tuổi cô giáo gấp 3 lần tuổi học sinh. Hiệu tuổi là 24. Hỏi 6 năm nữa học sinh bao nhiêu tuổi?',
    solutionSteps: [
      { order: 1, content: 'Tỉ số học sinh:cô $=1:3$, hiệu số phần $=2$; tuổi học sinh hiện nay $=24:2=12$.', rationale: 'Áp dụng dạng hiệu-tỉ để tìm tuổi hiện tại.' },
      { order: 2, content: 'Sau 6 năm nữa: $12+6=18$ (tuổi).', rationale: 'Cộng thêm số năm trong tương lai.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['18'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX9',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tuổi ông hơn tuổi cháu 56 tuổi. Tuổi cháu bằng $\\dfrac{1}{8}$ tuổi ông. Tính tuổi cháu.',
    solutionSteps: [{ order: 1, content: 'Tỉ số cháu:ông $=1:8$, hiệu số phần $=7$; 1 phần $=56:7=8$.', rationale: 'Đổi tỉ lệ phân số thành tỉ số phần.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'DH-06-EX10',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Hiện nay tuổi bố gấp 4 lần tuổi con, hiệu tuổi là 27. Tính tuổi con hiện nay.',
    solutionSteps: [{ order: 1, content: 'Tỉ số $1:4$, hiệu số phần $=3$; 1 phần $=9$.', rationale: 'Áp dụng dạng hiệu-tỉ.' }],
    mcq: { options: ['6', '9', '12', '15'], answerIndex: 1 },
  },
  {
    id: 'DH-06-EX11',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Năm nay em 7 tuổi, anh 15 tuổi. Hỏi bao nhiêu năm nữa thì tuổi anh gấp đôi tuổi em?',
    solutionSteps: [
      { order: 1, content: 'Gọi số năm cần tìm là $x$: $15+x = 2\\times(7+x)$.', rationale: 'Hiệu tuổi anh em không đổi, chỉ tỉ số thay đổi theo thời gian.' },
      { order: 2, content: '$15+x=14+2x \\Rightarrow x=1$.', rationale: 'Giải phương trình.' },
      { order: 3, content: 'Kiểm tra: sau 1 năm em 8 tuổi, anh 16 tuổi, $16=2\\times8$ (đúng).', rationale: 'Đối chiếu lại kết quả.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['1'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-06-EX12',
    topicIds: ['DH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tuổi bố hiện nay là 36, tuổi con là 8. Hỏi bao nhiêu năm trước thì tuổi bố gấp 5 lần tuổi con?',
    solutionSteps: [
      { order: 1, content: 'Gọi số năm trước là $x$: $36-x = 5\\times(8-x)$.', rationale: 'Hiệu tuổi không đổi theo thời gian.' },
      { order: 2, content: '$36-x=40-5x \\Rightarrow 4x=4 \\Rightarrow x=1$.', rationale: 'Giải phương trình.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['1'], tolerance: 0, isInteger: true },
  },

  // DH-07: Toán chuyển động cơ bản
  {
    id: 'DH-07-EX5',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai xe máy xuất phát cùng lúc từ hai địa điểm cách nhau 150km, đi ngược chiều nhau với vận tốc 35km/h và 40km/h. Hỏi sau bao lâu (giờ) hai xe gặp nhau?',
    solutionSteps: [{ order: 1, content: 'Tổng vận tốc $=35+40=75$km/h; thời gian gặp nhau $=150:75=2$ giờ.', rationale: 'Áp dụng công thức thời gian gặp nhau.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0 },
  },
  {
    id: 'DH-07-EX6',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người đi bộ vận tốc 5km/h xuất phát trước một người đi xe đạp 1 giờ. Người đi xe đạp đuổi theo với vận tốc 15km/h. Hỏi sau bao lâu (giờ, kể từ lúc xe đạp xuất phát) xe đạp đuổi kịp người đi bộ?',
    solutionSteps: [
      { order: 1, content: 'Khi xe đạp xuất phát, người đi bộ đã đi được $5\\times1=5$km.', rationale: 'Tính khoảng cách ban đầu.' },
      { order: 2, content: 'Hiệu vận tốc $=15-5=10$km/h; thời gian đuổi kịp $=5:10=0{,}5$ giờ.', rationale: 'Áp dụng công thức thời gian đuổi kịp.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['0.5'], tolerance: 0 },
  },
  {
    id: 'DH-07-EX7',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai ô tô cách nhau 420km đi ngược chiều, vận tốc 60km/h và 80km/h. Hỏi sau bao lâu (giờ) hai xe gặp nhau?',
    solutionSteps: [{ order: 1, content: 'Tổng vận tốc $=140$km/h; thời gian gặp nhau $=420:140=3$ giờ.', rationale: 'Áp dụng công thức thời gian gặp nhau.' }],
    numeric: { kind: 'single', acceptedValues: ['3'], tolerance: 0 },
  },
  {
    id: 'DH-07-EX8',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một xe tải đi từ A lúc 7 giờ với vận tốc 45km/h. Một xe con đi từ A lúc 9 giờ đuổi theo với vận tốc 60km/h. Hỏi xe con đuổi kịp xe tải lúc mấy giờ (nhập số giờ trong ngày)?',
    solutionSteps: [
      { order: 1, content: 'Khi xe con xuất phát (9 giờ), xe tải đã đi được $45\\times2=90$km.', rationale: 'Xe tải đi trước 2 giờ.' },
      { order: 2, content: 'Hiệu vận tốc $=60-45=15$km/h; thời gian đuổi kịp $=90:15=6$ giờ.', rationale: 'Áp dụng công thức thời gian đuổi kịp.' },
      { order: 3, content: 'Đuổi kịp lúc $9+6=15$ giờ.', rationale: 'Cộng vào giờ xuất phát của xe con.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-07-EX9',
    topicIds: ['DH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai xe đạp xuất phát cùng lúc từ hai điểm cách nhau 51km, đi ngược chiều nhau, gặp nhau sau 3 giờ. Biết vận tốc xe thứ nhất là 8km/h. Tính vận tốc xe thứ hai.',
    solutionSteps: [
      { order: 1, content: 'Tổng vận tốc hai xe $=51:3=17$km/h.', rationale: 'Suy ra tổng vận tốc từ quãng đường và thời gian gặp nhau.' },
      { order: 2, content: 'Vận tốc xe thứ hai $=17-8=9$km/h.', rationale: 'Lấy tổng vận tốc trừ vận tốc xe thứ nhất.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true, unit: 'km/h' },
  },
  {
    id: 'DH-07-EX10',
    topicIds: ['DH-07'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Hai xe cách nhau 100km đi ngược chiều, vận tốc 30km/h và 20km/h. Sau bao lâu gặp nhau?',
    solutionSteps: [{ order: 1, content: 'Tổng vận tốc $=50$km/h; $100:50=2$ giờ.', rationale: 'Áp dụng công thức thời gian gặp nhau.' }],
    mcq: { options: ['1 giờ', '2 giờ', '3 giờ', '4 giờ'], answerIndex: 1 },
  },
  {
    id: 'DH-07-EX11',
    topicIds: ['DH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một người đi xe đạp từ A đến B với vận tốc 12km/h hết 2,5 giờ. Tính quãng đường AB.',
    solutionSteps: [{ order: 1, content: '$12\\times2{,}5=30$km.', rationale: 'Áp dụng công thức quãng đường = vận tốc × thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['30'], tolerance: 0, isInteger: true, unit: 'km' },
  },
  {
    id: 'DH-07-EX12',
    topicIds: ['DH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Quãng đường AB dài 90km. Một ô tô đi từ A đến B với vận tốc 45km/h. Tính thời gian đi hết quãng đường AB.',
    solutionSteps: [{ order: 1, content: '$90:45=2$ giờ.', rationale: 'Thời gian = quãng đường : vận tốc.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0 },
  },

  // DH-08: Toán chuyển động nâng cao
  {
    id: 'DH-08-EX5',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một ca nô xuôi dòng vận tốc 30km/h, ngược dòng vận tốc 22km/h. Tính vận tốc thực.',
    solutionSteps: [{ order: 1, content: '$(30+22):2=26$km/h.', rationale: 'Áp dụng công thức tính vận tốc thực.' }],
    numeric: { kind: 'single', acceptedValues: ['26'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX6',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một ca nô xuôi dòng vận tốc 30km/h, ngược dòng vận tốc 22km/h. Tính vận tốc dòng nước.',
    solutionSteps: [{ order: 1, content: '$(30-22):2=4$km/h.', rationale: 'Áp dụng công thức tính vận tốc dòng nước.' }],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX7',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một ca nô có vận tốc thực 18km/h, vận tốc dòng nước 2km/h. Tính vận tốc ca nô khi xuôi dòng.',
    solutionSteps: [{ order: 1, content: '$18+2=20$km/h.', rationale: 'Vận tốc xuôi dòng = vận tốc thực + vận tốc dòng nước.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-08-EX8',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người đi xe máy trong 5 giờ kể cả thời gian nghỉ, nghỉ giữa đường 2 lần, mỗi lần 15 phút. Vận tốc đi là 40km/h. Tính quãng đường.',
    solutionSteps: [
      { order: 1, content: 'Tổng thời gian nghỉ $=2\\times15=30$ phút $=0{,}5$ giờ.', rationale: 'Đổi thời gian nghỉ về giờ.' },
      { order: 2, content: 'Thời gian đi thực tế $=5-0{,}5=4{,}5$ giờ; quãng đường $=40\\times4{,}5=180$km.', rationale: 'Trừ thời gian nghỉ rồi nhân vận tốc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['180'], tolerance: 0, isInteger: true, unit: 'km' },
  },
  {
    id: 'DH-08-EX9',
    topicIds: ['DH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một ca nô xuôi dòng từ A đến B hết 3 giờ, vận tốc xuôi dòng 24km/h. Tính quãng đường AB.',
    solutionSteps: [{ order: 1, content: '$24\\times3=72$km.', rationale: 'Quãng đường = vận tốc × thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true, unit: 'km' },
  },
  {
    id: 'DH-08-EX10',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Ca nô có vận tốc thực 15km/h, dòng nước 3km/h. Vận tốc ngược dòng là bao nhiêu?',
    solutionSteps: [{ order: 1, content: '$15-3=12$km/h.', rationale: 'Vận tốc ngược dòng = vận tốc thực - vận tốc dòng nước.' }],
    mcq: { options: ['9km/h', '12km/h', '15km/h', '18km/h'], answerIndex: 1 },
  },
  {
    id: 'DH-08-EX11',
    topicIds: ['DH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người đi ô tô từ A đến B mất 6 giờ kể cả thời gian nghỉ 1 giờ. Vận tốc đi là 50km/h. Tính quãng đường AB.',
    solutionSteps: [
      { order: 1, content: 'Thời gian đi thực tế $=6-1=5$ giờ.', rationale: 'Trừ thời gian nghỉ.' },
      { order: 2, content: 'Quãng đường $=50\\times5=250$km.', rationale: 'Nhân vận tốc với thời gian đi thực tế.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['250'], tolerance: 0, isInteger: true, unit: 'km' },
  },
  {
    id: 'DH-08-EX12',
    topicIds: ['DH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một ca nô ngược dòng từ B về A hết 4 giờ, vận tốc ngược dòng 18km/h. Tính quãng đường AB.',
    solutionSteps: [{ order: 1, content: '$18\\times4=72$km.', rationale: 'Quãng đường = vận tốc × thời gian.' }],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true, unit: 'km' },
  },

  // DH-09: Toán công việc chung
  {
    id: 'DH-09-EX5',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Người thứ nhất làm xong việc trong 8 giờ, người thứ hai làm xong trong 8 giờ. Làm chung thì sau bao lâu (giờ) xong việc?',
    solutionSteps: [{ order: 1, content: 'Năng suất chung $=\\dfrac{1}{8}+\\dfrac{1}{8}=\\dfrac{1}{4}$; thời gian $=4$ giờ.', rationale: 'Cộng năng suất rồi lấy nghịch đảo.' }],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0 },
  },
  {
    id: 'DH-09-EX6',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đội 8 người làm xong việc trong 15 ngày. Nếu có 12 người thì xong việc trong bao nhiêu ngày?',
    solutionSteps: [{ order: 1, content: 'Tổng người-ngày $=8\\times15=120$; với 12 người: $120:12=10$ ngày.', rationale: 'Số người và thời gian tỉ lệ nghịch.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-09-EX7',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Vòi thứ nhất chảy đầy bể trong 4 giờ, vòi thứ hai chảy đầy bể trong 12 giờ. Mở cả hai vòi cùng lúc thì sau bao lâu (giờ) đầy bể?',
    solutionSteps: [{ order: 1, content: 'Năng suất chung $=\\dfrac{1}{4}+\\dfrac{1}{12}=\\dfrac{3}{12}+\\dfrac{1}{12}=\\dfrac{4}{12}=\\dfrac{1}{3}$; thời gian $=3$ giờ.', rationale: 'Cộng năng suất rồi lấy nghịch đảo.' }],
    numeric: { kind: 'single', acceptedValues: ['3'], tolerance: 0 },
  },
  {
    id: 'DH-09-EX8',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một công việc cần 15 người làm trong 8 ngày. Hỏi cần bao nhiêu người để làm xong trong 6 ngày?',
    solutionSteps: [{ order: 1, content: 'Tổng người-ngày $=15\\times8=120$; với 6 ngày cần $120:6=20$ người.', rationale: 'Số người và thời gian tỉ lệ nghịch.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-09-EX9',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Người thứ nhất làm riêng xong việc trong 10 giờ, người thứ hai làm riêng xong việc trong 15 giờ. Làm chung thì sau bao lâu (giờ) xong việc?',
    solutionSteps: [{ order: 1, content: 'Năng suất chung $=\\dfrac{1}{10}+\\dfrac{1}{15}=\\dfrac{3}{30}+\\dfrac{2}{30}=\\dfrac{5}{30}=\\dfrac{1}{6}$; thời gian $=6$ giờ.', rationale: 'Cộng năng suất rồi lấy nghịch đảo.' }],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0 },
  },
  {
    id: 'DH-09-EX10',
    topicIds: ['DH-09'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Hai vòi nước cùng chảy vào 1 bể, mỗi vòi chảy riêng đầy bể trong 6 giờ. Mở cùng lúc, sau bao lâu đầy bể?',
    solutionSteps: [{ order: 1, content: 'Năng suất chung $=\\dfrac{1}{6}+\\dfrac{1}{6}=\\dfrac{1}{3}$; thời gian $=3$ giờ.', rationale: 'Cộng năng suất rồi lấy nghịch đảo.' }],
    mcq: { options: ['2 giờ', '3 giờ', '4 giờ', '6 giờ'], answerIndex: 1 },
  },
  {
    id: 'DH-09-EX11',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đội 10 người làm xong việc trong 12 ngày. Nếu bớt đi 2 người thì cần bao nhiêu ngày để làm xong?',
    solutionSteps: [{ order: 1, content: 'Tổng người-ngày $=10\\times12=120$; còn 8 người: $120:8=15$ ngày.', rationale: 'Số người và thời gian tỉ lệ nghịch.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-09-EX12',
    topicIds: ['DH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Vòi thứ nhất chảy một mình đầy bể trong 6 giờ. Nếu mở cả hai vòi thì sau 4 giờ đầy bể. Tính thời gian vòi thứ hai chảy một mình đầy bể (giờ).',
    solutionSteps: [
      { order: 1, content: 'Năng suất vòi 1 $=\\dfrac{1}{6}$; năng suất chung $=\\dfrac{1}{4}$.', rationale: 'Năng suất bằng 1 chia thời gian.' },
      { order: 2, content: 'Năng suất vòi 2 $=\\dfrac{1}{4}-\\dfrac{1}{6}=\\dfrac{3}{12}-\\dfrac{2}{12}=\\dfrac{1}{12}$; thời gian vòi 2 $=12$ giờ.', rationale: 'Lấy năng suất chung trừ năng suất vòi 1.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
];
