import type { Exercise } from '../../types';

/** Mở rộng bài tập cho các chuyên đề DL, hướng tới 6–8 bài/chuyên đề. */
export const dlExpandExercises: Exercise[] = [
  // DL-01
  {
    id: 'DL-01-EX4',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $9\\,km$ sang mét.',
    solutionSteps: [{ order: 1, content: '$9\\times1000=9000$m.', rationale: 'Nhân với 1000 khi đổi km sang m.' }],
    numeric: { kind: 'single', acceptedValues: ['9000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-01-EX5',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $4{,}7\\,kg$ sang g.',
    solutionSteps: [{ order: 1, content: '$4{,}7\\times1000=4700$g.', rationale: 'Nhân với 1000 khi đổi kg sang g.' }],
    numeric: { kind: 'single', acceptedValues: ['4700'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-01-EX6',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $650\\,cm$ sang mét.',
    solutionSteps: [{ order: 1, content: '$650:100=6{,}5$m.', rationale: 'Chia cho 100 khi đổi cm sang m.' }],
    numeric: { kind: 'single', acceptedValues: ['6.5'], tolerance: 0 },
  },
  {
    id: 'DL-01-EX7',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $3200\\,g$ sang kg.',
    solutionSteps: [{ order: 1, content: '$3200:1000=3{,}2$kg.', rationale: 'Chia cho 1000 khi đổi g sang kg.' }],
    numeric: { kind: 'single', acceptedValues: ['3.2'], tolerance: 0 },
  },

  // DL-02
  {
    id: 'DL-02-EX4',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $6\\,m^2$ sang $dm^2$.',
    solutionSteps: [{ order: 1, content: '$6\\times100=600\\,dm^2$.', rationale: 'Nhân với 100 khi đổi m² sang dm².' }],
    numeric: { kind: 'single', acceptedValues: ['600'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-02-EX5',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $5\\,ha$ sang $m^2$.',
    solutionSteps: [{ order: 1, content: '$5\\times10\\,000=50\\,000\\,m^2$.', rationale: '1ha = 10 000m².' }],
    numeric: { kind: 'single', acceptedValues: ['50000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-02-EX6',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $15\\,000\\,m^2$ sang ha.',
    solutionSteps: [{ order: 1, content: '$15\\,000:10\\,000=1{,}5\\,ha$.', rationale: '1ha = 10 000m².' }],
    numeric: { kind: 'single', acceptedValues: ['1.5'], tolerance: 0 },
  },
  {
    id: 'DL-02-EX7',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $4\\,dm^2$ sang $cm^2$.',
    solutionSteps: [{ order: 1, content: '$4\\times100=400\\,cm^2$.', rationale: 'Nhân với 100 khi đổi dm² sang cm².' }],
    numeric: { kind: 'single', acceptedValues: ['400'], tolerance: 0, isInteger: true },
  },

  // DL-03
  {
    id: 'DL-03-EX4',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $7\\,m^3$ sang $dm^3$.',
    solutionSteps: [{ order: 1, content: '$7\\times1000=7000\\,dm^3$.', rationale: 'Nhân với 1000 khi đổi m³ sang dm³.' }],
    numeric: { kind: 'single', acceptedValues: ['7000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-03-EX5',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $9000\\,cm^3$ sang lít.',
    solutionSteps: [{ order: 1, content: '$9000:1000=9$ lít.', rationale: '1 lít = 1000cm³.' }],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-03-EX6',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $6$ lít sang $cm^3$.',
    solutionSteps: [{ order: 1, content: '$6\\times1000=6000\\,cm^3$.', rationale: '1 lít = 1000cm³.' }],
    numeric: { kind: 'single', acceptedValues: ['6000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-03-EX7',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $4500\\,cm^3$ sang $dm^3$.',
    solutionSteps: [{ order: 1, content: '$4500:1000=4{,}5\\,dm^3$.', rationale: 'Chia cho 1000 khi đổi cm³ sang dm³.' }],
    numeric: { kind: 'single', acceptedValues: ['4.5'], tolerance: 0 },
  },

  // DL-04
  {
    id: 'DL-04-EX4',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $4$ giờ $15$ phút sang phút.',
    solutionSteps: [{ order: 1, content: '$4\\times60+15=255$ phút.', rationale: 'Đổi giờ sang phút rồi cộng thêm.' }],
    numeric: { kind: 'single', acceptedValues: ['255'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-04-EX5',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $3$ giờ $40$ phút $+ 2$ giờ $35$ phút. Đổi kết quả sang phút.',
    solutionSteps: [
      { order: 1, content: '$3$ giờ $40$ phút $=220$ phút; $2$ giờ $35$ phút $=155$ phút.', rationale: 'Đổi cả hai số đo về phút.' },
      { order: 2, content: '$220+155=375$ phút.', rationale: 'Cộng hai số đo đã đổi cùng đơn vị.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['375'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-04-EX6',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một trận đấu bắt đầu lúc $15$ giờ $45$ phút, kết thúc lúc $17$ giờ $20$ phút. Trận đấu kéo dài bao nhiêu phút?',
    solutionSteps: [
      { order: 1, content: 'Từ $15$h$45$ đến $17$h$45$ là $2$ giờ $=120$ phút.', rationale: 'Tính khoảng thời gian tròn giờ trước.' },
      { order: 2, content: 'Trận đấu kết thúc sớm hơn $25$ phút (lúc $17$h$20$), nên thời lượng $=120-25=95$ phút.', rationale: 'Trừ đi phần chênh lệch còn lại.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['95'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-04-EX7',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $150$ phút sang giờ và phút. Nhập số giờ.',
    solutionSteps: [{ order: 1, content: '$150:60=2$ dư $30$, vậy $150$ phút $=2$ giờ $30$ phút.', rationale: 'Chia cho 60 để đổi phút sang giờ.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },

  // DL-05
  {
    id: 'DL-05-EX4',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bản đồ tỉ lệ $1:1\\,500\\,000$. Khoảng cách trên bản đồ là $4\\,cm$. Tính khoảng cách thực tế (km).',
    solutionSteps: [
      { order: 1, content: 'Khoảng cách thực tế $=4\\times1\\,500\\,000=6\\,000\\,000$cm.', rationale: 'Áp dụng công thức tỉ lệ bản đồ.' },
      { order: 2, content: '$6\\,000\\,000$cm $=60$km.', rationale: 'Đổi cm sang km.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-05-EX5',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Khoảng cách thực tế là $60$km. Bản đồ tỉ lệ $1:3\\,000\\,000$. Tính khoảng cách trên bản đồ (cm).',
    solutionSteps: [
      { order: 1, content: '$60$km $=6\\,000\\,000$cm.', rationale: 'Đổi km sang cm trước.' },
      { order: 2, content: 'Khoảng cách trên bản đồ $=6\\,000\\,000:3\\,000\\,000=2$cm.', rationale: 'Chia độ dài thực tế cho mẫu số tỉ lệ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-05-EX6',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bản đồ tỉ lệ $1:200\\,000$. Khoảng cách trên bản đồ là $7\\,cm$. Tính khoảng cách thực tế (km).',
    solutionSteps: [
      { order: 1, content: 'Khoảng cách thực tế $=7\\times200\\,000=1\\,400\\,000$cm.', rationale: 'Áp dụng công thức tỉ lệ bản đồ.' },
      { order: 2, content: '$1\\,400\\,000$cm $=14$km.', rationale: 'Đổi cm sang km.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['14'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-05-EX7',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Khoảng cách thực tế là $45$km. Bản đồ tỉ lệ $1:1\\,500\\,000$. Tính khoảng cách trên bản đồ (cm).',
    solutionSteps: [
      { order: 1, content: '$45$km $=4\\,500\\,000$cm.', rationale: 'Đổi km sang cm trước.' },
      { order: 2, content: 'Khoảng cách trên bản đồ $=4\\,500\\,000:1\\,500\\,000=3$cm.', rationale: 'Chia độ dài thực tế cho mẫu số tỉ lệ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['3'], tolerance: 0, isInteger: true },
  },

  // DL-06
  {
    id: 'DL-06-EX4',
    topicIds: ['DL-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Mua $6\\,kg$ đường hết $108\\,000$đ. Tính đơn giá $1kg$ đường.',
    solutionSteps: [{ order: 1, content: '$108\\,000:6=18\\,000$đ.', rationale: 'Chia tổng tiền cho số lượng.' }],
    numeric: { kind: 'single', acceptedValues: ['18000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-06-EX5',
    topicIds: ['DL-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đơn giá $1$ quyển sách là $25\\,000$đ. Mua $8$ quyển hết bao nhiêu tiền?',
    solutionSteps: [{ order: 1, content: '$25\\,000\\times8=200\\,000$đ.', rationale: 'Nhân đơn giá với số lượng.' }],
    numeric: { kind: 'single', acceptedValues: ['200000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-06-EX6',
    topicIds: ['DL-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement:
      'Một hóa đơn ghi: mua $4\\,kg$ cá hết $260\\,000$đ. Hỏi nếu mua thêm $3kg$ cá nữa (cùng đơn giá) thì tổng cộng (7kg) phải trả bao nhiêu tiền?',
    solutionSteps: [
      { order: 1, content: 'Đơn giá $=260\\,000:4=65\\,000$đ/kg.', rationale: 'Tìm đơn giá từ hóa đơn ban đầu.' },
      { order: 2, content: 'Tổng tiền cho $7kg$ $=65\\,000\\times7=455\\,000$đ.', rationale: 'Nhân đơn giá với tổng số lượng mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['455000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-06-EX7',
    topicIds: ['DL-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Mua $5$ chiếc bút hết $45\\,000$đ. Hỏi mua $12$ chiếc bút cùng loại hết bao nhiêu tiền?',
    solutionSteps: [
      { order: 1, content: 'Đơn giá $=45\\,000:5=9\\,000$đ.', rationale: 'Chia tổng tiền cho số lượng.' },
      { order: 2, content: 'Tổng tiền $12$ chiếc $=9\\,000\\times12=108\\,000$đ.', rationale: 'Nhân đơn giá với số lượng mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['108000'], tolerance: 0, isInteger: true },
  },
];
