import type { Exercise } from '../../types';

export const dlExercises: Exercise[] = [
  {
    id: 'DL-01-EX1',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $7\\,km$ sang mét.',
    solutionSteps: [{ order: 1, content: '$7\\times1000=7000$m.', rationale: 'Nhân với 1000 khi đổi km sang m.' }],
    numeric: { kind: 'single', acceptedValues: ['7000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-01-EX2',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $3{,}2\\,kg$ sang g.',
    solutionSteps: [{ order: 1, content: '$3{,}2\\times1000=3200$g.', rationale: 'Nhân với 1000 khi đổi kg sang g.' }],
    numeric: { kind: 'single', acceptedValues: ['3200'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-01-EX3',
    topicIds: ['DL-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $450\\,cm$ sang mét.',
    solutionSteps: [{ order: 1, content: '$450:100=4{,}5$m.', rationale: 'Chia cho 100 khi đổi cm sang m.' }],
    numeric: { kind: 'single', acceptedValues: ['4.5'], tolerance: 0 },
  },
  {
    id: 'DL-02-EX1',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $8\\,m^2$ sang $dm^2$.',
    solutionSteps: [{ order: 1, content: '$8\\times100=800\\,dm^2$.', rationale: 'Nhân với 100 khi đổi m² sang dm².' }],
    numeric: { kind: 'single', acceptedValues: ['800'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-02-EX2',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $4\\,ha$ sang $m^2$.',
    solutionSteps: [{ order: 1, content: '$4\\times10\\,000=40\\,000\\,m^2$.', rationale: '1ha = 10 000m².' }],
    numeric: { kind: 'single', acceptedValues: ['40000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-02-EX3',
    topicIds: ['DL-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $20\\,000\\,m^2$ sang ha.',
    solutionSteps: [{ order: 1, content: '$20\\,000:10\\,000=2\\,ha$.', rationale: '1ha = 10 000m².' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-03-EX1',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $5\\,m^3$ sang $dm^3$.',
    solutionSteps: [{ order: 1, content: '$5\\times1000=5000\\,dm^3$.', rationale: 'Nhân với 1000 khi đổi m³ sang dm³.' }],
    numeric: { kind: 'single', acceptedValues: ['5000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-03-EX2',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $12\\,000\\,cm^3$ sang lít.',
    solutionSteps: [{ order: 1, content: '$12\\,000:1000=12$ lít.', rationale: '1 lít = 1000cm³.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-03-EX3',
    topicIds: ['DL-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một thùng chứa $8$ lít nước. Đổi sang $cm^3$.',
    solutionSteps: [{ order: 1, content: '$8\\times1000=8000\\,cm^3$.', rationale: '1 lít = 1000cm³.' }],
    numeric: { kind: 'single', acceptedValues: ['8000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-04-EX1',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $3$ giờ $30$ phút sang phút.',
    solutionSteps: [{ order: 1, content: '$3\\times60+30=210$ phút.', rationale: 'Đổi giờ sang phút rồi cộng thêm.' }],
    numeric: { kind: 'single', acceptedValues: ['210'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-04-EX2',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $2$ giờ $20$ phút $+ 1$ giờ $50$ phút. Đổi kết quả sang phút.',
    solutionSteps: [
      { order: 1, content: '$2$ giờ $20$ phút $=140$ phút; $1$ giờ $50$ phút $=110$ phút.', rationale: 'Đổi cả hai số đo về phút.' },
      { order: 2, content: '$140+110=250$ phút.', rationale: 'Cộng hai số đo đã đổi cùng đơn vị.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['250'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-04-EX3',
    topicIds: ['DL-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một bộ phim bắt đầu lúc $14$ giờ $30$ phút và kết thúc lúc $16$ giờ $15$ phút. Phim dài bao nhiêu phút?',
    solutionSteps: [
      { order: 1, content: 'Từ $14$h$30$ đến $16$h$30$ là $2$ giờ $=120$ phút.', rationale: 'Tính khoảng thời gian tròn giờ trước.' },
      { order: 2, content: 'Nhưng phim kết thúc sớm hơn $15$ phút (lúc $16$h$15$), nên thời lượng $=120-15=105$ phút.', rationale: 'Trừ đi phần chênh lệch còn lại.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['105'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-05-EX1',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bản đồ tỉ lệ $1:2\\,000\\,000$. Khoảng cách trên bản đồ là $6\\,cm$. Tính khoảng cách thực tế (km).',
    solutionSteps: [
      { order: 1, content: 'Khoảng cách thực tế $=6\\times2\\,000\\,000=12\\,000\\,000$cm.', rationale: 'Áp dụng công thức tỉ lệ bản đồ.' },
      { order: 2, content: '$12\\,000\\,000$cm $=120$km.', rationale: 'Đổi cm sang km.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['120'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-05-EX2',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Khoảng cách thực tế là $25$km. Bản đồ tỉ lệ $1:500\\,000$. Tính khoảng cách trên bản đồ (cm).',
    solutionSteps: [
      { order: 1, content: '$25$km $=2\\,500\\,000$cm.', rationale: 'Đổi km sang cm trước.' },
      { order: 2, content: 'Khoảng cách trên bản đồ $=2\\,500\\,000:500\\,000=5$cm.', rationale: 'Chia độ dài thực tế cho mẫu số tỉ lệ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['5'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-05-EX3',
    topicIds: ['DL-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bản đồ tỉ lệ $1:100\\,000$. Khoảng cách trên bản đồ là $8\\,cm$. Tính khoảng cách thực tế (km).',
    solutionSteps: [
      { order: 1, content: 'Khoảng cách thực tế $=8\\times100\\,000=800\\,000$cm.', rationale: 'Áp dụng công thức tỉ lệ bản đồ.' },
      { order: 2, content: '$800\\,000$cm $=8$km.', rationale: 'Đổi cm sang km.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-06-EX1',
    topicIds: ['DL-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Mua $8\\,kg$ gạo hết $136\\,000$đ. Tính đơn giá $1kg$ gạo.',
    solutionSteps: [{ order: 1, content: '$136\\,000:8=17\\,000$đ.', rationale: 'Chia tổng tiền cho số lượng.' }],
    numeric: { kind: 'single', acceptedValues: ['17000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-06-EX2',
    topicIds: ['DL-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đơn giá $1$ chiếc bánh là $12\\,000$đ. Mua $15$ chiếc hết bao nhiêu tiền?',
    solutionSteps: [{ order: 1, content: '$12\\,000\\times15=180\\,000$đ.', rationale: 'Nhân đơn giá với số lượng.' }],
    numeric: { kind: 'single', acceptedValues: ['180000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-06-EX3',
    topicIds: ['DL-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một hóa đơn ghi: mua $3\\,kg$ thịt hết $270\\,000$đ. Hỏi nếu mua thêm $2kg$ thịt nữa (cùng đơn giá) thì tổng cộng (5kg) phải trả bao nhiêu tiền?',
    solutionSteps: [
      { order: 1, content: 'Đơn giá $=270\\,000:3=90\\,000$đ/kg.', rationale: 'Tìm đơn giá từ hóa đơn ban đầu.' },
      { order: 2, content: 'Tổng tiền cho $5kg$ $=90\\,000\\times5=450\\,000$đ.', rationale: 'Nhân đơn giá với tổng số lượng mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['450000'], tolerance: 0, isInteger: true },
  },
];
