import type { Exercise } from '../../types';

/** Mở rộng bài tập cho các chuyên đề HH chưa ưu tiên, hướng tới 6–8 bài/chuyên đề. */
export const hhExpandExercises: Exercise[] = [
  // HH-01
  {
    id: 'HH-01-EX4',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Góc có số đo $170°$ là loại góc gì?',
    solutionSteps: [{ order: 1, content: '$170°$ lớn hơn $90°$ và nhỏ hơn $180°$ nên là góc tù.', rationale: 'Áp dụng định nghĩa góc tù.' }],
    mcq: { options: ['Góc tù', 'Góc bẹt', 'Góc vuông', 'Góc nhọn'], answerIndex: 0 },
  },
  {
    id: 'HH-01-EX5',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Trong các góc $20°$, $95°$, $180°$, $60°$, góc nào là góc bẹt?',
    solutionSteps: [{ order: 1, content: 'Góc bẹt có số đo đúng bằng $180°$.', rationale: 'Định nghĩa góc bẹt.' }],
    mcq: { options: ['20°', '95°', '180°', '60°'], answerIndex: 2 },
  },
  {
    id: 'HH-01-EX6',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Góc có số đo $88°$ là loại góc gì?',
    solutionSteps: [{ order: 1, content: '$88°<90°$ nên là góc nhọn.', rationale: 'So sánh với góc vuông 90°.' }],
    mcq: { options: ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], answerIndex: 0 },
  },
  {
    id: 'HH-01-EX7',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Góc tù có số đo lớn hơn bao nhiêu độ (nhập số)?',
    solutionSteps: [{ order: 1, content: 'Góc tù có số đo lớn hơn $90°$ và nhỏ hơn $180°$.', rationale: 'Định nghĩa góc tù.' }],
    numeric: { kind: 'single', acceptedValues: ['90'], tolerance: 0, isInteger: true },
  },

  // HH-05
  {
    id: 'HH-05-EX4',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình bình hành có đáy $14\\,cm$, chiều cao $7\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$14\\times7=98$.', rationale: 'Áp dụng công thức diện tích hình bình hành.' }],
    numeric: { kind: 'single', acceptedValues: ['98'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-05-EX5',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thoi có hai đường chéo $16\\,cm$ và $10\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$16\\times10:2=80$.', rationale: 'Áp dụng công thức diện tích hình thoi.' }],
    numeric: { kind: 'single', acceptedValues: ['80'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-05-EX6',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình bình hành có diện tích $84\\,cm^2$, đáy $12\\,cm$. Tính chiều cao ($cm$).',
    solutionSteps: [{ order: 1, content: '$84:12=7$.', rationale: 'Suy ra chiều cao từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['7'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-05-EX7',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thoi có diện tích $60\\,cm^2$, một đường chéo $12\\,cm$. Tính đường chéo còn lại ($cm$).',
    solutionSteps: [{ order: 1, content: '$60\\times2:12=10$.', rationale: 'Suy ra đường chéo còn lại từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },

  // HH-06
  {
    id: 'HH-06-EX4',
    topicIds: ['HH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình tròn có bán kính $7\\,cm$. Tính chu vi ($cm$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: '$2\\times7\\times3{,}14=43{,}96$.', rationale: 'Áp dụng công thức chu vi hình tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['43.96'], tolerance: 0 },
  },
  {
    id: 'HH-06-EX5',
    topicIds: ['HH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình tròn có bán kính $7\\,cm$. Tính diện tích ($cm^2$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: '$7\\times7\\times3{,}14=153{,}86$.', rationale: 'Áp dụng công thức diện tích hình tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['153.86'], tolerance: 0 },
  },
  {
    id: 'HH-06-EX6',
    topicIds: ['HH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình tròn có đường kính $14\\,cm$. Tính chu vi ($cm$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: '$14\\times3{,}14=43{,}96$.', rationale: 'Áp dụng công thức chu vi theo đường kính.' }],
    numeric: { kind: 'single', acceptedValues: ['43.96'], tolerance: 0 },
  },
  {
    id: 'HH-06-EX7',
    topicIds: ['HH-06'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình tròn có chu vi $31{,}4\\,cm$. Tính bán kính ($cm$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: 'Bán kính $=31{,}4:(2\\times3{,}14)=31{,}4:6{,}28=5$.', rationale: 'Suy ra bán kính từ công thức chu vi.' }],
    numeric: { kind: 'single', acceptedValues: ['5'], tolerance: 0, isInteger: true },
  },

  // HH-07
  {
    id: 'HH-07-EX4',
    topicIds: ['HH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình hộp chữ nhật có chiều dài $15\\,cm$, chiều rộng $8\\,cm$, chiều cao $6\\,cm$. Tính thể tích ($cm^3$).',
    solutionSteps: [{ order: 1, content: '$15\\times8\\times6=720$.', rationale: 'Áp dụng công thức thể tích hình hộp chữ nhật.' }],
    numeric: { kind: 'single', acceptedValues: ['720'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-07-EX5',
    topicIds: ['HH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình lập phương cạnh $6\\,cm$. Tính thể tích ($cm^3$).',
    solutionSteps: [{ order: 1, content: '$6\\times6\\times6=216$.', rationale: 'Áp dụng công thức thể tích hình lập phương.' }],
    numeric: { kind: 'single', acceptedValues: ['216'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-07-EX6',
    topicIds: ['HH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình lập phương cạnh $5\\,cm$. Tính diện tích xung quanh ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$5\\times5\\times4=100$.', rationale: 'Diện tích xung quanh hình lập phương gồm 4 mặt bên.' }],
    numeric: { kind: 'single', acceptedValues: ['100'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-07-EX7',
    topicIds: ['HH-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình hộp chữ nhật có thể tích $480\\,cm^3$, đáy dài $10\\,cm$, rộng $6\\,cm$. Tính chiều cao ($cm$).',
    solutionSteps: [{ order: 1, content: '$480:(10\\times6)=480:60=8$.', rationale: 'Suy ra chiều cao từ công thức thể tích.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },

  // HH-08
  {
    id: 'HH-08-EX4',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình chữ nhật dài $18\\,cm$, rộng $10\\,cm$. Tăng chiều dài thêm $5\\,cm$, giữ nguyên chiều rộng. Diện tích tăng thêm bao nhiêu ($cm^2$)?',
    solutionSteps: [
      { order: 1, content: 'Diện tích cũ $=18\\times10=180\\,cm^2$.', rationale: 'Tính diện tích ban đầu.' },
      { order: 2, content: 'Chiều dài mới $=23\\,cm$; diện tích mới $=23\\times10=230\\,cm^2$.', rationale: 'Tính lại diện tích với kích thước mới.' },
      { order: 3, content: 'Diện tích tăng thêm $=230-180=50\\,cm^2$.', rationale: 'So sánh diện tích mới và cũ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['50'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-08-EX5',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình vuông cạnh $7\\,cm$. Tăng cạnh thêm $4\\,cm$. Diện tích tăng thêm bao nhiêu ($cm^2$)?',
    solutionSteps: [
      { order: 1, content: 'Diện tích cũ $=49\\,cm^2$; cạnh mới $=11\\,cm$; diện tích mới $=121\\,cm^2$.', rationale: 'Tính lại diện tích với cạnh mới.' },
      { order: 2, content: 'Diện tích tăng thêm $=121-49=72\\,cm^2$.', rationale: 'So sánh diện tích mới và cũ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-08-EX6',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình chữ nhật dài $25\\,cm$, rộng $12\\,cm$. Giảm chiều rộng đi $4\\,cm$. Diện tích giảm bao nhiêu ($cm^2$)?',
    solutionSteps: [
      { order: 1, content: 'Diện tích cũ $=300\\,cm^2$; chiều rộng mới $=8\\,cm$; diện tích mới $=200\\,cm^2$.', rationale: 'Tính lại diện tích với kích thước mới.' },
      { order: 2, content: 'Diện tích giảm $=300-200=100\\,cm^2$.', rationale: 'So sánh diện tích cũ và mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['100'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-08-EX7',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình vuông cạnh $10\\,cm$. Nếu tăng cạnh lên gấp đôi thì diện tích tăng gấp mấy lần?',
    solutionSteps: [
      { order: 1, content: 'Diện tích cũ $=100\\,cm^2$; cạnh mới $=20\\,cm$; diện tích mới $=400\\,cm^2$.', rationale: 'Tính diện tích cũ và mới.' },
      { order: 2, content: '$400:100=4$ lần.', rationale: 'So sánh diện tích mới với diện tích cũ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },

  // HH-10
  {
    id: 'HH-10-EX4',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình chữ nhật dài $14\\,cm$, rộng $9\\,cm$, bên trong cắt bỏ một hình vuông cạnh $5\\,cm$ (không tô đậm). Tính diện tích phần tô đậm còn lại ($cm^2$).',
    solutionSteps: [
      { order: 1, content: 'Diện tích hình chữ nhật $=14\\times9=126\\,cm^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích hình vuông $=5\\times5=25\\,cm^2$.', rationale: 'Tính diện tích phần bị cắt.' },
      { order: 3, content: 'Diện tích tô đậm $=126-25=101\\,cm^2$.', rationale: 'Lấy diện tích lớn trừ phần bị cắt.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['101'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-10-EX5',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình vuông cạnh $14\\,cm$ chứa một hình tròn bán kính $7\\,cm$ nội tiếp (không tô đậm). Tính diện tích phần tô đậm còn lại ($cm^2$), lấy $\\pi=3{,}14$.',
    solutionSteps: [
      { order: 1, content: 'Diện tích hình vuông $=14\\times14=196\\,cm^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích hình tròn $=7\\times7\\times3{,}14=153{,}86\\,cm^2$.', rationale: 'Tính diện tích phần bị cắt.' },
      { order: 3, content: 'Diện tích tô đậm $=196-153{,}86=42{,}14\\,cm^2$.', rationale: 'Lấy diện tích lớn trừ phần bị cắt.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['42.14'], tolerance: 0 },
  },
  {
    id: 'HH-10-EX6',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình chữ nhật dài $20\\,cm$, rộng $12\\,cm$, bên trong cắt bỏ một hình tam giác có đáy $8\\,cm$, chiều cao $6\\,cm$ (không tô đậm). Tính diện tích phần tô đậm còn lại ($cm^2$).',
    solutionSteps: [
      { order: 1, content: 'Diện tích hình chữ nhật $=20\\times12=240\\,cm^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích tam giác $=8\\times6:2=24\\,cm^2$.', rationale: 'Tính diện tích phần bị cắt.' },
      { order: 3, content: 'Diện tích tô đậm $=240-24=216\\,cm^2$.', rationale: 'Lấy diện tích lớn trừ phần bị cắt.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['216'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-10-EX7',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một khu đất hình chữ nhật dài $25\\,m$, rộng $18\\,m$, ở giữa có một ao cá hình vuông cạnh $6\\,m$ (không tính vào phần sử dụng). Tính diện tích đất còn lại ($m^2$).',
    solutionSteps: [
      { order: 1, content: 'Diện tích khu đất $=25\\times18=450\\,m^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích ao cá $=6\\times6=36\\,m^2$.', rationale: 'Tính diện tích phần không sử dụng.' },
      { order: 3, content: 'Diện tích còn lại $=450-36=414\\,m^2$.', rationale: 'Lấy diện tích khu đất trừ ao cá.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['414'], tolerance: 0, isInteger: true },
  },

  // HH-11
  {
    id: 'HH-11-EX4',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một bể cá đáy dài $45\\,cm$, rộng $25\\,cm$. Thả một hòn đá vào bể làm mực nước dâng lên $6\\,cm$. Tính thể tích hòn đá ($cm^3$).',
    solutionSteps: [{ order: 1, content: '$45\\times25\\times6=6750$.', rationale: 'Thể tích nước dâng lên bằng thể tích hòn đá.' }],
    numeric: { kind: 'single', acceptedValues: ['6750'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-11-EX5',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một bể nước đáy dài $70\\,cm$, rộng $40\\,cm$. Thả vào bể một khối đá có thể tích $5600\\,cm^3$ (chìm hoàn toàn). Hỏi mực nước dâng lên bao nhiêu cm?',
    solutionSteps: [{ order: 1, content: 'Diện tích đáy bể $=70\\times40=2800\\,cm^2$; mực nước dâng $=5600:2800=2\\,cm$.', rationale: 'Chia thể tích vật cho diện tích đáy bể.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-11-EX6',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một bể kính đáy dài $60\\,cm$, rộng $25\\,cm$. Thả vào bể 4 viên bi giống nhau, mỗi viên có thể tích $75\\,cm^3$ (chìm hoàn toàn). Hỏi mực nước dâng lên bao nhiêu cm?',
    solutionSteps: [
      { order: 1, content: 'Tổng thể tích 4 viên bi $=4\\times75=300\\,cm^3$.', rationale: 'Tính tổng thể tích các vật thả vào.' },
      { order: 2, content: 'Diện tích đáy bể $=60\\times25=1500\\,cm^2$; mực nước dâng $=300:1500=0{,}2\\,cm$.', rationale: 'Chia thể tích cho diện tích đáy bể.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['0.2'], tolerance: 0 },
  },
  {
    id: 'HH-11-EX7',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement:
      'Một bể nước hình hộp chữ nhật đáy dài $50\\,cm$, rộng $30\\,cm$, đang chứa nước cao $40\\,cm$. Thả vào bể một khối lập phương cạnh $15\\,cm$ (chìm hoàn toàn, nước không tràn). Tính chiều cao mực nước sau khi thả ($cm$).',
    solutionSteps: [
      { order: 1, content: 'Thể tích khối lập phương $=15\\times15\\times15=3375\\,cm^3$.', rationale: 'Tính thể tích vật thả vào.' },
      { order: 2, content: 'Diện tích đáy bể $=50\\times30=1500\\,cm^2$; mực nước dâng $=3375:1500=2{,}25\\,cm$.', rationale: 'Chia thể tích cho diện tích đáy bể.' },
      { order: 3, content: 'Chiều cao mực nước sau khi thả $=40+2{,}25=42{,}25\\,cm$.', rationale: 'Cộng mực nước dâng vào mực nước ban đầu.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['42.25'], tolerance: 0 },
  },
];
