import type { Exercise } from '../../types';
import { sharedBaseTriangleFigure, sharedHeightTriangleFigure } from '../figures/triangle-comparison';
import { shadedRegionFigure } from '../figures/shaded-region';

export const hhMoreExercises: Exercise[] = [
  {
    id: 'HH-01-EX1',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Góc có số đo $45°$ là loại góc gì?',
    solutionSteps: [{ order: 1, content: '$45° < 90°$ nên là góc nhọn.', rationale: 'So sánh với góc vuông 90°.' }],
    mcq: { options: ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], answerIndex: 0 },
  },
  {
    id: 'HH-01-EX2',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Trong các góc sau, góc nào là góc tù: $60°$, $90°$, $135°$, $30°$?',
    solutionSteps: [{ order: 1, content: '$135°$ lớn hơn $90°$ và nhỏ hơn $180°$ nên là góc tù; các góc còn lại là góc nhọn hoặc góc vuông.', rationale: 'Áp dụng định nghĩa góc tù.' }],
    mcq: { options: ['60°', '90°', '135°', '30°'], answerIndex: 2 },
  },
  {
    id: 'HH-01-EX3',
    topicIds: ['HH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Góc vuông có số đo bao nhiêu độ?',
    solutionSteps: [{ order: 1, content: 'Góc vuông luôn có số đo đúng bằng 90°.', rationale: 'Định nghĩa góc vuông.' }],
    numeric: { kind: 'single', acceptedValues: ['90'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX1',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tam giác có đáy $12\\,cm$, chiều cao $7\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$12\\times7:2=42$.', rationale: 'Áp dụng công thức diện tích tam giác.' }],
    numeric: { kind: 'single', acceptedValues: ['42'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX2',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tam giác có diện tích $36\\,cm^2$, đáy $9\\,cm$. Tính chiều cao ($cm$).',
    solutionSteps: [{ order: 1, content: '$36\\times2:9=8$.', rationale: 'Suy ra chiều cao từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX3',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tam giác có diện tích $45\\,cm^2$, chiều cao $10\\,cm$. Tính đáy ($cm$).',
    solutionSteps: [{ order: 1, content: '$45\\times2:10=9$.', rationale: 'Suy ra đáy từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX4',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một mảnh đất hình tam giác có đáy $20\\,m$, chiều cao $15\\,m$. Tính diện tích ($m^2$).',
    solutionSteps: [{ order: 1, content: '$20\\times15:2=150$.', rationale: 'Áp dụng công thức diện tích tam giác.' }],
    numeric: { kind: 'single', acceptedValues: ['150'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX1',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thang có đáy lớn $18\\,cm$, đáy bé $12\\,cm$, chiều cao $8\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$(18+12)\\times8:2=120$.', rationale: 'Áp dụng công thức diện tích hình thang.' }],
    numeric: { kind: 'single', acceptedValues: ['120'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX2',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thang có diện tích $84\\,cm^2$, hai đáy $10\\,cm$ và $11\\,cm$. Tính chiều cao ($cm$).',
    solutionSteps: [{ order: 1, content: '$84\\times2:(10+11)=168:21=8$.', rationale: 'Suy ra chiều cao từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX3',
    topicIds: ['HH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình thang có diện tích $100\\,cm^2$, đáy lớn $14\\,cm$, chiều cao $8\\,cm$. Tính đáy bé ($cm$).',
    solutionSteps: [
      { order: 1, content: 'Tổng hai đáy $=100\\times2:8=25$.', rationale: 'Suy ra tổng hai đáy từ công thức diện tích.' },
      { order: 2, content: 'Đáy bé $=25-14=11$.', rationale: 'Lấy tổng hai đáy trừ đáy lớn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['11'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX4',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một thửa ruộng hình thang có đáy lớn $30\\,m$, đáy bé $20\\,m$, chiều cao $12\\,m$. Tính diện tích ($m^2$).',
    solutionSteps: [{ order: 1, content: '$(30+20)\\times12:2=300$.', rationale: 'Áp dụng công thức diện tích hình thang.' }],
    numeric: { kind: 'single', acceptedValues: ['300'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-05-EX1',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình bình hành có đáy $15\\,cm$, chiều cao $8\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$15\\times8=120$.', rationale: 'Áp dụng công thức diện tích hình bình hành.' }],
    numeric: { kind: 'single', acceptedValues: ['120'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-05-EX2',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thoi có hai đường chéo $14\\,cm$ và $9\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$14\\times9:2=63$.', rationale: 'Áp dụng công thức diện tích hình thoi.' }],
    numeric: { kind: 'single', acceptedValues: ['63'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-05-EX3',
    topicIds: ['HH-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình bình hành có diện tích $72\\,cm^2$, chiều cao $6\\,cm$. Tính đáy ($cm$).',
    solutionSteps: [{ order: 1, content: '$72:6=12$.', rationale: 'Suy ra đáy từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-06-EX1',
    topicIds: ['HH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình tròn có bán kính $6\\,cm$. Tính chu vi ($cm$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: '$2\\times6\\times3{,}14=37{,}68$.', rationale: 'Áp dụng công thức chu vi hình tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['37.68'], tolerance: 0 },
  },
  {
    id: 'HH-06-EX2',
    topicIds: ['HH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình tròn có bán kính $6\\,cm$. Tính diện tích ($cm^2$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: '$6\\times6\\times3{,}14=113{,}04$.', rationale: 'Áp dụng công thức diện tích hình tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['113.04'], tolerance: 0 },
  },
  {
    id: 'HH-06-EX3',
    topicIds: ['HH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình tròn có đường kính $20\\,cm$. Tính chu vi ($cm$), lấy $\\pi=3{,}14$.',
    solutionSteps: [{ order: 1, content: '$20\\times3{,}14=62{,}8$.', rationale: 'Áp dụng công thức chu vi theo đường kính.' }],
    numeric: { kind: 'single', acceptedValues: ['62.8'], tolerance: 0 },
  },
  {
    id: 'HH-07-EX1',
    topicIds: ['HH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình hộp chữ nhật có chiều dài $12\\,cm$, chiều rộng $6\\,cm$, chiều cao $5\\,cm$. Tính thể tích ($cm^3$).',
    solutionSteps: [{ order: 1, content: '$12\\times6\\times5=360$.', rationale: 'Áp dụng công thức thể tích hình hộp chữ nhật.' }],
    numeric: { kind: 'single', acceptedValues: ['360'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-07-EX2',
    topicIds: ['HH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình lập phương cạnh $7\\,cm$. Tính diện tích toàn phần ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$7\\times7\\times6=294$.', rationale: 'Hình lập phương có 6 mặt bằng nhau.' }],
    numeric: { kind: 'single', acceptedValues: ['294'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-07-EX3',
    topicIds: ['HH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình hộp chữ nhật có chiều dài $9\\,cm$, chiều rộng $5\\,cm$, chiều cao $4\\,cm$. Tính diện tích xung quanh ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$(9+5)\\times2\\times4=112$.', rationale: 'Diện tích xung quanh bằng chu vi đáy nhân chiều cao.' }],
    numeric: { kind: 'single', acceptedValues: ['112'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-08-EX1',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình chữ nhật dài $15\\,cm$, rộng $9\\,cm$. Tăng chiều rộng thêm $3\\,cm$, giữ nguyên chiều dài. Diện tích tăng thêm bao nhiêu ($cm^2$)?',
    solutionSteps: [
      { order: 1, content: 'Diện tích cũ $=15\\times9=135\\,cm^2$.', rationale: 'Tính diện tích ban đầu.' },
      { order: 2, content: 'Chiều rộng mới $=12\\,cm$; diện tích mới $=15\\times12=180\\,cm^2$.', rationale: 'Tính lại diện tích với kích thước mới.' },
      { order: 3, content: 'Diện tích tăng thêm $=180-135=45\\,cm^2$.', rationale: 'So sánh diện tích mới và cũ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['45'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-08-EX2',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình vuông cạnh $8\\,cm$. Giảm cạnh đi $3\\,cm$. Diện tích giảm đi bao nhiêu ($cm^2$)?',
    solutionSteps: [
      { order: 1, content: 'Diện tích cũ $=8\\times8=64\\,cm^2$.', rationale: 'Tính diện tích ban đầu.' },
      { order: 2, content: 'Cạnh mới $=5\\,cm$; diện tích mới $=5\\times5=25\\,cm^2$.', rationale: 'Tính lại diện tích với cạnh mới.' },
      { order: 3, content: 'Diện tích giảm đi $=64-25=39\\,cm^2$.', rationale: 'So sánh diện tích cũ và mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['39'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-08-EX3',
    topicIds: ['HH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình chữ nhật dài $20\\,cm$, rộng $10\\,cm$. Nếu giảm chiều dài đi $5\\,cm$ thì chu vi mới là bao nhiêu ($cm$)?',
    solutionSteps: [
      { order: 1, content: 'Chiều dài mới $=20-5=15\\,cm$.', rationale: 'Tính kích thước mới.' },
      { order: 2, content: 'Chu vi mới $=(15+10)\\times2=50\\,cm$.', rationale: 'Áp dụng công thức chu vi hình chữ nhật.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['50'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX1',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedBaseTriangleFigure(10, 15, 'Tam giác nhỏ', 'Tam giác lớn'),
    statement: 'Hai tam giác chung đáy có chiều cao lần lượt $10\\,cm$ và $15\\,cm$. Tính tỉ số diện tích tam giác nhỏ so với tam giác lớn (dạng phân số tối giản).',
    solutionSteps: [{ order: 1, content: 'Chung đáy nên tỉ số diện tích bằng tỉ số chiều cao: $10:15=2:3$.', rationale: 'Áp dụng tính chất tam giác chung đáy.' }],
    numeric: { kind: 'single', acceptedValues: ['2/3'], tolerance: 0 },
  },
  {
    id: 'HH-09-EX2',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedHeightTriangleFigure('A', 'N', 'BN', 'NC'),
    statement: 'Tam giác ABC diện tích $72\\,cm^2$. N trên BC sao cho $BN=\\dfrac{2}{3}BC$ (chung chiều cao từ A). Tính diện tích tam giác ABN ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'Chung chiều cao nên tỉ số diện tích bằng tỉ số đáy: $S_{ABN}=72\\times\\dfrac{2}{3}=48$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao.' }],
    numeric: { kind: 'single', acceptedValues: ['48'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX3',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedHeightTriangleFigure('M', 'Q', 'NQ', 'QP'),
    statement: 'Tam giác MNP có diện tích $40\\,cm^2$. Q là trung điểm của NP (chung chiều cao từ M). Tính diện tích tam giác MNQ ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'Q là trung điểm nên $NQ=\\dfrac{1}{2}NP$; $S_{MNQ}=40\\times\\dfrac{1}{2}=20$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX4',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedBaseTriangleFigure(6, 9, 'Tam giác ABD', 'Tam giác ACD'),
    statement: 'Hai tam giác ABD và ACD có chung đáy AD. Diện tích ABD là $18\\,cm^2$ ứng với chiều cao $6\\,cm$; ACD ứng với chiều cao $9\\,cm$. Tính diện tích ACD ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'Chung đáy nên $S_{ACD}:S_{ABD}=9:6$; $S_{ACD}=18\\times\\dfrac{9}{6}=27$.', rationale: 'Áp dụng tính chất tam giác chung đáy.' }],
    numeric: { kind: 'single', acceptedValues: ['27'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-10-EX1',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    figure: shadedRegionFigure(15, 10, { kind: 'triangle', base: 6, height: 5, label: 'đáy 6, cao 5' }),
    statement: 'Hình chữ nhật dài $15\\,cm$, rộng $10\\,cm$, bên trong cắt bỏ một hình tam giác có đáy $6\\,cm$, chiều cao $5\\,cm$ (không tô đậm). Tính diện tích phần tô đậm còn lại ($cm^2$).',
    solutionSteps: [
      { order: 1, content: 'Diện tích hình chữ nhật $=15\\times10=150\\,cm^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích tam giác $=6\\times5:2=15\\,cm^2$.', rationale: 'Tính diện tích phần bị cắt.' },
      { order: 3, content: 'Diện tích tô đậm $=150-15=135\\,cm^2$.', rationale: 'Lấy diện tích lớn trừ phần bị cắt.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['135'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-10-EX2',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    figure: shadedRegionFigure(12, 12, { kind: 'circle', radius: 6, label: 'r=6' }),
    statement: 'Hình vuông cạnh $12\\,cm$ chứa một hình tròn bán kính $6\\,cm$ nội tiếp (không tô đậm). Tính diện tích phần tô đậm còn lại ($cm^2$), lấy $\\pi=3{,}14$.',
    solutionSteps: [
      { order: 1, content: 'Diện tích hình vuông $=12\\times12=144\\,cm^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích hình tròn $=6\\times6\\times3{,}14=113{,}04\\,cm^2$.', rationale: 'Tính diện tích phần bị cắt.' },
      { order: 3, content: 'Diện tích tô đậm $=144-113{,}04=30{,}96\\,cm^2$.', rationale: 'Lấy diện tích lớn trừ phần bị cắt.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['30.96'], tolerance: 0 },
  },
  {
    id: 'HH-10-EX3',
    topicIds: ['HH-10'],
    level: 'advanced',
    answerType: 'numeric',
    figure: shadedRegionFigure(20, 15, { kind: 'strip', width: 2, label: 'lối đi rộng 2m' }, 'm'),
    statement: 'Một mảnh vườn hình chữ nhật dài $20\\,m$, rộng $15\\,m$, ở giữa có một lối đi hình chữ nhật rộng $2\\,m$ chạy suốt chiều dài (không trồng cây). Tính diện tích phần còn lại để trồng cây ($m^2$).',
    solutionSteps: [
      { order: 1, content: 'Diện tích cả vườn $=20\\times15=300\\,m^2$.', rationale: 'Tính diện tích hình lớn.' },
      { order: 2, content: 'Diện tích lối đi $=20\\times2=40\\,m^2$.', rationale: 'Lối đi chạy suốt chiều dài 20m, rộng 2m.' },
      { order: 3, content: 'Diện tích trồng cây $=300-40=260\\,m^2$.', rationale: 'Lấy diện tích vườn trừ diện tích lối đi.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['260'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-11-EX1',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một bể cá đáy dài $35\\,cm$, rộng $20\\,cm$. Thả một hòn đá vào bể làm mực nước dâng lên $4\\,cm$. Tính thể tích hòn đá ($cm^3$).',
    solutionSteps: [{ order: 1, content: '$35\\times20\\times4=2800$.', rationale: 'Thể tích nước dâng lên bằng thể tích hòn đá.' }],
    numeric: { kind: 'single', acceptedValues: ['2800'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-11-EX2',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một bể nước đáy dài $60\\,cm$, rộng $30\\,cm$. Người ta thả vào bể một khối đá có thể tích $3600\\,cm^3$ (chìm hoàn toàn). Hỏi mực nước dâng lên bao nhiêu cm?',
    solutionSteps: [{ order: 1, content: 'Diện tích đáy bể $=60\\times30=1800\\,cm^2$; mực nước dâng $=3600:1800=2\\,cm$.', rationale: 'Chia thể tích vật cho diện tích đáy bể.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-11-EX3',
    topicIds: ['HH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một bể kính đáy dài $50\\,cm$, rộng $20\\,cm$, đang chứa nước. Thả vào bể 5 viên bi giống nhau, mỗi viên có thể tích $40\\,cm^3$ (chìm hoàn toàn). Hỏi mực nước dâng lên bao nhiêu cm?',
    solutionSteps: [
      { order: 1, content: 'Tổng thể tích 5 viên bi $=5\\times40=200\\,cm^3$.', rationale: 'Tính tổng thể tích các vật thả vào.' },
      { order: 2, content: 'Diện tích đáy bể $=50\\times20=1000\\,cm^2$; mực nước dâng $=200:1000=0{,}2\\,cm$.', rationale: 'Chia thể tích cho diện tích đáy bể.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['0.2'], tolerance: 0 },
  },
];
