import type { Exercise } from '../../types';
import { sharedBaseTriangleFigure, sharedHeightTriangleFigure } from '../figures/triangle-comparison';

/** Bổ sung bài tập cho HH-03, HH-04, HH-09 (ưu tiên theo Mục 4.7 URD), hướng tới 12–15 bài/chuyên đề. */
export const hhPriorityMoreExercises: Exercise[] = [
  // HH-03: Diện tích tam giác
  {
    id: 'HH-03-EX5',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tam giác có đáy $14\\,cm$, chiều cao $9\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$14\\times9:2=63$.', rationale: 'Áp dụng công thức diện tích tam giác.' }],
    numeric: { kind: 'single', acceptedValues: ['63'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX6',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tam giác có diện tích $54\\,cm^2$, đáy $12\\,cm$. Tính chiều cao ($cm$).',
    solutionSteps: [{ order: 1, content: '$54\\times2:12=9$.', rationale: 'Suy ra chiều cao từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX7',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tam giác có diện tích $40\\,cm^2$, chiều cao $8\\,cm$. Tính đáy ($cm$).',
    solutionSteps: [{ order: 1, content: '$40\\times2:8=10$.', rationale: 'Suy ra đáy từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX8',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một mảnh đất hình tam giác có đáy $25\\,m$, chiều cao $16\\,m$. Tính diện tích ($m^2$).',
    solutionSteps: [{ order: 1, content: '$25\\times16:2=200$.', rationale: 'Áp dụng công thức diện tích tam giác.' }],
    numeric: { kind: 'single', acceptedValues: ['200'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX9',
    topicIds: ['HH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tam giác có đáy $18\\,cm$, chiều cao bằng nửa đáy. Tính diện tích ($cm^2$).',
    solutionSteps: [
      { order: 1, content: 'Chiều cao $=18:2=9\\,cm$.', rationale: 'Chiều cao bằng nửa đáy.' },
      { order: 2, content: 'Diện tích $=18\\times9:2=81\\,cm^2$.', rationale: 'Áp dụng công thức diện tích tam giác.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['81'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX10',
    topicIds: ['HH-03'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Tam giác có đáy $16\\,cm$, chiều cao $5\\,cm$. Diện tích là bao nhiêu?',
    solutionSteps: [{ order: 1, content: '$16\\times5:2=40\\,cm^2$.', rationale: 'Áp dụng công thức diện tích tam giác.' }],
    mcq: { options: ['35 cm²', '40 cm²', '45 cm²', '50 cm²'], answerIndex: 1 },
  },
  {
    id: 'HH-03-EX11',
    topicIds: ['HH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement:
      'Hai tam giác có diện tích bằng nhau. Tam giác thứ nhất có đáy $10\\,cm$, chiều cao $12\\,cm$. Tam giác thứ hai có đáy $15\\,cm$. Tính chiều cao tam giác thứ hai ($cm$).',
    solutionSteps: [
      { order: 1, content: 'Diện tích tam giác thứ nhất $=10\\times12:2=60\\,cm^2$.', rationale: 'Tính diện tích tam giác đã biết đủ dữ kiện.' },
      { order: 2, content: 'Chiều cao tam giác thứ hai $=60\\times2:15=8\\,cm$.', rationale: 'Hai diện tích bằng nhau, suy ra chiều cao còn lại.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-03-EX12',
    topicIds: ['HH-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tam giác vuông có hai cạnh góc vuông lần lượt là $6\\,cm$ và $8\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'Hai cạnh góc vuông đóng vai trò đáy và chiều cao: $6\\times8:2=24\\,cm^2$.', rationale: 'Ở tam giác vuông, hai cạnh góc vuông vuông góc với nhau nên đóng vai trò đáy-chiều cao.' }],
    numeric: { kind: 'single', acceptedValues: ['24'], tolerance: 0, isInteger: true },
  },

  // HH-04: Diện tích hình thang
  {
    id: 'HH-04-EX5',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thang có đáy lớn $20\\,cm$, đáy bé $14\\,cm$, chiều cao $8\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [{ order: 1, content: '$(20+14)\\times8:2=136$.', rationale: 'Áp dụng công thức diện tích hình thang.' }],
    numeric: { kind: 'single', acceptedValues: ['136'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX6',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Hình thang có diện tích $96\\,cm^2$, hai đáy $10\\,cm$ và $14\\,cm$. Tính chiều cao ($cm$).',
    solutionSteps: [{ order: 1, content: '$96\\times2:(10+14)=8$.', rationale: 'Suy ra chiều cao từ công thức diện tích.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX7',
    topicIds: ['HH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình thang có diện tích $108\\,cm^2$, đáy lớn $16\\,cm$, chiều cao $9\\,cm$. Tính đáy bé ($cm$).',
    solutionSteps: [
      { order: 1, content: 'Tổng hai đáy $=108\\times2:9=24$.', rationale: 'Suy ra tổng hai đáy từ công thức diện tích.' },
      { order: 2, content: 'Đáy bé $=24-16=8$.', rationale: 'Lấy tổng hai đáy trừ đáy lớn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX8',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một thửa ruộng hình thang có đáy lớn $40\\,m$, đáy bé $25\\,m$, chiều cao $18\\,m$. Tính diện tích ($m^2$).',
    solutionSteps: [{ order: 1, content: '$(40+25)\\times18:2=585$.', rationale: 'Áp dụng công thức diện tích hình thang.' }],
    numeric: { kind: 'single', acceptedValues: ['585'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX9',
    topicIds: ['HH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình thang có đáy lớn gấp đôi đáy bé. Đáy bé $9\\,cm$, chiều cao $10\\,cm$. Tính diện tích ($cm^2$).',
    solutionSteps: [
      { order: 1, content: 'Đáy lớn $=9\\times2=18\\,cm$.', rationale: 'Đáy lớn gấp đôi đáy bé.' },
      { order: 2, content: 'Diện tích $=(18+9)\\times10:2=135\\,cm^2$.', rationale: 'Áp dụng công thức diện tích hình thang.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['135'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX10',
    topicIds: ['HH-04'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Hình thang có hai đáy $8\\,cm$ và $12\\,cm$, chiều cao $6\\,cm$. Diện tích là bao nhiêu?',
    solutionSteps: [{ order: 1, content: '$(8+12)\\times6:2=60\\,cm^2$.', rationale: 'Áp dụng công thức diện tích hình thang.' }],
    mcq: { options: ['50 cm²', '55 cm²', '60 cm²', '65 cm²'], answerIndex: 2 },
  },
  {
    id: 'HH-04-EX11',
    topicIds: ['HH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hình thang có diện tích $84\\,cm^2$, đáy bé $10\\,cm$, chiều cao $8\\,cm$. Tính đáy lớn ($cm$).',
    solutionSteps: [
      { order: 1, content: 'Tổng hai đáy $=84\\times2:8=21$.', rationale: 'Suy ra tổng hai đáy từ công thức diện tích.' },
      { order: 2, content: 'Đáy lớn $=21-10=11$.', rationale: 'Lấy tổng hai đáy trừ đáy bé.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['11'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-04-EX12',
    topicIds: ['HH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement:
      'Một mảnh vườn hình thang có đáy lớn $30\\,m$, đáy bé $20\\,m$, chiều cao $12\\,m$. Người ta trồng hoa trên toàn bộ mảnh vườn với mật độ 4 cây/$m^2$. Tính số cây hoa cần trồng.',
    solutionSteps: [
      { order: 1, content: 'Diện tích mảnh vườn $=(30+20)\\times12:2=300\\,m^2$.', rationale: 'Áp dụng công thức diện tích hình thang.' },
      { order: 2, content: 'Số cây hoa $=300\\times4=1200$ cây.', rationale: 'Nhân diện tích với mật độ trồng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['1200'], tolerance: 0, isInteger: true },
  },

  // HH-09: Tỉ số diện tích tam giác chung đáy hoặc chung chiều cao
  {
    id: 'HH-09-EX5',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedBaseTriangleFigure(12, 18, 'Tam giác nhỏ', 'Tam giác lớn'),
    statement: 'Hai tam giác chung đáy có chiều cao lần lượt $12\\,cm$ và $18\\,cm$. Tính tỉ số diện tích tam giác nhỏ so với tam giác lớn (dạng phân số tối giản).',
    solutionSteps: [{ order: 1, content: 'Chung đáy nên tỉ số diện tích bằng tỉ số chiều cao: $12:18=2:3$.', rationale: 'Áp dụng tính chất tam giác chung đáy.' }],
    numeric: { kind: 'single', acceptedValues: ['2/3'], tolerance: 0 },
  },
  {
    id: 'HH-09-EX6',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedHeightTriangleFigure('A', 'M', 'BM', 'MC'),
    statement: 'Tam giác ABC diện tích $90\\,cm^2$. M trên BC sao cho $BM=\\dfrac{2}{5}BC$ (chung chiều cao từ A). Tính diện tích tam giác ABM ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'Chung chiều cao nên tỉ số diện tích bằng tỉ số đáy: $S_{ABM}=90\\times\\dfrac{2}{5}=36$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao.' }],
    numeric: { kind: 'single', acceptedValues: ['36'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX7',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedHeightTriangleFigure('D', 'P', 'EP', 'PF'),
    statement: 'Tam giác DEF có diện tích $56\\,cm^2$. P là trung điểm EF (chung chiều cao từ D). Tính diện tích tam giác DEP ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'P là trung điểm nên $EP=\\dfrac{1}{2}EF$; $S_{DEP}=56\\times\\dfrac{1}{2}=28$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao.' }],
    numeric: { kind: 'single', acceptedValues: ['28'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX8',
    topicIds: ['HH-09'],
    level: 'basic',
    answerType: 'mcq',
    figure: sharedBaseTriangleFigure(8, 8, 'Tam giác XYZ', 'Tam giác XYT'),
    statement: 'Hai tam giác XYZ và XYT có chung đáy XY, chiều cao lần lượt bằng nhau (cùng $8\\,cm$). So sánh diện tích hai tam giác.',
    solutionSteps: [{ order: 1, content: 'Chung đáy và chiều cao bằng nhau nên diện tích bằng nhau.', rationale: 'Áp dụng tính chất tam giác chung đáy, chung chiều cao.' }],
    mcq: { options: ['Bằng nhau', 'XYZ lớn hơn', 'XYT lớn hơn', 'Không so sánh được'], answerIndex: 0 },
  },
  {
    id: 'HH-09-EX9',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedHeightTriangleFigure('A', 'N', 'BN', 'CN'),
    statement: 'Tam giác ABC diện tích $120\\,cm^2$. N trên BC sao cho $CN=\\dfrac{1}{4}BC$ (chung chiều cao từ A). Tính diện tích tam giác ACN ($cm^2$).',
    solutionSteps: [{ order: 1, content: 'Chung chiều cao từ A nên $S_{ACN}=120\\times\\dfrac{1}{4}=30$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao, với đáy CN.' }],
    numeric: { kind: 'single', acceptedValues: ['30'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX10',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'mcq',
    figure: sharedHeightTriangleFigure('Đỉnh chung', 'Điểm chia', 'đáy 6cm', 'đáy 9cm'),
    statement: 'Hai tam giác chung chiều cao có đáy lần lượt là $6\\,cm$ và $9\\,cm$. Tỉ số diện tích tam giác nhỏ so với lớn là bao nhiêu?',
    solutionSteps: [{ order: 1, content: 'Chung chiều cao nên tỉ số diện tích bằng tỉ số đáy: $6:9=2:3$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao.' }],
    mcq: { options: ['1/2', '2/3', '3/4', '5/6'], answerIndex: 1 },
  },
  {
    id: 'HH-09-EX11',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedHeightTriangleFigure('M', 'Q', 'NQ', 'QP'),
    statement: 'Tam giác MNP diện tích $84\\,cm^2$. Q trên NP sao cho $NQ:QP=3:4$ (chung chiều cao từ M). Tính diện tích tam giác MNQ ($cm^2$).',
    solutionSteps: [
      { order: 1, content: 'NQ chiếm $\\dfrac{3}{7}$ NP (tổng số phần $3+4=7$).', rationale: 'Chuyển tỉ số thành phân số của cả đoạn NP.' },
      { order: 2, content: '$S_{MNQ}=84\\times\\dfrac{3}{7}=36$.', rationale: 'Áp dụng tính chất tam giác chung chiều cao.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['36'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-09-EX12',
    topicIds: ['HH-09'],
    level: 'advanced',
    answerType: 'numeric',
    figure: sharedBaseTriangleFigure(9, 15, 'Tam giác nhỏ', 'Tam giác lớn'),
    statement: 'Hai tam giác chung đáy có tỉ số diện tích là $3:5$. Biết chiều cao tam giác nhỏ là $9\\,cm$. Tính chiều cao tam giác lớn ($cm$).',
    solutionSteps: [{ order: 1, content: 'Chung đáy nên tỉ số diện tích bằng tỉ số chiều cao: chiều cao lớn $=9\\times\\dfrac{5}{3}=15$.', rationale: 'Áp dụng tính chất tam giác chung đáy.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
];
