import type { Exercise } from '../../types';

/** Mở rộng bài tập cho các chuyên đề PS chưa ưu tiên, hướng tới 6–8 bài/chuyên đề. */
export const psExpandExercises: Exercise[] = [
  // PS-01
  {
    id: 'PS-01-EX7',
    topicIds: ['PS-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Rút gọn phân số $\\dfrac{18}{24}$ về dạng tối giản.',
    solutionSteps: [
      { order: 1, content: '$ƯCLN(18,24)=6$.', rationale: 'Tìm ước chung lớn nhất.' },
      { order: 2, content: '$18:6=3$, $24:6=4$, nên $\\dfrac{18}{24}=\\dfrac{3}{4}$.', rationale: 'Chia cả tử và mẫu cho ƯCLN.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['3/4'], tolerance: 0, requireSimplified: true },
  },
  {
    id: 'PS-01-EX8',
    topicIds: ['PS-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Quy đồng mẫu số hai phân số $\\dfrac{2}{5}$ và $\\dfrac{3}{4}$. Mẫu số chung nhỏ nhất là bao nhiêu?',
    solutionSteps: [{ order: 1, content: '$BCNN(5,4)=20$.', rationale: 'Tính bội chung nhỏ nhất của hai mẫu số.' }],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true },
  },

  // PS-02
  {
    id: 'PS-02-EX4',
    topicIds: ['PS-02'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'So sánh $\\dfrac{3}{8}$ và $\\dfrac{2}{5}$ bằng cách quy đồng mẫu số 40: $\\dfrac{3}{8}=\\dfrac{15}{40}$, $\\dfrac{2}{5}=\\dfrac{16}{40}$. Phân số nào lớn hơn?',
    solutionSteps: [{ order: 1, content: '$16>15$ nên $\\dfrac{2}{5}>\\dfrac{3}{8}$.', rationale: 'So sánh tử số khi mẫu số bằng nhau.' }],
    mcq: { options: ['3/8', '2/5', 'Bằng nhau', 'Không so sánh được'], answerIndex: 1 },
  },
  {
    id: 'PS-02-EX5',
    topicIds: ['PS-02'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'So sánh $\\dfrac{5}{6}$ và $\\dfrac{7}{8}$ bằng phần bù đến 1. Phân số nào lớn hơn?',
    solutionSteps: [{ order: 1, content: 'Phần bù của $\\dfrac{5}{6}$ là $\\dfrac{1}{6}$, phần bù của $\\dfrac{7}{8}$ là $\\dfrac{1}{8}$. Vì $\\dfrac{1}{8}<\\dfrac{1}{6}$ nên $\\dfrac{7}{8}>\\dfrac{5}{6}$.', rationale: 'Phần bù nhỏ hơn thì phân số gốc lớn hơn.' }],
    mcq: { options: ['5/6', '7/8', 'Bằng nhau', 'Không xác định'], answerIndex: 1 },
  },
  {
    id: 'PS-02-EX6',
    topicIds: ['PS-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'So sánh $\\dfrac{4}{9}$ và $\\dfrac{5}{9}$: nhập phân số lớn hơn.',
    solutionSteps: [{ order: 1, content: 'Cùng mẫu số, so sánh tử số: $5>4$ nên $\\dfrac{5}{9}$ lớn hơn.', rationale: 'So sánh phân số cùng mẫu.' }],
    numeric: { kind: 'single', acceptedValues: ['5/9'], tolerance: 0 },
  },
  {
    id: 'PS-02-EX7',
    topicIds: ['PS-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính phần bù đến 1 của phân số $\\dfrac{5}{8}$.',
    solutionSteps: [{ order: 1, content: '$1-\\dfrac{5}{8}=\\dfrac{3}{8}$.', rationale: 'Phần bù đến 1 bằng 1 trừ phân số đó.' }],
    numeric: { kind: 'single', acceptedValues: ['3/8'], tolerance: 0 },
  },

  // PS-03
  {
    id: 'PS-03-EX4',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{2}{7} + \\dfrac{3}{7}$',
    solutionSteps: [{ order: 1, content: '$\\dfrac{2+3}{7}=\\dfrac{5}{7}$.', rationale: 'Cộng tử số, giữ nguyên mẫu số vì cùng mẫu.' }],
    numeric: { kind: 'single', acceptedValues: ['5/7'], tolerance: 0 },
  },
  {
    id: 'PS-03-EX5',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{5}{6} - \\dfrac{1}{3}$',
    solutionSteps: [{ order: 1, content: 'Quy đồng mẫu 6: $\\dfrac{5}{6}-\\dfrac{2}{6}=\\dfrac{3}{6}=\\dfrac{1}{2}$.', rationale: 'Quy đồng rồi trừ tử số.' }],
    numeric: { kind: 'single', acceptedValues: ['1/2'], tolerance: 0 },
  },
  {
    id: 'PS-03-EX6',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{3}{5} \\times \\dfrac{2}{9}$',
    solutionSteps: [{ order: 1, content: '$\\dfrac{3\\times2}{5\\times9}=\\dfrac{6}{45}=\\dfrac{2}{15}$.', rationale: 'Nhân tử với tử, mẫu với mẫu rồi rút gọn.' }],
    numeric: { kind: 'single', acceptedValues: ['2/15'], tolerance: 0 },
  },
  {
    id: 'PS-03-EX7',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{5}{8} : \\dfrac{5}{4}$',
    solutionSteps: [{ order: 1, content: '$\\dfrac{5}{8} \\times \\dfrac{4}{5} = \\dfrac{20}{40}=\\dfrac{1}{2}$.', rationale: 'Chia bằng cách nhân với nghịch đảo rồi rút gọn.' }],
    numeric: { kind: 'single', acceptedValues: ['1/2'], tolerance: 0 },
  },

  // PS-04
  {
    id: 'PS-04-EX4',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'So sánh $6{,}08$ và $6{,}8$. Số nào lớn hơn?',
    solutionSteps: [{ order: 1, content: 'Viết $6{,}8=6{,}80$; so sánh $80$ và $08$: $80>08$ nên $6{,}8>6{,}08$.', rationale: 'So sánh phần thập phân sau khi cùng số chữ số.' }],
    mcq: { options: ['6,08', '6,8', 'Bằng nhau', 'Không so sánh được'], answerIndex: 1 },
  },
  {
    id: 'PS-04-EX5',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Làm tròn số $3{,}652$ đến hàng phần trăm.',
    solutionSteps: [{ order: 1, content: 'Chữ số hàng phần nghìn là 2 $<5$ nên giữ nguyên: $3{,}65$.', rationale: 'Áp dụng quy tắc làm tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['3.65'], tolerance: 0 },
  },
  {
    id: 'PS-04-EX6',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Làm tròn số $24{,}5$ đến hàng đơn vị.',
    solutionSteps: [{ order: 1, content: 'Chữ số hàng phần mười là 5 $\\ge5$ nên làm tròn lên: $25$.', rationale: 'Áp dụng quy tắc làm tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['25'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-04-EX7',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'So sánh $0{,}7$ và $0{,}70$. Kết luận nào đúng?',
    solutionSteps: [{ order: 1, content: 'Thêm số 0 vào cuối không làm thay đổi giá trị số thập phân: $0{,}7=0{,}70$.', rationale: 'Số 0 ở cuối phần thập phân không làm đổi giá trị.' }],
    mcq: { options: ['0,7 = 0,70', '0,7 > 0,70', '0,7 < 0,70', 'Không so sánh được'], answerIndex: 0 },
  },

  // PS-05
  {
    id: 'PS-05-EX4',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $15{,}8 + 4{,}25$',
    solutionSteps: [{ order: 1, content: '$15{,}80+4{,}25=20{,}05$.', rationale: 'Đặt tính thẳng cột dấu phẩy rồi cộng.' }],
    numeric: { kind: 'single', acceptedValues: ['20.05'], tolerance: 0 },
  },
  {
    id: 'PS-05-EX5',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $0{,}4 \\times 2{,}5$',
    solutionSteps: [{ order: 1, content: '$4\\times25=100$; tổng số chữ số thập phân là 2, đặt dấu phẩy: $1{,}00=1$.', rationale: 'Nhân như số tự nhiên rồi đặt đúng dấu phẩy.' }],
    numeric: { kind: 'single', acceptedValues: ['1'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-05-EX6',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $18{,}6 - 5{,}45$',
    solutionSteps: [{ order: 1, content: '$18{,}60-5{,}45=13{,}15$.', rationale: 'Đặt tính thẳng cột dấu phẩy rồi trừ.' }],
    numeric: { kind: 'single', acceptedValues: ['13.15'], tolerance: 0 },
  },
  {
    id: 'PS-05-EX7',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $7{,}2 : 3$',
    solutionSteps: [{ order: 1, content: '$7{,}2:3=2{,}4$.', rationale: 'Chia như số tự nhiên, giữ đúng dấu phẩy ở thương.' }],
    numeric: { kind: 'single', acceptedValues: ['2.4'], tolerance: 0 },
  },

  // PS-06
  {
    id: 'PS-06-EX4',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi phân số $\\dfrac{3}{8}$ sang số thập phân.',
    solutionSteps: [{ order: 1, content: '$3:8=0{,}375$.', rationale: 'Lấy tử số chia cho mẫu số.' }],
    numeric: { kind: 'single', acceptedValues: ['0.375'], tolerance: 0 },
  },
  {
    id: 'PS-06-EX5',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi số thập phân $0{,}72$ sang tỉ số phần trăm (nhập số).',
    solutionSteps: [{ order: 1, content: '$0{,}72\\times100=72$, vậy bằng $72\\%$.', rationale: 'Nhân số thập phân với 100.' }],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-06-EX6',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $\\dfrac{11}{20}$ sang tỉ số phần trăm (nhập số).',
    solutionSteps: [{ order: 1, content: '$11:20=0{,}55=55\\%$.', rationale: 'Đổi sang số thập phân rồi nhân 100.' }],
    numeric: { kind: 'single', acceptedValues: ['55'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-06-EX7',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $15\\%$ sang phân số tối giản.',
    solutionSteps: [{ order: 1, content: '$15\\%=\\dfrac{15}{100}=\\dfrac{3}{20}$.', rationale: 'Viết dưới dạng phân số có mẫu 100 rồi rút gọn.' }],
    numeric: { kind: 'single', acceptedValues: ['3/20'], tolerance: 0, requireSimplified: true },
  },

  // PS-07
  {
    id: 'PS-07-EX4',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{5}{6} \\times \\dfrac{6}{7} \\times \\dfrac{7}{8}$',
    solutionSteps: [{ order: 1, content: 'Rút gọn dây chuyền, chỉ còn tử đầu và mẫu cuối: $\\dfrac{5}{8}$.', rationale: 'Các thừa số ở giữa lần lượt triệt tiêu.' }],
    numeric: { kind: 'single', acceptedValues: ['5/8'], tolerance: 0 },
  },
  {
    id: 'PS-07-EX5',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{1}{3 \\times 4} + \\dfrac{1}{4 \\times 5}$',
    solutionSteps: [
      { order: 1, content: 'Tách: $\\left(\\dfrac{1}{3}-\\dfrac{1}{4}\\right)+\\left(\\dfrac{1}{4}-\\dfrac{1}{5}\\right)=\\dfrac{1}{3}-\\dfrac{1}{5}$.', rationale: 'Số hạng giữa triệt tiêu.' },
      { order: 2, content: 'Quy đồng mẫu 15: $\\dfrac{5}{15}-\\dfrac{3}{15}=\\dfrac{2}{15}$.', rationale: 'Thực hiện phép trừ phân số.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2/15'], tolerance: 0 },
  },
  {
    id: 'PS-07-EX6',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{4}{5} \\times \\dfrac{5}{6} \\times \\dfrac{6}{7} \\times \\dfrac{7}{8}$',
    solutionSteps: [{ order: 1, content: 'Rút gọn dây chuyền, chỉ còn tử đầu và mẫu cuối: $\\dfrac{4}{8}=\\dfrac{1}{2}$.', rationale: 'Các thừa số ở giữa lần lượt triệt tiêu.' }],
    numeric: { kind: 'single', acceptedValues: ['1/2'], tolerance: 0 },
  },
  {
    id: 'PS-07-EX7',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{1}{5 \\times 6} + \\dfrac{1}{6 \\times 7} + \\dfrac{1}{7 \\times 8}$',
    solutionSteps: [{ order: 1, content: 'Tách và triệt tiêu các số hạng ở giữa: $\\dfrac{1}{5}-\\dfrac{1}{8}=\\dfrac{8}{40}-\\dfrac{5}{40}=\\dfrac{3}{40}$.', rationale: 'Áp dụng công thức tách phân số liên tiếp.' }],
    numeric: { kind: 'single', acceptedValues: ['3/40'], tolerance: 0 },
  },

  // PS-08
  {
    id: 'PS-08-EX4',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một lớp có 14 bạn nam và 21 bạn nữ. Tính tỉ số giữa số nam và tổng số học sinh (dạng phân số tối giản).',
    solutionSteps: [
      { order: 1, content: 'Tổng số học sinh $=14+21=35$.', rationale: 'Cộng số nam và số nữ.' },
      { order: 2, content: 'Tỉ số $=14:35=\\dfrac{14}{35}=\\dfrac{2}{5}$.', rationale: 'Lập tỉ số rồi rút gọn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2/5'], tolerance: 0 },
  },
  {
    id: 'PS-08-EX5',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tỉ số giữa hai số là $3:8$. Biết số lớn là 40. Tìm số bé.',
    solutionSteps: [{ order: 1, content: 'Số bé $=40:8\\times3=15$.', rationale: 'Áp dụng đúng tỉ số đã cho.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-08-EX6',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một hình chữ nhật dài $18\\,cm$, rộng $12\\,cm$. Tính tỉ số chiều dài và chiều rộng (dạng phân số tối giản).',
    solutionSteps: [{ order: 1, content: 'Tỉ số $=18:12=\\dfrac{18}{12}=\\dfrac{3}{2}$.', rationale: 'Lập tỉ số rồi rút gọn.' }],
    numeric: { kind: 'single', acceptedValues: ['3/2'], tolerance: 0 },
  },
  {
    id: 'PS-08-EX7',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tỉ số giữa tuổi bố và tuổi con là $7:2$. Biết tuổi con là 8. Tính tuổi bố.',
    solutionSteps: [{ order: 1, content: 'Tuổi bố $=8:2\\times7=28$.', rationale: 'Áp dụng đúng tỉ số đã cho.' }],
    numeric: { kind: 'single', acceptedValues: ['28'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },

  // PS-10
  {
    id: 'PS-10-EX4',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một mặt hàng giá gốc 300 000đ, giảm giá 15%. Tính giá sau khi giảm.',
    solutionSteps: [{ order: 1, content: '$300\\,000\\times85:100=255\\,000$đ.', rationale: 'Áp dụng công thức giá sau giảm.' }],
    numeric: { kind: 'single', acceptedValues: ['255000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-10-EX5',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người mua hàng giá 800 000đ rồi bán lãi 12%. Tính số tiền lãi.',
    solutionSteps: [{ order: 1, content: '$800\\,000\\times12:100=96\\,000$đ.', rationale: 'Lãi tính trên giá gốc.' }],
    numeric: { kind: 'single', acceptedValues: ['96000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-10-EX6',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một chiếc xe đạp giá gốc 1 200 000đ được tăng giá 5%. Tính giá sau khi tăng.',
    solutionSteps: [{ order: 1, content: '$1\\,200\\,000\\times105:100=1\\,260\\,000$đ.', rationale: 'Áp dụng công thức giá sau tăng.' }],
    numeric: { kind: 'single', acceptedValues: ['1260000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-10-EX7',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người mua hàng giá 450 000đ rồi bán lại lỗ 10%. Tính giá bán.',
    solutionSteps: [
      { order: 1, content: 'Tiền lỗ $=450\\,000\\times10:100=45\\,000$đ.', rationale: 'Lỗ tính trên giá gốc.' },
      { order: 2, content: 'Giá bán $=450\\,000-45\\,000=405\\,000$đ.', rationale: 'Giá bán bằng giá gốc trừ tiền lỗ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['405000'], tolerance: 0, isInteger: true },
  },
];
