import type { Exercise } from '../../types';

export const psMoreExercises: Exercise[] = [
  {
    id: 'PS-02-EX1',
    topicIds: ['PS-02'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'So sánh $\\dfrac{5}{8}$ và $\\dfrac{3}{4}$ bằng cách quy đồng mẫu số 8: $\\dfrac{3}{4}=\\dfrac{6}{8}$. Phân số nào lớn hơn?',
    solutionSteps: [{ order: 1, content: '$\\dfrac{6}{8} > \\dfrac{5}{8}$ nên $\\dfrac{3}{4} > \\dfrac{5}{8}$.', rationale: 'So sánh tử số khi mẫu số đã bằng nhau.' }],
    mcq: { options: ['5/8', '3/4', 'Bằng nhau', 'Không so sánh được'], answerIndex: 1 },
  },
  {
    id: 'PS-02-EX2',
    topicIds: ['PS-02'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'So sánh $\\dfrac{8}{9}$ và $\\dfrac{9}{10}$ bằng phần bù đến 1. Phân số nào lớn hơn?',
    solutionSteps: [{ order: 1, content: 'Phần bù của $\\dfrac{8}{9}$ là $\\dfrac{1}{9}$, phần bù của $\\dfrac{9}{10}$ là $\\dfrac{1}{10}$. Vì $\\dfrac{1}{10} < \\dfrac{1}{9}$ nên $\\dfrac{9}{10} > \\dfrac{8}{9}$.', rationale: 'Phần bù nhỏ hơn thì phân số gốc lớn hơn.' }],
    mcq: { options: ['8/9', '9/10', 'Bằng nhau', 'Không xác định'], answerIndex: 1 },
  },
  {
    id: 'PS-02-EX3',
    topicIds: ['PS-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'So sánh $\\dfrac{7}{12}$ và $\\dfrac{5}{8}$: nhập phân số lớn hơn.',
    solutionSteps: [{ order: 1, content: 'Quy đồng mẫu 24: $\\dfrac{7}{12}=\\dfrac{14}{24}$, $\\dfrac{5}{8}=\\dfrac{15}{24}$. Vì $15>14$ nên $\\dfrac{5}{8}$ lớn hơn.', rationale: 'So sánh tử số sau khi quy đồng mẫu số.' }],
    numeric: { kind: 'single', acceptedValues: ['5/8'], tolerance: 0 },
  },
  {
    id: 'PS-03-EX1',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{5}{6} - \\dfrac{1}{4}$',
    solutionSteps: [{ order: 1, content: 'Quy đồng mẫu 12: $\\dfrac{10}{12}-\\dfrac{3}{12}=\\dfrac{7}{12}$.', rationale: 'Quy đồng rồi trừ tử số.' }],
    numeric: { kind: 'single', acceptedValues: ['7/12'], tolerance: 0 },
  },
  {
    id: 'PS-03-EX2',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{3}{7} \\times \\dfrac{2}{5}$',
    solutionSteps: [{ order: 1, content: '$\\dfrac{3 \\times 2}{7 \\times 5} = \\dfrac{6}{35}$.', rationale: 'Nhân tử với tử, mẫu với mẫu.' }],
    numeric: { kind: 'single', acceptedValues: ['6/35'], tolerance: 0 },
  },
  {
    id: 'PS-03-EX3',
    topicIds: ['PS-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{4}{9} : \\dfrac{2}{3}$',
    solutionSteps: [{ order: 1, content: '$\\dfrac{4}{9} \\times \\dfrac{3}{2} = \\dfrac{12}{18} = \\dfrac{2}{3}$.', rationale: 'Chia bằng cách nhân với nghịch đảo rồi rút gọn.' }],
    numeric: { kind: 'single', acceptedValues: ['2/3'], tolerance: 0 },
  },
  {
    id: 'PS-04-EX1',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Số nào bé hơn: $3{,}7$ hay $3{,}68$?',
    solutionSteps: [{ order: 1, content: 'Viết $3{,}7=3{,}70$; so sánh $70$ và $68$: $68<70$ nên $3{,}68<3{,}7$.', rationale: 'So sánh phần thập phân sau khi cùng số chữ số.' }],
    mcq: { options: ['3,7', '3,68', 'Bằng nhau', 'Không so sánh được'], answerIndex: 1 },
  },
  {
    id: 'PS-04-EX2',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Làm tròn số $5{,}428$ đến hàng phần trăm.',
    solutionSteps: [{ order: 1, content: 'Chữ số hàng phần nghìn là 8 $\\ge 5$ nên làm tròn lên: $5{,}42 \\rightarrow 5{,}43$.', rationale: 'Áp dụng quy tắc làm tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['5.43'], tolerance: 0 },
  },
  {
    id: 'PS-04-EX3',
    topicIds: ['PS-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Làm tròn số $18{,}5$ đến hàng đơn vị.',
    solutionSteps: [{ order: 1, content: 'Chữ số hàng phần mười là 5 $\\ge 5$ nên làm tròn lên: $18 \\rightarrow 19$.', rationale: 'Áp dụng quy tắc làm tròn.' }],
    numeric: { kind: 'single', acceptedValues: ['19'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-05-EX1',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $12{,}6 + 5{,}45$',
    solutionSteps: [{ order: 1, content: 'Đặt tính thẳng cột dấu phẩy: $12{,}60 + 5{,}45 = 18{,}05$.', rationale: 'Cộng như số tự nhiên rồi giữ dấu phẩy thẳng cột.' }],
    numeric: { kind: 'single', acceptedValues: ['18.05'], tolerance: 0 },
  },
  {
    id: 'PS-05-EX2',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $0{,}6 \\times 1{,}5$',
    solutionSteps: [{ order: 1, content: '$6 \\times 15 = 90$; tổng số chữ số thập phân là 2, đặt dấu phẩy: $0{,}90 = 0{,}9$.', rationale: 'Nhân như số tự nhiên rồi đặt dấu phẩy đúng vị trí.' }],
    numeric: { kind: 'single', acceptedValues: ['0.9'], tolerance: 0 },
  },
  {
    id: 'PS-05-EX3',
    topicIds: ['PS-05'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $9{,}6 : 4$',
    solutionSteps: [{ order: 1, content: '$9{,}6 : 4 = 2{,}4$.', rationale: 'Chia như số tự nhiên, giữ đúng vị trí dấu phẩy ở thương.' }],
    numeric: { kind: 'single', acceptedValues: ['2.4'], tolerance: 0 },
  },
  {
    id: 'PS-06-EX1',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi phân số $\\dfrac{7}{20}$ sang số thập phân.',
    solutionSteps: [{ order: 1, content: '$7 : 20 = 0{,}35$.', rationale: 'Lấy tử số chia cho mẫu số.' }],
    numeric: { kind: 'single', acceptedValues: ['0.35'], tolerance: 0 },
  },
  {
    id: 'PS-06-EX2',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi số thập phân $0{,}08$ sang tỉ số phần trăm (nhập số).',
    solutionSteps: [{ order: 1, content: '$0{,}08 \\times 100 = 8$, vậy bằng $8\\%$.', rationale: 'Nhân số thập phân với 100.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-06-EX3',
    topicIds: ['PS-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Đổi $\\dfrac{9}{25}$ sang tỉ số phần trăm (nhập số).',
    solutionSteps: [{ order: 1, content: '$9 : 25 = 0{,}36 = 36\\%$.', rationale: 'Đổi sang số thập phân rồi nhân 100.' }],
    numeric: { kind: 'single', acceptedValues: ['36'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-07-EX1',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{2}{3} \\times \\dfrac{3}{4} \\times \\dfrac{4}{5} \\times \\dfrac{5}{6}$',
    solutionSteps: [{ order: 1, content: 'Rút gọn dây chuyền, chỉ còn tử đầu và mẫu cuối: $\\dfrac{2}{6} = \\dfrac{1}{3}$.', rationale: 'Các thừa số ở giữa lần lượt triệt tiêu.' }],
    numeric: { kind: 'single', acceptedValues: ['1/3'], tolerance: 0 },
  },
  {
    id: 'PS-07-EX2',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{1}{1 \\times 2} + \\dfrac{1}{2 \\times 3} + \\dfrac{1}{3 \\times 4} + \\dfrac{1}{4 \\times 5}$',
    solutionSteps: [{ order: 1, content: 'Tách và triệt tiêu các số hạng ở giữa: $\\dfrac{1}{1} - \\dfrac{1}{5} = \\dfrac{4}{5}$.', rationale: 'Áp dụng công thức tách phân số liên tiếp.' }],
    numeric: { kind: 'single', acceptedValues: ['4/5'], tolerance: 0 },
  },
  {
    id: 'PS-07-EX3',
    topicIds: ['PS-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính: $\\dfrac{1}{4 \\times 5} + \\dfrac{1}{5 \\times 6}$',
    solutionSteps: [{ order: 1, content: 'Tách: $\\left(\\dfrac{1}{4}-\\dfrac{1}{5}\\right)+\\left(\\dfrac{1}{5}-\\dfrac{1}{6}\\right) = \\dfrac{1}{4}-\\dfrac{1}{6}$.', rationale: 'Số hạng giữa triệt tiêu.' },
      { order: 2, content: 'Quy đồng mẫu 12: $\\dfrac{3}{12}-\\dfrac{2}{12}=\\dfrac{1}{12}$.', rationale: 'Thực hiện phép trừ phân số.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['1/12'], tolerance: 0 },
  },
  {
    id: 'PS-08-EX1',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một hình chữ nhật có chiều dài 24cm, chiều rộng 16cm. Tính tỉ số giữa chiều rộng và chiều dài (dạng phân số tối giản).',
    solutionSteps: [{ order: 1, content: 'Tỉ số $= 16:24=\\dfrac{16}{24}=\\dfrac{2}{3}$.', rationale: 'Lập tỉ số rồi rút gọn.' }],
    numeric: { kind: 'single', acceptedValues: ['2/3'], tolerance: 0 },
  },
  {
    id: 'PS-08-EX2',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tỉ số giữa tuổi em và tuổi anh là $3:5$. Biết tuổi anh là 15. Tính tuổi em.',
    solutionSteps: [{ order: 1, content: 'Em $= 15 : 5 \\times 3 = 9$ (tuổi).', rationale: 'Áp dụng đúng tỉ số đã cho.' }],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true, unit: 'tuổi' },
  },
  {
    id: 'PS-08-EX3',
    topicIds: ['PS-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tỉ số giữa số bi đỏ và số bi xanh là $4:7$. Biết có 28 bi xanh. Tính số bi đỏ.',
    solutionSteps: [{ order: 1, content: 'Số bi đỏ $= 28 : 7 \\times 4 = 16$.', rationale: 'Áp dụng đúng tỉ số đã cho.' }],
    numeric: { kind: 'single', acceptedValues: ['16'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-09-EX1',
    topicIds: ['PS-09'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một trường có 800 học sinh, trong đó có 200 học sinh giỏi. Tính tỉ số % học sinh giỏi (nhập số).',
    solutionSteps: [{ order: 1, content: '$200 : 800 \\times 100 = 25$.', rationale: 'Áp dụng công thức tìm tỉ số phần trăm của hai số.' }],
    numeric: { kind: 'single', acceptedValues: ['25'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-09-EX2',
    topicIds: ['PS-09'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một cửa hàng có 350 sản phẩm, 12% bị lỗi. Tính số sản phẩm bị lỗi.',
    solutionSteps: [{ order: 1, content: '$350 \\times 12 : 100 = 42$.', rationale: 'Áp dụng công thức tìm giá trị phần trăm của một số.' }],
    numeric: { kind: 'single', acceptedValues: ['42'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-09-EX3',
    topicIds: ['PS-09'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Biết 35% của một số là 70. Tìm số đó.',
    solutionSteps: [{ order: 1, content: '$70 : 35 \\times 100 = 200$.', rationale: 'Áp dụng công thức tìm số biết giá trị phần trăm của nó.' }],
    numeric: { kind: 'single', acceptedValues: ['200'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-09-EX4',
    topicIds: ['PS-09'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một đội có 40 công nhân, trong đó 30 công nhân là nữ. Tính tỉ số % công nhân nữ (nhập số).',
    solutionSteps: [{ order: 1, content: '$30 : 40 \\times 100 = 75$.', rationale: 'Áp dụng công thức tìm tỉ số phần trăm của hai số.' }],
    numeric: { kind: 'single', acceptedValues: ['75'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-10-EX1',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một cửa hàng giảm giá 25% cho món hàng giá gốc 400 000đ. Tính giá sau khi giảm.',
    solutionSteps: [{ order: 1, content: '$400\\,000 \\times 75 : 100 = 300\\,000$ (đồng).', rationale: 'Áp dụng công thức giá sau giảm.' }],
    numeric: { kind: 'single', acceptedValues: ['300000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-10-EX2',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một người mua hàng giá 600 000đ rồi bán lại lỗ 15%. Tính giá bán.',
    solutionSteps: [
      { order: 1, content: 'Tiền lỗ $= 600\\,000 \\times 15 : 100 = 90\\,000$ (đồng).', rationale: 'Lỗ tính trên giá gốc.' },
      { order: 2, content: 'Giá bán $= 600\\,000 - 90\\,000 = 510\\,000$ (đồng).', rationale: 'Giá bán bằng giá gốc trừ tiền lỗ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['510000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'PS-10-EX3',
    topicIds: ['PS-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một mặt hàng giá gốc 150 000đ, tăng giá 12%. Tính giá mới.',
    solutionSteps: [{ order: 1, content: '$150\\,000 \\times 112 : 100 = 168\\,000$ (đồng).', rationale: 'Áp dụng công thức giá sau tăng.' }],
    numeric: { kind: 'single', acceptedValues: ['168000'], tolerance: 0, isInteger: true },
  },
];
