import type { Exercise } from '../../types';

/** Mở rộng bài tập cho các chuyên đề SH chưa ưu tiên, hướng tới 6–8 bài/chuyên đề. */
export const shExpandExercises: Exercise[] = [
  // SH-01
  {
    id: 'SH-01-EX4',
    topicIds: ['SH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'So sánh hai số 25431 và 25413. Số nào lớn hơn? (nhập số lớn hơn)',
    solutionSteps: [{ order: 1, content: 'Hàng nghìn, trăm bằng nhau. Hàng chục: $3>1$. Vậy $25431>25413$.', rationale: 'So sánh từng hàng từ trái sang phải.' }],
    numeric: { kind: 'single', acceptedValues: ['25431'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-01-EX5',
    topicIds: ['SH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Chữ số 4 trong số 84275 có giá trị là bao nhiêu?',
    solutionSteps: [{ order: 1, content: 'Chữ số 4 đứng ở hàng nghìn; giá trị $=4\\times1000=4000$.', rationale: 'Nhân chữ số với giá trị hàng.' }],
    numeric: { kind: 'single', acceptedValues: ['4000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-01-EX6',
    topicIds: ['SH-01'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Viết số tự nhiên bé nhất có 4 chữ số khác nhau được lập từ các chữ số 3, 0, 7, 5.',
    solutionSteps: [
      { order: 1, content: 'Chữ số hàng nghìn không được là 0; chọn chữ số nhỏ nhất khác 0 là 3.', rationale: 'Số tự nhiên không viết chữ số 0 ở đầu.' },
      { order: 2, content: 'Các chữ số còn lại xếp tăng dần: 0, 5, 7. Số cần tìm là 3057.', rationale: 'Xếp các chữ số còn lại theo thứ tự tăng dần để số nhỏ nhất.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['3057'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-01-EX7',
    topicIds: ['SH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Trong các số 12045, 12054, 12450, 12405, số nào lớn nhất?',
    solutionSteps: [{ order: 1, content: 'So sánh hàng trăm rồi hàng chục: $12450$ có hàng trăm và chục lớn nhất trong bốn số.', rationale: 'So sánh từng hàng.' }],
    mcq: { options: ['12045', '12054', '12450', '12405'], answerIndex: 2 },
  },

  // SH-02
  {
    id: 'SH-02-EX4',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $45 + 68 + 55$',
    solutionSteps: [{ order: 1, content: 'Nhóm $45+55=100$; $100+68=168$.', rationale: 'Cộng hai số tròn trăm trước.' }],
    numeric: { kind: 'single', acceptedValues: ['168'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-02-EX5',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $25 \\times 37 \\times 4$',
    solutionSteps: [{ order: 1, content: 'Nhóm $25\\times4=100$; $100\\times37=3700$.', rationale: 'Nhóm hai thừa số ra số tròn trăm.' }],
    numeric: { kind: 'single', acceptedValues: ['3700'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-02-EX6',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $128 + 345 + 72 + 55$',
    solutionSteps: [{ order: 1, content: 'Nhóm $128+72=200$ và $345+55=400$; tổng $=600$.', rationale: 'Nhóm các số hạng ra số tròn trăm.' }],
    numeric: { kind: 'single', acceptedValues: ['600'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-02-EX7',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $5 \\times 246 \\times 2$',
    solutionSteps: [{ order: 1, content: 'Nhóm $5\\times2=10$; $10\\times246=2460$.', rationale: 'Nhóm hai thừa số ra số tròn chục.' }],
    numeric: { kind: 'single', acceptedValues: ['2460'], tolerance: 0, isInteger: true },
  },

  // SH-03
  {
    id: 'SH-03-EX4',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $36:6+4\\times5$',
    solutionSteps: [{ order: 1, content: '$36:6=6$; $4\\times5=20$; $6+20=26$.', rationale: 'Nhân chia trước, cộng trừ sau.' }],
    numeric: { kind: 'single', acceptedValues: ['26'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-03-EX5',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $(36+4)\\times5:8$',
    solutionSteps: [{ order: 1, content: 'Trong ngoặc trước: $36+4=40$; $40\\times5=200$; $200:8=25$.', rationale: 'Ngoặc tính trước, sau đó nhân chia từ trái sang phải.' }],
    numeric: { kind: 'single', acceptedValues: ['25'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-03-EX6',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $100-45:9\\times3$',
    solutionSteps: [{ order: 1, content: '$45:9=5$; $5\\times3=15$; $100-15=85$.', rationale: 'Nhân chia trước, trừ sau.' }],
    numeric: { kind: 'single', acceptedValues: ['85'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-03-EX7',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $(18-8):2+7$',
    solutionSteps: [{ order: 1, content: 'Trong ngoặc trước: $18-8=10$; $10:2=5$; $5+7=12$.', rationale: 'Ngoặc tính trước, sau đó chia rồi cộng.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },

  // SH-06
  {
    id: 'SH-06-EX4',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một phép chia có số chia 8, thương 9, số dư 5. Tìm số bị chia.',
    solutionSteps: [{ order: 1, content: '$8\\times9+5=77$.', rationale: 'Áp dụng công thức số bị chia.' }],
    numeric: { kind: 'single', acceptedValues: ['77'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-06-EX5',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Số bị chia là 150, số chia là 12. Tìm số dư.',
    solutionSteps: [{ order: 1, content: '$150=12\\times12+6$, vậy số dư là 6.', rationale: 'Thực hiện phép chia có dư.' }],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-06-EX6',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Số dư lớn nhất có thể có khi chia cho 11 là bao nhiêu?',
    solutionSteps: [{ order: 1, content: 'Số dư luôn nhỏ hơn số chia; lớn nhất có thể là $11-1=10$.', rationale: 'Tính chất của phép chia có dư.' }],
    numeric: { kind: 'single', acceptedValues: ['10'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-06-EX7',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Phép chia nào sau đây có số dư hợp lệ (số dư nhỏ hơn số chia)?',
    solutionSteps: [{ order: 1, content: '$45=6\\times7+3$ nên $45:6$ dư 3 là hợp lệ; các số dư 6, 7, 8 đều không nhỏ hơn 6.', rationale: 'Kiểm tra điều kiện số dư nhỏ hơn số chia.' }],
    mcq: { options: ['45:6 dư 3', '45:6 dư 6', '45:6 dư 7', '45:6 dư 8'], answerIndex: 0 },
  },

  // SH-07
  {
    id: 'SH-07-EX4',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $x - 27 = 45$',
    solutionSteps: [{ order: 1, content: '$x=45+27=72$.', rationale: 'Muốn tìm số bị trừ, lấy hiệu cộng số trừ.' }],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-07-EX5',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $x \\times 8 = 96$',
    solutionSteps: [{ order: 1, content: '$x=96:8=12$.', rationale: 'Muốn tìm thừa số, lấy tích chia thừa số đã biết.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-07-EX6',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $150 - x = 68$',
    solutionSteps: [{ order: 1, content: '$x=150-68=82$.', rationale: 'Muốn tìm số trừ, lấy số bị trừ trừ hiệu.' }],
    numeric: { kind: 'single', acceptedValues: ['82'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-07-EX7',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $x : 6 = 15$',
    solutionSteps: [{ order: 1, content: '$x=15\\times6=90$.', rationale: 'Muốn tìm số bị chia, lấy thương nhân số chia.' }],
    numeric: { kind: 'single', acceptedValues: ['90'], tolerance: 0, isInteger: true },
  },

  // SH-08
  {
    id: 'SH-08-EX4',
    topicIds: ['SH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm trung bình cộng của 22, 28, 34, 40.',
    solutionSteps: [{ order: 1, content: 'Tổng $=22+28+34+40=124$; TBC $=124:4=31$.', rationale: 'Chia tổng cho số lượng số hạng.' }],
    numeric: { kind: 'single', acceptedValues: ['31'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-08-EX5',
    topicIds: ['SH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trung bình cộng của 3 số là 45. Biết hai trong ba số là 40 và 50. Tìm số còn lại.',
    solutionSteps: [
      { order: 1, content: 'Tổng 3 số $=45\\times3=135$.', rationale: 'Từ TBC suy ra tổng.' },
      { order: 2, content: 'Số còn lại $=135-40-50=45$.', rationale: 'Lấy tổng trừ hai số đã biết.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['45'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-08-EX6',
    topicIds: ['SH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Bốn thùng dầu có trung bình mỗi thùng 25 lít. Tính tổng số lít dầu của 4 thùng.',
    solutionSteps: [{ order: 1, content: '$25\\times4=100$ lít.', rationale: 'Tổng bằng trung bình cộng nhân số lượng.' }],
    numeric: { kind: 'single', acceptedValues: ['100'], tolerance: 0, isInteger: true, unit: 'lít' },
  },
  {
    id: 'SH-08-EX7',
    topicIds: ['SH-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trung bình cộng của hai số là 36. Hiệu hai số là 8. Tìm số lớn.',
    solutionSteps: [
      { order: 1, content: 'Tổng hai số $=36\\times2=72$.', rationale: 'Từ TBC suy ra tổng.' },
      { order: 2, content: 'Số lớn $=(72+8):2=40$.', rationale: 'Áp dụng công thức tổng-hiệu.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['40'], tolerance: 0, isInteger: true },
  },

  // SH-10
  {
    id: 'SH-10-EX4',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số 20 có tất cả bao nhiêu ước?',
    solutionSteps: [{ order: 1, content: '$Ư(20)=\\{1,2,4,5,10,20\\}$, có 6 ước.', rationale: 'Liệt kê tất cả các số chia hết 20.' }],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-10-EX5',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Số nào sau đây là số nguyên tố?',
    solutionSteps: [{ order: 1, content: '$21=3\\times7$, $25=5\\times5$, $27=3\\times9$ đều không phải số nguyên tố; 23 chỉ có ước 1 và 23.', rationale: 'Kiểm tra ước của từng số.' }],
    mcq: { options: ['21', '23', '25', '27'], answerIndex: 1 },
  },
  {
    id: 'SH-10-EX6',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm bội chung nhỏ nhất của 6 và 8.',
    solutionSteps: [{ order: 1, content: 'Bội của 6: 6,12,18,24...; bội của 8: 8,16,24... Bội chung nhỏ nhất là 24.', rationale: 'Liệt kê bội và tìm số nhỏ nhất chung.' }],
    numeric: { kind: 'single', acceptedValues: ['24'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-10-EX7',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm ước chung lớn nhất của 18 và 24.',
    solutionSteps: [{ order: 1, content: '$Ư(18)=\\{1,2,3,6,9,18\\}$, $Ư(24)=\\{1,2,3,4,6,8,12,24\\}$. ƯCLN là 6.', rationale: 'Liệt kê ước của mỗi số và tìm số lớn nhất chung.' }],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, isInteger: true },
  },
];
