import type { Exercise } from '../../types';

/** Bổ sung bài tập cho SH-04, SH-05, SH-09 (ưu tiên theo Mục 4.7 URD), hướng tới 12–15 bài/chuyên đề. */
export const shPriorityMoreExercises: Exercise[] = [
  // SH-04: Cấu tạo số
  {
    id: 'SH-04-EX5',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Viết thêm chữ số 0 vào bên phải số 34 thì được số mới là bao nhiêu?',
    solutionSteps: [{ order: 1, content: '$34\\times10=340$.', rationale: 'Viết thêm 0 vào bên phải nghĩa là nhân 10.' }],
    numeric: { kind: 'single', acceptedValues: ['340'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX6',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Nếu viết thêm chữ số 0 vào bên phải một số thì số đó tăng thêm 342 đơn vị. Tìm số đó.',
    solutionSteps: [
      { order: 1, content: 'Gọi số cũ là $a$: $10a-a=9a=342$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: '$a=342:9=38$.', rationale: 'Giải tìm số cũ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['38'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX7',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số có 2 chữ số. Nếu xóa chữ số hàng đơn vị thì được số mới kém số đã cho 39 đơn vị. Tìm số đã cho.',
    solutionSteps: [
      { order: 1, content: 'Gọi số đã cho $=10t+d$: $9t+d=39$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: 'Vì $0\\le d\\le9$ nên $t=4$ (vì $9\\times4=36$), $d=39-36=3$.', rationale: 'Xét điều kiện chữ số.' },
      { order: 3, content: 'Vậy số đã cho là 43.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['43'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX8',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số có 2 chữ số. Nếu xóa chữ số hàng đơn vị thì được số mới kém số đã cho 67 đơn vị. Tìm số đã cho.',
    solutionSteps: [
      { order: 1, content: 'Gọi số đã cho $=10t+d$: $9t+d=67$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: 'Vì $0\\le d\\le9$ nên $t=7$ (vì $9\\times7=63$), $d=67-63=4$.', rationale: 'Xét điều kiện chữ số.' },
      { order: 3, content: 'Vậy số đã cho là 74.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['74'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX9',
    topicIds: ['SH-04'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Viết thêm chữ số 0 vào bên phải số 125 thì được số mới là bao nhiêu?',
    solutionSteps: [{ order: 1, content: '$125\\times10=1250$.', rationale: 'Viết thêm 0 vào bên phải nghĩa là nhân 10.' }],
    numeric: { kind: 'single', acceptedValues: ['1250'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX10',
    topicIds: ['SH-04'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Số 68 sau khi viết thêm chữ số 0 vào bên phải trở thành số nào?',
    solutionSteps: [{ order: 1, content: '$68\\times10=680$.', rationale: 'Áp dụng quy tắc viết thêm 0.' }],
    mcq: { options: ['680', '608', '6800', '86'], answerIndex: 0 },
  },
  {
    id: 'SH-04-EX11',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số có 2 chữ số, chữ số hàng chục là 5. Nếu xóa chữ số hàng đơn vị thì được số mới kém số đã cho 47 đơn vị. Tìm chữ số hàng đơn vị.',
    solutionSteps: [{ order: 1, content: '$9\\times5+d=47 \\Rightarrow 45+d=47 \\Rightarrow d=2$.', rationale: 'Thay chữ số hàng chục đã biết vào biểu thức.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX12',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số có 2 chữ số. Nếu xóa chữ số hàng đơn vị thì được số mới kém số đã cho 76 đơn vị. Tìm số đã cho.',
    solutionSteps: [
      { order: 1, content: 'Gọi số đã cho $=10t+d$: $9t+d=76$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: 'Vì $0\\le d\\le9$ nên $t=8$ (vì $9\\times8=72$), $d=76-72=4$.', rationale: 'Xét điều kiện chữ số.' },
      { order: 3, content: 'Vậy số đã cho là 84.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['84'], tolerance: 0, isInteger: true },
  },

  // SH-05: Dấu hiệu chia hết
  {
    id: 'SH-05-EX4',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Số nào sau đây chia hết cho cả 3 và 5?',
    solutionSteps: [{ order: 1, content: '$45$: tổng chữ số $4+5=9$ chia hết 3, tận cùng 5 chia hết 5. Các số còn lại không thỏa cả hai điều kiện.', rationale: 'Kiểm tra đồng thời hai dấu hiệu chia hết.' }],
    mcq: { options: ['45', '40', '33', '28'], answerIndex: 0 },
  },
  {
    id: 'SH-05-EX5',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số $x$ (khác 0) để số $\\overline{7x2}$ chia hết cho 9.',
    solutionSteps: [
      { order: 1, content: 'Tổng các chữ số: $7+x+2=9+x$.', rationale: 'Lập tổng các chữ số.' },
      { order: 2, content: 'Để chia hết cho 9 thì $x=0$ hoặc $x=9$; vì $x\\ne0$ nên $x=9$.', rationale: 'Xét điều kiện chữ số khác 0.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-05-EX6',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Số nào sau đây chia hết cho cả 2, 3 và 5?',
    solutionSteps: [{ order: 1, content: '$2340$: tận cùng 0 (chia hết 2 và 5), tổng chữ số $2+3+4+0=9$ chia hết 3.', rationale: 'Kiểm tra đồng thời ba dấu hiệu chia hết.' }],
    mcq: { options: ['2340', '2341', '2343', '2345'], answerIndex: 0 },
  },
  {
    id: 'SH-05-EX7',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số $x$ lớn nhất để số $\\overline{45x}$ chia hết cho 3.',
    solutionSteps: [
      { order: 1, content: 'Tổng các chữ số: $4+5+x=9+x$; cần chia hết cho 3 nên $x\\in\\{0,3,6,9\\}$.', rationale: 'Xét các chữ số x thỏa mãn dấu hiệu chia hết cho 3.' },
      { order: 2, content: 'Chữ số lớn nhất thỏa mãn là $x=9$.', rationale: 'Chọn giá trị lớn nhất trong tập hợp.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-05-EX8',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số $\\overline{6x4}$ chia hết cho 9 khi $x$ bằng bao nhiêu?',
    solutionSteps: [{ order: 1, content: 'Tổng các chữ số $=6+x+4=10+x$; chỉ có $10+x=18$ (tức $x=8$) là giá trị hợp lệ trong khoảng $10$–$19$ chia hết cho 9.', rationale: 'Xét giá trị x duy nhất thỏa mãn trong khoảng hợp lệ.' }],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-05-EX9',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Số nào sau đây chia hết cho 5 nhưng không chia hết cho 2?',
    solutionSteps: [{ order: 1, content: '$25$ tận cùng 5 (chia hết 5) và là số lẻ (không chia hết 2).', rationale: 'Kiểm tra đồng thời hai điều kiện.' }],
    mcq: { options: ['25', '30', '44', '50'], answerIndex: 0 },
  },
  {
    id: 'SH-05-EX10',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số $x$ lớn nhất để số $\\overline{3x0}$ chia hết cho cả 2, 3 và 5.',
    solutionSteps: [
      { order: 1, content: 'Số tận cùng 0 nên luôn chia hết cho cả 2 và 5, không phụ thuộc $x$.', rationale: 'Xét dấu hiệu chia hết cho 2 và 5.' },
      { order: 2, content: 'Cần chia hết cho 3: tổng $3+x+0=3+x$ chia hết cho 3 khi $x\\in\\{0,3,6,9\\}$; lớn nhất là $x=9$.', rationale: 'Xét dấu hiệu chia hết cho 3.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-05-EX11',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Số nào sau đây chia hết cho 9?',
    solutionSteps: [{ order: 1, content: '$918$: tổng chữ số $9+1+8=18$ chia hết cho 9; các số còn lại có tổng chữ số không chia hết cho 9.', rationale: 'Áp dụng dấu hiệu chia hết cho 9.' }],
    mcq: { options: ['918', '917', '916', '915'], answerIndex: 0 },
  },
  {
    id: 'SH-05-EX12',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số $x$ nhỏ nhất (khác 0, vì là chữ số hàng trăm) để số $\\overline{x45}$ chia hết cho 3.',
    solutionSteps: [
      { order: 1, content: 'Tổng các chữ số $=x+4+5=x+9$; cần chia hết cho 3 nên $x$ chia hết cho 3 (vì 9 đã chia hết cho 3).', rationale: 'Lập tổng và xét điều kiện chia hết.' },
      { order: 2, content: 'Vì $x\\ne0$, các giá trị hợp lệ là $\\{3,6,9\\}$; nhỏ nhất là $x=3$.', rationale: 'Chọn giá trị nhỏ nhất trong tập hợp thỏa điều kiện khác 0.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['3'], tolerance: 0, isInteger: true },
  },

  // SH-09: Dãy số viết theo quy luật
  {
    id: 'SH-09-EX5',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Dãy số $3, 7, 11, \\ldots, 59$ có bao nhiêu số hạng?',
    solutionSteps: [{ order: 1, content: 'Khoảng cách $d=4$; số số hạng $=(59-3):4+1=14+1=15$.', rationale: 'Áp dụng công thức đếm số hạng.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX6',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính tổng dãy số $3, 6, 9, \\ldots, 60$.',
    solutionSteps: [
      { order: 1, content: 'Số số hạng $=(60-3):3+1=19+1=20$.', rationale: 'Đếm số số hạng.' },
      { order: 2, content: 'Tổng $=(3+60)\\times20:2=630$.', rationale: 'Áp dụng công thức tính tổng dãy cách đều.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['630'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX7',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm số hạng thứ 15 của dãy số $2, 5, 8, 11, \\ldots$',
    solutionSteps: [{ order: 1, content: 'Số hạng thứ $n = 2+(n-1)\\times3$; với $n=15$: $2+14\\times3=44$.', rationale: 'Áp dụng công thức số hạng tổng quát.' }],
    numeric: { kind: 'single', acceptedValues: ['44'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX8',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính tổng các số lẻ từ 1 đến 99.',
    solutionSteps: [
      { order: 1, content: 'Số số hạng $=(99-1):2+1=49+1=50$.', rationale: 'Đếm số số hạng.' },
      { order: 2, content: 'Tổng $=(1+99)\\times50:2=2500$.', rationale: 'Áp dụng công thức tính tổng dãy cách đều.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2500'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX9',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Dãy số $10, 15, 20, \\ldots, 100$ có bao nhiêu số hạng?',
    solutionSteps: [{ order: 1, content: 'Khoảng cách $d=5$; số số hạng $=(100-10):5+1=18+1=19$.', rationale: 'Áp dụng công thức đếm số hạng.' }],
    numeric: { kind: 'single', acceptedValues: ['19'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX10',
    topicIds: ['SH-09'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Tính tổng dãy số $5, 10, 15, 20$.',
    solutionSteps: [{ order: 1, content: '$5+10+15+20=50$.', rationale: 'Cộng trực tiếp các số hạng.' }],
    mcq: { options: ['40', '45', '50', '55'], answerIndex: 2 },
  },
  {
    id: 'SH-09-EX11',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm số hạng thứ 10 của dãy số $4, 9, 14, 19, \\ldots$',
    solutionSteps: [{ order: 1, content: 'Số hạng thứ $n = 4+(n-1)\\times5$; với $n=10$: $4+9\\times5=49$.', rationale: 'Áp dụng công thức số hạng tổng quát.' }],
    numeric: { kind: 'single', acceptedValues: ['49'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX12',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính tổng dãy số $7, 14, 21, \\ldots, 70$.',
    solutionSteps: [
      { order: 1, content: 'Số số hạng $=(70-7):7+1=9+1=10$.', rationale: 'Đếm số số hạng.' },
      { order: 2, content: 'Tổng $=(7+70)\\times10:2=385$.', rationale: 'Áp dụng công thức tính tổng dãy cách đều.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['385'], tolerance: 0, isInteger: true },
  },
];
