import type { Exercise } from '../../types';

export const shExercises: Exercise[] = [
  {
    id: 'SH-01-EX1',
    topicIds: ['SH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'So sánh hai số 8102 và 8120. Số nào lớn hơn? (nhập số lớn hơn)',
    solutionSteps: [
      { order: 1, content: 'Hàng nghìn, hàng trăm bằng nhau. Hàng chục: $0 < 2$.', rationale: 'So sánh từng hàng từ trái sang phải.' },
      { order: 2, content: 'Vậy $8120 > 8102$.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8120'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-01-EX2',
    topicIds: ['SH-01'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Chữ số 6 trong số 46 375 có giá trị là bao nhiêu?',
    solutionSteps: [
      { order: 1, content: 'Chữ số 6 đứng ở hàng nghìn.', rationale: 'Xác định vị trí chữ số.' },
      { order: 2, content: 'Giá trị $= 6 \\times 1000 = 6000$.', rationale: 'Nhân chữ số với giá trị hàng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['6000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-01-EX3',
    topicIds: ['SH-01'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Trong các số 3459, 3495, 3549, 3400, số nào bé nhất?',
    solutionSteps: [{ order: 1, content: 'So sánh hàng trăm và hàng chục: $3400 < 3459 < 3495 < 3549$.', rationale: 'So sánh từng hàng.' }],
    mcq: { options: ['3459', '3495', '3549', '3400'], answerIndex: 3 },
  },
  {
    id: 'SH-02-EX1',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $36 + 47 + 64$',
    solutionSteps: [
      { order: 1, content: 'Nhóm $36 + 64 = 100$.', rationale: 'Cộng hai số tròn trăm trước.' },
      { order: 2, content: '$100 + 47 = 147$.', rationale: 'Cộng số hạng còn lại.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['147'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-02-EX2',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $8 \\times 25 \\times 4 \\times 5$',
    solutionSteps: [
      { order: 1, content: 'Nhóm $(25 \\times 4) \\times (8 \\times 5) = 100 \\times 40$.', rationale: 'Nhóm các thừa số để ra số tròn.' },
      { order: 2, content: '$100 \\times 40 = 4000$.', rationale: 'Thực hiện phép nhân.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-02-EX3',
    topicIds: ['SH-02'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính bằng cách thuận tiện nhất: $125 \\times 3 \\times 8$',
    solutionSteps: [
      { order: 1, content: 'Nhóm $125 \\times 8 = 1000$.', rationale: 'Nhóm hai thừa số ra số tròn nghìn.' },
      { order: 2, content: '$1000 \\times 3 = 3000$.', rationale: 'Thực hiện phép nhân còn lại.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['3000'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-03-EX1',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $45 - 20 : 4$',
    solutionSteps: [
      { order: 1, content: '$20 : 4 = 5$.', rationale: 'Chia trước.' },
      { order: 2, content: '$45 - 5 = 40$.', rationale: 'Trừ sau.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['40'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-03-EX2',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $(45 - 20) : 5$',
    solutionSteps: [
      { order: 1, content: 'Trong ngoặc trước: $45 - 20 = 25$.', rationale: 'Ngoặc luôn tính trước.' },
      { order: 2, content: '$25 : 5 = 5$.', rationale: 'Chia sau.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['5'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-03-EX3',
    topicIds: ['SH-03'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tính: $6 \\times 7 - 15 : 3$',
    solutionSteps: [
      { order: 1, content: '$6 \\times 7 = 42$ và $15 : 3 = 5$.', rationale: 'Nhân và chia trước, từ trái sang phải.' },
      { order: 2, content: '$42 - 5 = 37$.', rationale: 'Trừ sau cùng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['37'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX1',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Nếu viết thêm chữ số 0 vào bên phải một số thì số đó tăng thêm 153 đơn vị. Tìm số đó.',
    solutionSteps: [
      { order: 1, content: 'Gọi số cũ là $a$: $10a - a = 9a = 153$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: '$a = 153 : 9 = 17$.', rationale: 'Giải tìm số cũ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['17'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX2',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số có 2 chữ số. Nếu xóa chữ số hàng đơn vị thì được số mới kém số đã cho 44 đơn vị. Tìm số đã cho.',
    solutionSteps: [
      { order: 1, content: 'Gọi số đã cho $= 10t + d$; xóa chữ số hàng đơn vị được $t$: $9t + d = 44$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: 'Vì $0 \\le d \\le 9$ nên $t = 4$ (vì $9 \\times 4 = 36$), $d = 44 - 36 = 8$.', rationale: 'Xét điều kiện chữ số.' },
      { order: 3, content: 'Vậy số đã cho là 48.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['48'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-04-EX3',
    topicIds: ['SH-04'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Số 27 sau khi viết thêm chữ số 0 vào bên phải trở thành số nào?',
    solutionSteps: [{ order: 1, content: 'Viết thêm 0 vào bên phải nghĩa là nhân 10: $27 \\times 10 = 270$.', rationale: 'Áp dụng quy tắc.' }],
    mcq: { options: ['270', '027', '207', '2700'], answerIndex: 0 },
  },
  {
    id: 'SH-04-EX4',
    topicIds: ['SH-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một số có 2 chữ số. Nếu xóa chữ số hàng đơn vị thì được số mới kém số đã cho 58 đơn vị. Tìm số đã cho.',
    solutionSteps: [
      { order: 1, content: 'Gọi số đã cho $= 10t + d$: $9t + d = 58$.', rationale: 'Lập biểu thức theo dữ kiện.' },
      { order: 2, content: 'Vì $0 \\le d \\le 9$ nên $t = 6$ (vì $9 \\times 6 = 54$), $d = 58 - 54 = 4$.', rationale: 'Xét điều kiện chữ số.' },
      { order: 3, content: 'Vậy số đã cho là 64.', rationale: 'Kết luận.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['64'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-05-EX1',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Số nào sau đây chia hết cho 9?',
    solutionSteps: [{ order: 1, content: 'Tổng các chữ số của 621 là $6+2+1=9$, chia hết cho 9; các số còn lại có tổng chữ số không chia hết cho 9.', rationale: 'Áp dụng dấu hiệu chia hết cho 9.' }],
    mcq: { options: ['621', '622', '623', '625'], answerIndex: 0 },
  },
  {
    id: 'SH-05-EX2',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số $x$ (khác 0) để số $\\overline{3x6}$ chia hết cho 9.',
    solutionSteps: [
      { order: 1, content: 'Tổng các chữ số: $3 + x + 6 = 9 + x$.', rationale: 'Lập tổng các chữ số.' },
      { order: 2, content: 'Để chia hết cho 9 thì $9 + x$ chia hết cho 9; vì $x \\ne 0$ nên $x = 9$.', rationale: 'Xét điều kiện chữ số khác 0.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-05-EX3',
    topicIds: ['SH-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số tận cùng $x$ để số $\\overline{24x}$ chia hết cho cả 2 và 5.',
    solutionSteps: [{ order: 1, content: 'Chỉ có chữ số 0 vừa chẵn vừa chia hết cho 5.', rationale: 'Kết hợp hai dấu hiệu chia hết.' }],
    numeric: { kind: 'single', acceptedValues: ['0'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-06-EX1',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Một phép chia có số chia 6, thương 12, số dư 5. Tìm số bị chia.',
    solutionSteps: [{ order: 1, content: '$6 \\times 12 + 5 = 72 + 5 = 77$.', rationale: 'Áp dụng công thức số bị chia.' }],
    numeric: { kind: 'single', acceptedValues: ['77'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-06-EX2',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Số bị chia là 100, số chia là 7. Tìm số dư của phép chia đó.',
    solutionSteps: [{ order: 1, content: '$100 = 7 \\times 14 + 2$, vậy số dư là 2.', rationale: 'Thực hiện phép chia có dư.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-06-EX3',
    topicIds: ['SH-06'],
    level: 'basic',
    answerType: 'mcq',
    statement: 'Phép chia nào sau đây có số dư hợp lệ (số dư nhỏ hơn số chia)?',
    solutionSteps: [{ order: 1, content: '$37 = 5 \\times 7 + 2$ nên $37 : 5$ dư 2 là hợp lệ; các số dư 5,6,7 đều không nhỏ hơn 5.', rationale: 'Kiểm tra điều kiện số dư nhỏ hơn số chia.' }],
    mcq: { options: ['37 : 5 dư 2', '37 : 5 dư 7', '37 : 5 dư 5', '37 : 5 dư 6'], answerIndex: 0 },
  },
  {
    id: 'SH-07-EX1',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $84 - x = 37$',
    solutionSteps: [{ order: 1, content: '$x = 84 - 37 = 47$.', rationale: 'Muốn tìm số trừ, lấy số bị trừ trừ hiệu.' }],
    numeric: { kind: 'single', acceptedValues: ['47'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-07-EX2',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $x : 5 = 13$',
    solutionSteps: [{ order: 1, content: '$x = 13 \\times 5 = 65$.', rationale: 'Muốn tìm số bị chia, lấy thương nhân số chia.' }],
    numeric: { kind: 'single', acceptedValues: ['65'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-07-EX3',
    topicIds: ['SH-07'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm $x$: $90 : x = 6$',
    solutionSteps: [{ order: 1, content: '$x = 90 : 6 = 15$.', rationale: 'Muốn tìm số chia, lấy số bị chia chia thương.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-08-EX1',
    topicIds: ['SH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Tìm trung bình cộng của 15, 25, 35, 45.',
    solutionSteps: [
      { order: 1, content: 'Tổng $= 15+25+35+45=120$.', rationale: 'Cộng tất cả các số hạng.' },
      { order: 2, content: 'TBC $=120:4=30$.', rationale: 'Chia tổng cho số lượng số hạng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['30'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-08-EX2',
    topicIds: ['SH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Ba lớp có số học sinh lần lượt là 32, 35, 38. Tính trung bình mỗi lớp có bao nhiêu học sinh?',
    solutionSteps: [
      { order: 1, content: 'Tổng $=32+35+38=105$.', rationale: 'Cộng số học sinh cả 3 lớp.' },
      { order: 2, content: 'TBC $=105:3=35$.', rationale: 'Chia tổng cho số lớp.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['35'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-08-EX3',
    topicIds: ['SH-08'],
    level: 'basic',
    answerType: 'numeric',
    statement: 'Trung bình cộng của hai số là 25. Biết một trong hai số là 18. Tìm số còn lại.',
    solutionSteps: [
      { order: 1, content: 'Tổng hai số $=25 \\times 2=50$.', rationale: 'Từ TBC suy ra tổng.' },
      { order: 2, content: 'Số còn lại $=50-18=32$.', rationale: 'Lấy tổng trừ số đã biết.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['32'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX1',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Dãy số $4, 8, 12, \\ldots, 60$ có bao nhiêu số hạng?',
    solutionSteps: [{ order: 1, content: 'Số số hạng $=(60-4):4+1=14+1=15$.', rationale: 'Áp dụng công thức đếm số hạng.' }],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX2',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính tổng dãy số $2, 5, 8, \\ldots, 29$.',
    solutionSteps: [
      { order: 1, content: 'Số số hạng $=(29-2):3+1=9+1=10$.', rationale: 'Đếm số số hạng.' },
      { order: 2, content: 'Tổng $=(2+29) \\times 10:2=155$.', rationale: 'Áp dụng công thức tính tổng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['155'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX3',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm số hạng thứ 20 của dãy số $3, 6, 9, 12, \\ldots$',
    solutionSteps: [{ order: 1, content: 'Số hạng thứ $n$ $= 3 + (n-1) \\times 3$; với $n=20$: $3+19\\times3=3+57=60$.', rationale: 'Áp dụng công thức số hạng tổng quát.' }],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-09-EX4',
    topicIds: ['SH-09'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính tổng các số chẵn từ 2 đến 100.',
    solutionSteps: [
      { order: 1, content: 'Số số hạng $=(100-2):2+1=49+1=50$.', rationale: 'Đếm số số hạng.' },
      { order: 2, content: 'Tổng $=(2+100) \\times 50:2=2550$.', rationale: 'Áp dụng công thức tính tổng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2550'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-10-EX1',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm ước chung lớn nhất của 24 và 36.',
    solutionSteps: [
      { order: 1, content: '$Ư(24)=\\{1,2,3,4,6,8,12,24\\}$, $Ư(36)=\\{1,2,3,4,6,9,12,18,36\\}$.', rationale: 'Liệt kê ước của mỗi số.' },
      { order: 2, content: 'Ước chung lớn nhất là 12.', rationale: 'Tìm số lớn nhất chung cho cả hai tập ước.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-10-EX2',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm bội chung nhỏ nhất của 4 và 6.',
    solutionSteps: [{ order: 1, content: 'Bội của 4: 4,8,12,16...; bội của 6: 6,12,18... Bội chung nhỏ nhất là 12.', rationale: 'Liệt kê bội và tìm số nhỏ nhất chung.' }],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-10-EX3',
    topicIds: ['SH-10'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Trong các số 13, 14, 15, 16, số nào là số nguyên tố?',
    solutionSteps: [{ order: 1, content: '$14=2\\times7$, $15=3\\times5$, $16=2^4$ đều không phải số nguyên tố; 13 chỉ có ước 1 và 13.', rationale: 'Kiểm tra ước của từng số.' }],
    mcq: { options: ['13', '14', '15', '16'], answerIndex: 0 },
  },
];
