import type { Exercise } from '../../types';

export const tdExercises: Exercise[] = [
  {
    id: 'TD-01-EX1',
    topicIds: ['TD-01'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Ba bạn Bình, Chi, Dũng mỗi người thích một loại nước: cam, chanh, dừa. Biết Bình không thích cam và không thích dừa; Chi không thích dừa. Dũng thích loại nước gì?',
    solutionSteps: [
      { order: 1, content: 'Bình không cam, không dừa $\\Rightarrow$ Bình thích chanh.', rationale: 'Loại trừ hai khả năng cho Bình.' },
      { order: 2, content: 'Chi không dừa, chanh đã thuộc Bình $\\Rightarrow$ Chi thích cam.', rationale: 'Tiếp tục loại trừ.' },
      { order: 3, content: 'Còn lại Dũng thích dừa.', rationale: 'Khả năng duy nhất còn lại.' },
    ],
    mcq: { options: ['Cam', 'Chanh', 'Dừa', 'Không xác định'], answerIndex: 2 },
  },
  {
    id: 'TD-01-EX2',
    topicIds: ['TD-01'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Bốn bạn xếp hàng: Việt đứng trước Nam, Nam đứng trước Hùng, Hùng đứng trước Sơn. Ai đứng cuối hàng?',
    solutionSteps: [{ order: 1, content: 'Thứ tự: Việt, Nam, Hùng, Sơn $\\Rightarrow$ Sơn đứng cuối.', rationale: 'Ghép các quan hệ "trước" thành một thứ tự duy nhất.' }],
    mcq: { options: ['Việt', 'Nam', 'Hùng', 'Sơn'], answerIndex: 3 },
  },
  {
    id: 'TD-01-EX3',
    topicIds: ['TD-01'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Ba hộp bút màu: đỏ, xanh, vàng. Hộp A không phải đỏ và không phải vàng. Hộp B không phải vàng. Hộp C là màu gì?',
    solutionSteps: [
      { order: 1, content: 'A không đỏ, không vàng $\\Rightarrow$ A màu xanh.', rationale: 'Loại trừ hai khả năng cho A.' },
      { order: 2, content: 'B không vàng, xanh đã thuộc A $\\Rightarrow$ B màu đỏ.', rationale: 'Tiếp tục loại trừ.' },
      { order: 3, content: 'Còn lại C màu vàng.', rationale: 'Khả năng duy nhất còn lại.' },
    ],
    mcq: { options: ['Đỏ', 'Xanh', 'Vàng', 'Không xác định'], answerIndex: 2 },
  },
  {
    id: 'TD-02-EX1',
    topicIds: ['TD-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trên một đường thẳng có 7 điểm phân biệt. Hỏi có tất cả bao nhiêu đoạn thẳng?',
    solutionSteps: [{ order: 1, content: '$7\\times6:2=21$.', rationale: 'Áp dụng công thức đếm đoạn thẳng.' }],
    numeric: { kind: 'single', acceptedValues: ['21'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-02-EX2',
    topicIds: ['TD-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có 8 điểm không có 3 điểm nào thẳng hàng. Hỏi nối được bao nhiêu đoạn thẳng?',
    solutionSteps: [{ order: 1, content: '$8\\times7:2=28$.', rationale: 'Mỗi cặp điểm tạo đúng 1 đoạn thẳng.' }],
    numeric: { kind: 'single', acceptedValues: ['28'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-02-EX3',
    topicIds: ['TD-02'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trên một đường thẳng có 10 điểm phân biệt. Hỏi có tất cả bao nhiêu đoạn thẳng?',
    solutionSteps: [{ order: 1, content: '$10\\times9:2=45$.', rationale: 'Áp dụng công thức đếm đoạn thẳng.' }],
    numeric: { kind: 'single', acceptedValues: ['45'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-03-EX1',
    topicIds: ['TD-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có 20 viên bi chia vào 6 hộp. Hộp nhiều nhất chứa ít nhất bao nhiêu viên?',
    solutionSteps: [
      { order: 1, content: 'Nếu mỗi hộp tối đa 3 viên thì tổng tối đa $=6\\times3=18<20$.', rationale: 'Giả sử phản chứng.' },
      { order: 2, content: 'Vậy có ít nhất 1 hộp chứa từ 4 viên trở lên.', rationale: 'Áp dụng nguyên lý Dirichlet.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-03-EX2',
    topicIds: ['TD-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trong một nhóm có 32 học sinh. Hỏi chắc chắn có ít nhất bao nhiêu học sinh cùng tháng sinh (12 tháng)?',
    solutionSteps: [
      { order: 1, content: 'Nếu mỗi tháng tối đa 2 học sinh thì tổng tối đa $=12\\times2=24<32$.', rationale: 'Giả sử phản chứng.' },
      { order: 2, content: 'Vậy có ít nhất 1 tháng có từ 3 học sinh trở lên.', rationale: 'Áp dụng nguyên lý Dirichlet.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['3'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-03-EX3',
    topicIds: ['TD-03'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có 50 cuốn sách xếp vào 7 kệ. Kệ nhiều nhất chứa ít nhất bao nhiêu cuốn?',
    solutionSteps: [
      { order: 1, content: 'Nếu mỗi kệ tối đa 7 cuốn thì tổng tối đa $=7\\times7=49<50$.', rationale: 'Giả sử phản chứng.' },
      { order: 2, content: 'Vậy có ít nhất 1 kệ chứa từ 8 cuốn trở lên.', rationale: 'Áp dụng nguyên lý Dirichlet.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-04-EX1',
    topicIds: ['TD-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có can 7 lít và can 4 lít (không vạch chia). Đổ đầy can 7 lít rồi rót sang can 4 lít cho đầy. Can 7 lít còn lại bao nhiêu lít?',
    solutionSteps: [{ order: 1, content: '$7-4=3$ lít.', rationale: 'Lấy dung tích can lớn trừ dung tích can nhỏ đã rót đầy.' }],
    numeric: { kind: 'single', acceptedValues: ['3'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-04-EX2',
    topicIds: ['TD-04'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Có 4 viên bi giống nhau, 1 viên nặng hơn. Cần ít nhất bao nhiêu lần cân (cân thăng bằng) để chắc chắn tìm ra viên đó?',
    solutionSteps: [{ order: 1, content: 'Cân 1 viên với 1 viên: nếu lệch thì biết ngay; nếu bằng thì viên nặng nằm trong 2 viên còn lại, cân tiếp 1 lần nữa — cần tối đa 2 lần để chắc chắn.', rationale: 'Xét trường hợp xấu nhất.' }],
    mcq: { options: ['2 lần', '1 lần', '3 lần', '4 lần'], answerIndex: 0 },
  },
  {
    id: 'TD-04-EX3',
    topicIds: ['TD-04'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có can 6 lít và can 4 lít. Đổ đầy can 6 lít rồi rót sang can 4 lít cho đầy. Can 6 lít còn lại bao nhiêu lít?',
    solutionSteps: [{ order: 1, content: '$6-4=2$ lít.', rationale: 'Lấy dung tích can lớn trừ dung tích can nhỏ đã rót đầy.' }],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-05-EX1',
    topicIds: ['TD-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Dãy que diêm tăng đều: hình 1 dùng 4 que, hình 2 dùng 7 que, hình 3 dùng 10 que. Hình thứ 6 dùng bao nhiêu que?',
    solutionSteps: [{ order: 1, content: '$4+(6-1)\\times3=4+15=19$.', rationale: 'Áp dụng công thức số hạng tổng quát.' }],
    numeric: { kind: 'single', acceptedValues: ['19'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-05-EX2',
    topicIds: ['TD-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Dãy số chấm tam giác: hình 1 có 1 chấm, hình 2 có 3 chấm, hình 3 có 6 chấm. Hình thứ 6 có bao nhiêu chấm?',
    solutionSteps: [{ order: 1, content: '$6\\times7:2=21$.', rationale: 'Áp dụng công thức dãy số tam giác.' }],
    numeric: { kind: 'single', acceptedValues: ['21'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-05-EX3',
    topicIds: ['TD-05'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một dãy hình vuông ghép que diêm theo hàng ngang: hình 1 dùng 4 que, mỗi hình sau ghép thêm 1 hình vuông liền kề dùng thêm 3 que. Hình thứ 10 dùng bao nhiêu que?',
    solutionSteps: [{ order: 1, content: '$4+(10-1)\\times3=4+27=31$.', rationale: 'Áp dụng công thức số hạng tổng quát.' }],
    numeric: { kind: 'single', acceptedValues: ['31'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-06-EX1',
    topicIds: ['TD-06'],
    level: 'advanced',
    answerType: 'essay',
    statement: 'Giải thích vì sao tổng của hai số chẵn bất kỳ luôn là một số chẵn. Minh họa bằng một ví dụ cụ thể.',
    solutionSteps: [
      { order: 1, content: 'Số chẵn là số chia hết cho 2.', rationale: 'Nhắc lại khái niệm số chẵn.' },
      { order: 2, content: 'Khi cộng hai số cùng chia hết cho 2, tổng cũng chia hết cho 2.', rationale: 'Tính chất của phép cộng hai số chia hết cho cùng một số.' },
      { order: 3, content: 'Ví dụ: $8+14=22$; cả 8, 14 và 22 đều là số chẵn.', rationale: 'Kiểm chứng bằng ví dụ cụ thể.' },
    ],
    essay: {
      modelSolution:
        'Số chẵn là số chia hết cho 2. Khi cộng hai số đều chia hết cho 2, tổng cũng chia hết cho 2. Ví dụ: 8 + 14 = 22, cả 8, 14 và 22 đều chia hết cho 2. Vậy tổng của hai số chẵn bất kỳ luôn là số chẵn.',
      rubric: [
        { criterion: 'Nêu đúng khái niệm số chẵn (chia hết cho 2)', points: 1 },
        { criterion: 'Giải thích được lý do tổng vẫn chia hết cho 2', points: 1 },
        { criterion: 'Đưa ra ví dụ minh họa đúng', points: 1 },
      ],
    },
  },
  {
    id: 'TD-06-EX2',
    topicIds: ['TD-06'],
    level: 'advanced',
    answerType: 'essay',
    statement: 'Giải thích vì sao một số có chữ số tận cùng là 0 thì luôn chia hết cho cả 2 và 5. Minh họa bằng số 350.',
    solutionSteps: [
      { order: 1, content: 'Số có chữ số tận cùng là 0 nghĩa là số đó chia hết cho 10.', rationale: 'Liên hệ chữ số tận cùng 0 với việc chia hết cho 10.' },
      { order: 2, content: 'Vì $10=2\\times5$, nên số chia hết cho 10 chắc chắn chia hết cho cả 2 và 5.', rationale: 'Phân tích 10 thành tích của 2 và 5.' },
      { order: 3, content: 'Ví dụ: $350=35\\times10$; $350:2=175$ và $350:5=70$, đều chia hết.', rationale: 'Kiểm chứng bằng ví dụ cụ thể.' },
    ],
    essay: {
      modelSolution:
        'Số có chữ số tận cùng là 0 nghĩa là số đó chia hết cho 10 (vì 10 chính là 1 chục). Mà 10 = 2 x 5, nên số chia hết cho 10 chắc chắn chia hết cho cả 2 và 5. Ví dụ: 350 = 35 x 10, chia hết cho 2 (350:2=175) và chia hết cho 5 (350:5=70).',
      rubric: [
        { criterion: 'Giải thích được số tận cùng 0 thì chia hết cho 10', points: 1 },
        { criterion: 'Liên hệ 10 = 2 x 5 để suy ra chia hết cho cả 2 và 5', points: 1 },
        { criterion: 'Kiểm chứng đúng bằng ví dụ số 350', points: 1 },
      ],
    },
  },
  {
    id: 'TD-06-EX3',
    topicIds: ['TD-06'],
    level: 'advanced',
    answerType: 'essay',
    statement: 'Giải thích vì sao trong 4 số tự nhiên liên tiếp bất kỳ luôn có ít nhất một số chia hết cho 4. Minh họa bằng ví dụ cụ thể.',
    solutionSteps: [
      { order: 1, content: 'Khi chia một số tự nhiên bất kỳ cho 4, số dư chỉ có thể là 0, 1, 2 hoặc 3.', rationale: 'Liệt kê đầy đủ các khả năng của số dư.' },
      { order: 2, content: 'Trong 4 số liên tiếp, các số dư khi chia cho 4 sẽ lần lượt đi qua đủ 4 giá trị 0, 1, 2, 3, nên chắc chắn có đúng một số dư 0.', rationale: 'Xét tính liên tục của số dư giữa các số liên tiếp.' },
      { order: 3, content: 'Ví dụ: $9, 10, 11, 12$ có $12$ chia hết cho 4.', rationale: 'Kiểm chứng bằng ví dụ cụ thể.' },
    ],
    essay: {
      modelSolution:
        'Khi chia một số tự nhiên bất kỳ cho 4, số dư chỉ có thể là 0, 1, 2 hoặc 3. Trong 4 số liên tiếp, số dư khi chia cho 4 sẽ lần lượt đi qua đủ các giá trị 0, 1, 2, 3, nên chắc chắn có đúng một số có số dư là 0, tức là chia hết cho 4. Ví dụ: 9, 10, 11, 12 thì 12 chia hết cho 4.',
      rubric: [
        { criterion: 'Giải thích được số dư khi chia cho 4 chỉ có 4 khả năng: 0, 1, 2, 3', points: 1 },
        { criterion: 'Suy luận được trong 4 số liên tiếp phải có đủ số dư 0', points: 1 },
        { criterion: 'Đưa ra ví dụ minh họa đúng', points: 1 },
      ],
    },
  },
];
