import type { Exercise } from '../../types';

/** Bài tập cho 10 chuyên đề mới bổ sung theo URD v2.0 (SH-11/12, PS-11, DH-15/16/17, HH-12, DL-07/08, TD-07). */
export const v2NewExercises: Exercise[] = [
  // SH-11 — Chữ số tận cùng
  {
    id: 'SH-11-EX1',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số tận cùng của $7^{2025}$.',
    solutionSteps: [
      { order: 1, content: 'Chu kỳ tận cùng của $7$ là $7, 9, 3, 1$ (chu kỳ $4$).', rationale: 'Liệt kê chu kỳ.' },
      { order: 2, content: '$2025 : 4 = 506$ dư $1$, ứng với vị trí $1$ trong chu kỳ: chữ số $7$.', rationale: 'Số dư 1 ứng phần tử đầu chu kỳ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['7'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-11-EX2',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tìm chữ số tận cùng của $8^{2026}$.',
    solutionSteps: [
      { order: 1, content: 'Chu kỳ tận cùng của $8$ là $8, 4, 2, 6$ (chu kỳ $4$).', rationale: 'Liệt kê chu kỳ.' },
      { order: 2, content: '$2026 : 4 = 506$ dư $2$, ứng với vị trí $2$ trong chu kỳ: chữ số $4$.', rationale: 'Số dư 2 ứng phần tử thứ 2 chu kỳ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-11-EX3',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tích $12 \\times 34 \\times 56$ có chữ số tận cùng là bao nhiêu?',
    solutionSteps: [
      { order: 1, content: 'Chữ số tận cùng của các thừa số: $2, 4, 6$.', rationale: 'Chỉ cần xét chữ số tận cùng.' },
      { order: 2, content: '$2 \\times 4 \\times 6 = 48$, chữ số tận cùng là $8$.', rationale: 'Nhân các chữ số tận cùng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-11-EX4',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tích $21 \\times 22 \\times 23 \\times 24$ có chữ số tận cùng là bao nhiêu?',
    solutionSteps: [
      { order: 1, content: 'Chữ số tận cùng của các thừa số: $1, 2, 3, 4$.', rationale: 'Chỉ cần xét chữ số tận cùng.' },
      { order: 2, content: '$1 \\times 2 \\times 3 \\times 4 = 24$, chữ số tận cùng là $4$.', rationale: 'Nhân các chữ số tận cùng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-11-EX5',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tích $25 \\times 48$ tận cùng bằng mấy chữ số 0?',
    solutionSteps: [
      { order: 1, content: '$25 = 5^2$; $48 = 2^4 \\times 3$.', rationale: 'Phân tích ra thừa số nguyên tố.' },
      { order: 2, content: 'Số lũy thừa của $2$ là $4$, số lũy thừa của $5$ là $2$; số nhỏ hơn là $2$.', rationale: 'Số chữ số 0 = số nhỏ hơn giữa hai lũy thừa.' },
      { order: 3, content: 'Vậy tích tận cùng bằng $2$ chữ số $0$ (kiểm tra: $25 \\times 48 = 1200$).', rationale: 'Xác nhận bằng phép nhân trực tiếp.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-11-EX6',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Số $A = 15 \\times 16 \\times 17 \\times 18 \\times 19 \\times 20$ tận cùng bằng mấy chữ số 0?',
    solutionSteps: [
      { order: 1, content: 'Lũy thừa của $2$: $16=2^4$, $18=2\\times3^2$, $20=2^2\\times5$ $\\Rightarrow$ tổng mũ $2$ là $4+1+2=7$.', rationale: 'Đếm lũy thừa của 2 trong các thừa số.' },
      { order: 2, content: 'Lũy thừa của $5$: $15=3\\times5$, $20=2^2\\times5$ $\\Rightarrow$ tổng mũ $5$ là $1+1=2$.', rationale: 'Đếm lũy thừa của 5 trong các thừa số.' },
      { order: 3, content: 'Số chữ số $0$ tận cùng $= \\min(7, 2) = 2$.', rationale: 'Lấy số nhỏ hơn giữa hai lũy thừa.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-11-EX7',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Chữ số tận cùng của $9^{35}$ là bao nhiêu?',
    solutionSteps: [
      { order: 1, content: 'Chu kỳ tận cùng của $9$ là $9, 1$ (chu kỳ $2$): số mũ lẻ tận cùng $9$, số mũ chẵn tận cùng $1$.', rationale: 'Chu kỳ của 9 chỉ có độ dài 2.' },
      { order: 2, content: '$35$ là số lẻ nên $9^{35}$ tận cùng là $9$.', rationale: 'Áp dụng quy tắc số mũ lẻ.' },
    ],
    mcq: { options: ['9', '1', '3', '7'], answerIndex: 0 },
  },
  {
    id: 'SH-11-EX8',
    topicIds: ['SH-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tích $2^{10} \\times 5^{7}$ tận cùng bằng mấy chữ số 0?',
    solutionSteps: [
      { order: 1, content: 'Số lũy thừa của $2$ là $10$, số lũy thừa của $5$ là $7$.', rationale: 'Đọc trực tiếp số mũ đã cho.' },
      { order: 2, content: 'Số chữ số $0$ tận cùng $= \\min(10, 7) = 7$.', rationale: 'Lấy số nhỏ hơn giữa hai lũy thừa.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['7'], tolerance: 0, isInteger: true },
  },

  // SH-12 — Dãy chữ; đánh số trang sách
  {
    id: 'SH-12-EX1',
    topicIds: ['SH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một quyển sách dày 120 trang. Hỏi cần dùng bao nhiêu chữ số để đánh số trang từ 1 đến 120?',
    solutionSteps: [
      { order: 1, content: 'Trang $1$–$9$: $9 \\times 1 = 9$ chữ số.', rationale: 'Trang 1 chữ số.' },
      { order: 2, content: 'Trang $10$–$99$: $90 \\times 2 = 180$ chữ số.', rationale: 'Trang 2 chữ số.' },
      { order: 3, content: 'Trang $100$–$120$: $(120-100+1) \\times 3 = 21 \\times 3 = 63$ chữ số.', rationale: 'Trang 3 chữ số, chỉ tính tới trang 120.' },
      { order: 4, content: 'Tổng: $9 + 180 + 63 = 252$ chữ số.', rationale: 'Cộng dồn 3 đoạn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['252'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-12-EX2',
    topicIds: ['SH-12'],
    level: 'advanced',
    answerType: 'mcq',
    statement: "Dãy chữ cái lặp lại theo chu kỳ 'HOCTOAN' (7 chữ). Chữ cái thứ 100 trong dãy là chữ gì?",
    solutionSteps: [
      { order: 1, content: '$100 : 7 = 14$ dư $2$.', rationale: 'Chia vị trí cho độ dài chu kỳ.' },
      { order: 2, content: 'Số dư $2$ ứng với chữ cái thứ $2$ trong "HOCTOAN": $H(1), O(2), C(3), T(4), O(5), A(6), N(7)$.', rationale: 'Đếm tới vị trí ứng với số dư.' },
      { order: 3, content: 'Vậy chữ cái thứ 100 là $O$.', rationale: 'Kết luận.' },
    ],
    mcq: { options: ['O', 'H', 'C', 'T'], answerIndex: 0 },
  },
  {
    id: 'SH-12-EX3',
    topicIds: ['SH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Để đánh số các trang của một quyển sách, người ta dùng hết 993 chữ số. Hỏi quyển sách đó có bao nhiêu trang?',
    solutionSteps: [
      { order: 1, content: 'Trang $1$–$99$ dùng hết $9 + 180 = 189$ chữ số.', rationale: 'Tính số chữ số dùng cho 99 trang đầu.' },
      { order: 2, content: 'Số chữ số còn lại cho các trang 3 chữ số: $993 - 189 = 804$.', rationale: 'Trừ đi phần đã dùng.' },
      { order: 3, content: 'Số trang 3 chữ số: $804 : 3 = 268$ trang.', rationale: 'Mỗi trang 3 chữ số dùng 3 chữ số.' },
      { order: 4, content: 'Tổng số trang: $99 + 268 = 367$ trang.', rationale: 'Cộng 99 trang đầu với 268 trang sau.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['367'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-12-EX4',
    topicIds: ['SH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Người ta viết liền các số tự nhiên bắt đầu từ 1: $123456789101112...$. Chữ số thứ 15 trong dãy này là chữ số nào?',
    solutionSteps: [
      { order: 1, content: 'Các số $1$ đến $9$ chiếm $9$ vị trí đầu.', rationale: 'Mỗi số 1 chữ số chiếm 1 vị trí.' },
      { order: 2, content: 'Từ vị trí $10$ trở đi là các số 2 chữ số: $10, 11, 12,...$; vị trí $15$ cách vị trí $10$ là $15-9=6$ vị trí trong nhóm này.', rationale: 'Xác định vị trí tương đối trong nhóm 2 chữ số.' },
      { order: 3, content: 'Số thứ $\\lceil 6/2 \\rceil = 3$ trong nhóm là $12$ (đếm $10, 11, 12$); vị trí trong số đó là $6 - (3-1)\\times2 = 2$, tức là chữ số thứ 2 của "$12$" là "$2$".', rationale: 'Xác định đúng số và đúng chữ số trong số đó.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-12-EX5',
    topicIds: ['SH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một quyển sách dày 200 trang. Hỏi cần dùng bao nhiêu chữ số để đánh số trang từ 1 đến 200?',
    solutionSteps: [
      { order: 1, content: 'Trang $1$–$9$: $9$ chữ số. Trang $10$–$99$: $180$ chữ số.', rationale: 'Tính 2 đoạn đầu.' },
      { order: 2, content: 'Trang $100$–$200$: $(200-100+1) \\times 3 = 101 \\times 3 = 303$ chữ số.', rationale: 'Đoạn trang 3 chữ số.' },
      { order: 3, content: 'Tổng: $9 + 180 + 303 = 492$ chữ số.', rationale: 'Cộng dồn 3 đoạn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['492'], tolerance: 0, isInteger: true },
  },
  {
    id: 'SH-12-EX6',
    topicIds: ['SH-12'],
    level: 'advanced',
    answerType: 'mcq',
    statement: "Dãy chữ cái lặp lại theo chu kỳ 'TOAN' (4 chữ). Chữ cái thứ 37 trong dãy là chữ gì?",
    solutionSteps: [
      { order: 1, content: '$37 : 4 = 9$ dư $1$.', rationale: 'Chia vị trí cho độ dài chu kỳ.' },
      { order: 2, content: 'Số dư $1$ ứng với chữ cái đầu tiên trong "TOAN": chữ $T$.', rationale: 'Kết luận theo số dư.' },
    ],
    mcq: { options: ['T', 'O', 'A', 'N'], answerIndex: 0 },
  },

  // PS-11 — Trộn dung dịch, tươi-khô
  {
    id: 'PS-11-EX1',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '8kg nấm tươi chứa 80% nước. Sau khi phơi khô, nấm khô chỉ còn chứa 20% nước. Tính khối lượng nấm khô thu được.',
    solutionSteps: [
      { order: 1, content: 'Khối lượng chất khô $= 8 \\times (100\\% - 80\\%) = 8 \\times 20\\% = 1{,}6$kg.', rationale: 'Phần chất khô không đổi khi phơi.' },
      { order: 2, content: 'Nấm khô có $100\\% - 20\\% = 80\\%$ là chất khô.', rationale: 'Xác định tỉ lệ chất khô trong nấm khô.' },
      { order: 3, content: 'Khối lượng nấm khô $= 1{,}6 : 80\\% = 2$kg.', rationale: 'Chia chất khô cho tỉ lệ chất khô trong khô.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0 },
  },
  {
    id: 'PS-11-EX2',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '15kg măng tươi chứa 90% nước. Phơi khô còn 25% nước. Tính khối lượng măng khô thu được.',
    solutionSteps: [
      { order: 1, content: 'Khối lượng chất khô $= 15 \\times 10\\% = 1{,}5$kg.', rationale: 'Phần chất khô không đổi.' },
      { order: 2, content: 'Măng khô có $75\\%$ là chất khô.', rationale: 'Xác định tỉ lệ chất khô trong khô.' },
      { order: 3, content: 'Khối lượng măng khô $= 1{,}5 : 75\\% = 2$kg.', rationale: 'Chia chất khô cho tỉ lệ chất khô.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0 },
  },
  {
    id: 'PS-11-EX3',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Người ta thu được 3kg mực khô từ mực tươi chứa 75% nước, biết mực khô chứa 20% nước. Hỏi cần bao nhiêu kg mực tươi?',
    solutionSteps: [
      { order: 1, content: 'Khối lượng chất khô trong mực khô $= 3 \\times (100\\% - 20\\%) = 3 \\times 80\\% = 2{,}4$kg.', rationale: 'Chất khô trong mực khô cũng chính là chất khô ban đầu.' },
      { order: 2, content: 'Mực tươi có $100\\% - 75\\% = 25\\%$ là chất khô.', rationale: 'Xác định tỉ lệ chất khô trong mực tươi.' },
      { order: 3, content: 'Khối lượng mực tươi $= 2{,}4 : 25\\% = 9{,}6$kg.', rationale: 'Chia chất khô cho tỉ lệ chất khô trong tươi.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9.6', '9,6'], tolerance: 0.01 },
  },
  {
    id: 'PS-11-EX4',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Trộn 3 lít dung dịch muối nồng độ 25% với 2 lít dung dịch muối nồng độ 10%. Tính nồng độ (%) của dung dịch sau khi trộn.',
    solutionSteps: [
      { order: 1, content: 'Lượng muối: $3 \\times 25\\% + 2 \\times 10\\% = 0{,}75 + 0{,}2 = 0{,}95$.', rationale: 'Cộng dồn chất tan của hai dung dịch.' },
      { order: 2, content: 'Tổng dung dịch: $3 + 2 = 5$ lít.', rationale: 'Cộng dồn khối lượng/thể tích.' },
      { order: 3, content: 'Nồng độ sau trộn $= 0{,}95 : 5 = 19\\% $.', rationale: 'Chất tan chia cho tổng dung dịch.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['19'], tolerance: 0, unit: '%' },
  },
  {
    id: 'PS-11-EX5',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Có 4kg dung dịch đường nồng độ 30%. Cần thêm bao nhiêu kg nước để dung dịch còn nồng độ 20%?',
    solutionSteps: [
      { order: 1, content: 'Lượng đường không đổi $= 4 \\times 30\\% = 1{,}2$kg.', rationale: 'Thêm nước không làm thay đổi lượng đường.' },
      { order: 2, content: 'Tổng khối lượng dung dịch mới $= 1{,}2 : 20\\% = 6$kg.', rationale: 'Đường chiếm 20% của dung dịch mới.' },
      { order: 3, content: 'Lượng nước cần thêm $= 6 - 4 = 2$kg.', rationale: 'Lấy khối lượng mới trừ khối lượng ban đầu.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['2'], tolerance: 0, unit: 'kg' },
  },
  {
    id: 'PS-11-EX6',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Cần trộn bao nhiêu kg dung dịch muối 40% với 6kg dung dịch muối 10% để được dung dịch muối 25%?',
    solutionSteps: [
      { order: 1, content: 'Theo phương pháp đường chéo: hiệu $(40-25)=15$ và hiệu $(25-10)=15$ bằng nhau, nên tỉ lệ khối lượng cần trộn là $1:1$.', rationale: 'Áp dụng phương pháp đường chéo cơ bản.' },
      { order: 2, content: 'Vậy cần $6$kg dung dịch $40\\%$ (bằng khối lượng dung dịch $10\\%$).', rationale: 'Tỉ lệ 1:1 nên khối lượng bằng nhau.' },
      { order: 3, content: 'Kiểm tra: $6 \\times 40\\% + 6 \\times 10\\% = 2{,}4+0{,}6=3$kg muối trên tổng $12$kg $\\Rightarrow 25\\%$, đúng.', rationale: 'Xác minh lại kết quả.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, unit: 'kg' },
  },
  {
    id: 'PS-11-EX7',
    topicIds: ['PS-11'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Bánh mì tươi nặng 500g chứa 40% nước. Để làm bánh mì khô (giữ nguyên phần không phải nước) chỉ còn 10% nước, khối lượng bánh khô thu được gần nhất với giá trị nào?',
    solutionSteps: [
      { order: 1, content: 'Khối lượng chất khô $= 500 \\times 60\\% = 300$g.', rationale: 'Phần không phải nước không đổi.' },
      { order: 2, content: 'Bánh khô có $90\\%$ là chất khô $\\Rightarrow$ khối lượng khô $= 300 : 90\\% \\approx 333$g.', rationale: 'Chia chất khô cho tỉ lệ chất khô trong khô.' },
    ],
    mcq: { options: ['≈333g', '≈300g', '≈250g', '≈450g'], answerIndex: 0 },
  },

  // DH-15 — Tỉ lệ kép
  {
    id: 'DH-15-EX1',
    topicIds: ['DH-15'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '5 công nhân làm trong 6 ngày thì đào được 30m mương. Hỏi 8 công nhân làm trong 9 ngày thì đào được bao nhiêu mét mương (năng suất mỗi người như nhau)?',
    solutionSteps: [
      { order: 1, content: '1 công nhân làm trong 1 ngày đào được: $30 : (5 \\times 6) = 1$m.', rationale: 'Quy về năng suất đơn vị.' },
      { order: 2, content: '8 công nhân làm trong 9 ngày đào được: $1 \\times 8 \\times 9 = 72$m.', rationale: 'Nhân năng suất đơn vị với số liệu mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-15-EX2',
    topicIds: ['DH-15'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '8 người làm trong 5 ngày thì xong một công việc. Hỏi 10 người làm (năng suất như nhau) thì mất bao nhiêu ngày để xong công việc đó?',
    solutionSteps: [
      { order: 1, content: 'Tổng công việc theo "người-ngày": $8 \\times 5 = 40$.', rationale: 'Tổng công việc không đổi.' },
      { order: 2, content: 'Số ngày với 10 người: $40 : 10 = 4$ ngày.', rationale: 'Chia tổng công việc cho số người mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-15-EX3',
    topicIds: ['DH-15'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '6 máy cày trong 4 ngày cày được 24ha đất. Hỏi 9 máy cày trong 8 ngày cày được bao nhiêu ha đất (năng suất mỗi máy như nhau)?',
    solutionSteps: [
      { order: 1, content: '1 máy cày trong 1 ngày cày được: $24 : (6 \\times 4) = 1$ha.', rationale: 'Quy về năng suất đơn vị.' },
      { order: 2, content: '9 máy trong 8 ngày cày được: $1 \\times 9 \\times 8 = 72$ha.', rationale: 'Nhân năng suất đơn vị với số liệu mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['72'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-15-EX4',
    topicIds: ['DH-15'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '12 người làm trong 10 ngày thì xong công việc. Nếu chỉ có 8 người thì cần bao nhiêu ngày để hoàn thành công việc đó (năng suất như nhau)?',
    solutionSteps: [
      { order: 1, content: 'Tổng công việc: $12 \\times 10 = 120$ (người-ngày).', rationale: 'Tổng công việc không đổi.' },
      { order: 2, content: 'Số ngày với 8 người: $120 : 8 = 15$ ngày.', rationale: 'Chia tổng công việc cho số người mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-15-EX5',
    topicIds: ['DH-15'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '4 vòi nước cùng chảy trong 3 giờ thì đầy một bể có dung tích 12m³ (các vòi chảy như nhau). Hỏi 6 vòi như thế chảy trong 2 giờ thì được bao nhiêu m³ nước?',
    solutionSteps: [
      { order: 1, content: '1 vòi chảy trong 1 giờ được: $12 : (4 \\times 3) = 1$m³.', rationale: 'Quy về năng suất đơn vị.' },
      { order: 2, content: '6 vòi chảy trong 2 giờ được: $1 \\times 6 \\times 2 = 12$m³.', rationale: 'Nhân năng suất đơn vị với số liệu mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DH-15-EX6',
    topicIds: ['DH-15'],
    level: 'advanced',
    answerType: 'numeric',
    statement: '10 công nhân làm trong 12 ngày thì xong một công trình. Hỏi cần bao nhiêu công nhân để làm xong công trình đó trong 8 ngày (năng suất như nhau)?',
    solutionSteps: [
      { order: 1, content: 'Tổng công việc: $10 \\times 12 = 120$ (người-ngày).', rationale: 'Tổng công việc không đổi.' },
      { order: 2, content: 'Số công nhân cần: $120 : 8 = 15$ người.', rationale: 'Chia tổng công việc cho số ngày mới.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['15'], tolerance: 0, isInteger: true },
  },

  // DH-16 — Phương pháp khử
  {
    id: 'DH-16-EX1',
    topicIds: ['DH-16'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 2 quyển vở và 3 chiếc bút hết 26.000 đồng. Mua 2 quyển vở và 5 chiếc bút hết 34.000 đồng. Tính giá tiền một chiếc bút.',
    solutionSteps: [
      { order: 1, content: 'Số vở bằng nhau ở 2 lần mua, chênh lệch bút: $5 - 3 = 2$ chiếc, chênh lệch tiền: $34\\,000 - 26\\,000 = 8\\,000$ đồng.', rationale: 'Khử đại lượng vở.' },
      { order: 2, content: 'Giá 1 chiếc bút $= 8\\,000 : 2 = 4\\,000$ đồng.', rationale: 'Chia chênh lệch tiền cho chênh lệch số bút.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4000'], tolerance: 0, isInteger: true, unit: 'đồng' },
  },
  {
    id: 'DH-16-EX2',
    topicIds: ['DH-16'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 2 quyển vở và 3 chiếc bút hết 26.000 đồng. Mua 2 quyển vở và 5 chiếc bút hết 34.000 đồng. Tính giá tiền một quyển vở.',
    solutionSteps: [
      { order: 1, content: 'Giá 1 chiếc bút $= 4\\,000$ đồng (tính như bài trước).', rationale: 'Dùng kết quả đã khử được ở bước tìm giá bút.' },
      { order: 2, content: '$2$ quyển vở $= 26\\,000 - 3 \\times 4\\,000 = 26\\,000 - 12\\,000 = 14\\,000$ đồng.', rationale: 'Thay ngược vào phương trình ban đầu.' },
      { order: 3, content: 'Giá 1 quyển vở $= 14\\,000 : 2 = 7\\,000$ đồng.', rationale: 'Chia đều cho 2 quyển vở.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['7000'], tolerance: 0, isInteger: true, unit: 'đồng' },
  },
  {
    id: 'DH-16-EX3',
    topicIds: ['DH-16'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 2kg gạo và 3kg đường hết 88.000 đồng. Mua 2kg gạo và 5kg đường hết 128.000 đồng. Tính giá 1kg đường.',
    solutionSteps: [
      { order: 1, content: 'Chênh lệch đường: $5-3=2$kg, chênh lệch tiền: $128\\,000-88\\,000=40\\,000$ đồng.', rationale: 'Khử đại lượng gạo.' },
      { order: 2, content: 'Giá 1kg đường $= 40\\,000 : 2 = 20\\,000$ đồng.', rationale: 'Chia chênh lệch tiền cho chênh lệch số kg.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['20000'], tolerance: 0, isInteger: true, unit: 'đồng' },
  },
  {
    id: 'DH-16-EX4',
    topicIds: ['DH-16'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 2kg gạo và 3kg đường hết 88.000 đồng. Mua 2kg gạo và 5kg đường hết 128.000 đồng. Tính giá 1kg gạo.',
    solutionSteps: [
      { order: 1, content: 'Giá 1kg đường $= 20\\,000$ đồng (tính như bài trước).', rationale: 'Dùng kết quả đã tìm được.' },
      { order: 2, content: '$2$kg gạo $= 88\\,000 - 3 \\times 20\\,000 = 88\\,000 - 60\\,000 = 28\\,000$ đồng.', rationale: 'Thay ngược vào phương trình ban đầu.' },
      { order: 3, content: 'Giá 1kg gạo $= 28\\,000 : 2 = 14\\,000$ đồng.', rationale: 'Chia đều cho 2kg gạo.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['14000'], tolerance: 0, isInteger: true, unit: 'đồng' },
  },
  {
    id: 'DH-16-EX5',
    topicIds: ['DH-16'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 5 quả cam và 3 quả táo hết 43.000 đồng. Mua 5 quả cam và 7 quả táo hết 59.000 đồng. Tính giá 1 quả táo.',
    solutionSteps: [
      { order: 1, content: 'Chênh lệch táo: $7-3=4$ quả, chênh lệch tiền: $59\\,000-43\\,000=16\\,000$ đồng.', rationale: 'Khử đại lượng cam.' },
      { order: 2, content: 'Giá 1 quả táo $= 16\\,000 : 4 = 4\\,000$ đồng.', rationale: 'Chia chênh lệch tiền cho chênh lệch số táo.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['4000'], tolerance: 0, isInteger: true, unit: 'đồng' },
  },
  {
    id: 'DH-16-EX6',
    topicIds: ['DH-16'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Mua 5 quả cam và 3 quả táo hết 43.000 đồng. Mua 5 quả cam và 7 quả táo hết 59.000 đồng. Tính giá 1 quả cam.',
    solutionSteps: [
      { order: 1, content: 'Giá 1 quả táo $= 4\\,000$ đồng (tính như bài trước).', rationale: 'Dùng kết quả đã tìm được.' },
      { order: 2, content: '$5$ quả cam $= 43\\,000 - 3 \\times 4\\,000 = 43\\,000 - 12\\,000 = 31\\,000$ đồng.', rationale: 'Thay ngược vào phương trình ban đầu.' },
      { order: 3, content: 'Giá 1 quả cam $= 31\\,000 : 5 = 6\\,200$ đồng.', rationale: 'Chia đều cho 5 quả cam.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['6200'], tolerance: 0, isInteger: true, unit: 'đồng' },
  },

  // DH-17 — Chuyển động đặc biệt
  {
    id: 'DH-17-EX1',
    topicIds: ['DH-17'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đoàn tàu dài 160m chạy qua một cột điện (coi như một điểm) hết 8 giây. Tính vận tốc đoàn tàu.',
    solutionSteps: [
      { order: 1, content: 'Quãng đường tàu đi qua cột điện đúng bằng chiều dài đoàn tàu: $160$m.', rationale: 'Cột điện coi như một điểm.' },
      { order: 2, content: 'Vận tốc $= 160 : 8 = 20$m/giây.', rationale: 'Vận tốc = quãng đường : thời gian.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true, unit: 'm/giây' },
  },
  {
    id: 'DH-17-EX2',
    topicIds: ['DH-17'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đoàn tàu dài 250m chạy với vận tốc 25m/giây qua một cây cầu dài 500m. Tính thời gian tàu qua hết cầu.',
    solutionSteps: [
      { order: 1, content: 'Quãng đường $= 250 + 500 = 750$m.', rationale: 'Cộng thêm chiều dài tàu vì toa cuối phải rời khỏi cầu.' },
      { order: 2, content: 'Thời gian $= 750 : 25 = 30$ giây.', rationale: 'Thời gian = quãng đường : vận tốc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['30'], tolerance: 0, isInteger: true, unit: 'giây' },
  },
  {
    id: 'DH-17-EX3',
    topicIds: ['DH-17'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đoàn tàu chạy qua một cột điện hết 6 giây và qua một cây cầu dài 210m hết 20 giây (vận tốc không đổi). Tính chiều dài đoàn tàu.',
    solutionSteps: [
      { order: 1, content: 'Gọi vận tốc là $v$ (m/giây), chiều dài tàu $L = v \\times 6$.', rationale: 'Qua cột điện, quãng đường bằng chiều dài tàu.' },
      { order: 2, content: 'Qua cầu: $L + 210 = v \\times 20$, thay $L = 6v$: $6v + 210 = 20v \\Rightarrow 210 = 14v \\Rightarrow v = 15$m/giây.', rationale: 'Lập và giải phương trình theo v.' },
      { order: 3, content: 'Chiều dài tàu $L = 15 \\times 6 = 90$m.', rationale: 'Thay v vào công thức L.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['90'], tolerance: 0, isInteger: true, unit: 'm' },
  },
  {
    id: 'DH-17-EX4',
    topicIds: ['DH-17'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai xe cùng xuất phát từ một điểm trên đường đua vòng tròn dài 600m, đi cùng chiều. Xe A vận tốc 12m/giây, xe B vận tốc 9m/giây. Sau bao lâu xe A vượt xe B đúng 1 vòng?',
    solutionSteps: [
      { order: 1, content: 'Hiệu vận tốc $= 12 - 9 = 3$m/giây.', rationale: 'Đi cùng chiều nên dùng hiệu vận tốc.' },
      { order: 2, content: 'Thời gian $= 600 : 3 = 200$ giây.', rationale: 'Chu vi chia cho hiệu vận tốc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['200'], tolerance: 0, isInteger: true, unit: 'giây' },
  },
  {
    id: 'DH-17-EX5',
    topicIds: ['DH-17'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Hai xe máy cùng xuất phát từ một điểm trên đường đua vòng tròn dài 300m, đi ngược chiều nhau. Xe A vận tốc 8m/giây, xe B vận tốc 7m/giây. Sau bao lâu hai xe gặp nhau lần đầu tiên?',
    solutionSteps: [
      { order: 1, content: 'Tổng vận tốc $= 8 + 7 = 15$m/giây.', rationale: 'Đi ngược chiều nên dùng tổng vận tốc.' },
      { order: 2, content: 'Thời gian $= 300 : 15 = 20$ giây.', rationale: 'Chu vi chia cho tổng vận tốc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['20'], tolerance: 0, isInteger: true, unit: 'giây' },
  },
  {
    id: 'DH-17-EX6',
    topicIds: ['DH-17'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một đoàn tàu dài 300m chạy với vận tốc 20m/giây. Đoàn tàu này chạy qua một đoàn tàu khác dài 200m đang đứng yên trên đường ray song song. Tính thời gian tàu thứ nhất vượt qua hết tàu thứ hai.',
    solutionSteps: [
      { order: 1, content: 'Quãng đường $= 300 + 200 = 500$m.', rationale: 'Tổng chiều dài 2 tàu vì tàu kia đứng yên.' },
      { order: 2, content: 'Vận tốc tương đối $= 20$m/giây (vì tàu kia đứng yên).', rationale: 'Không cần cộng vận tốc vì tàu kia không chuyển động.' },
      { order: 3, content: 'Thời gian $= 500 : 20 = 25$ giây.', rationale: 'Thời gian = quãng đường : vận tốc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['25'], tolerance: 0, isInteger: true, unit: 'giây' },
  },

  // HH-12 — Sơn màu hình khối
  {
    id: 'HH-12-EX1',
    topicIds: ['HH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Khối lập phương cạnh 3cm được sơn 6 mặt rồi cắt thành 27 khối nhỏ cạnh 1cm. Có bao nhiêu khối sơn đúng 2 mặt?',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức: $12 \\times (n-2)$ với $n=3$: $12 \\times 1 = 12$.', rationale: 'Khối 2 mặt nằm ở cạnh, không phải góc.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-12-EX2',
    topicIds: ['HH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Khối lập phương cạnh 6cm được sơn 6 mặt rồi cắt thành 216 khối nhỏ cạnh 1cm. Có bao nhiêu khối sơn đúng 1 mặt?',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức: $6 \\times (n-2)^2$ với $n=6$: $6 \\times 16 = 96$.', rationale: 'Khối 1 mặt nằm ở giữa mỗi mặt.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['96'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-12-EX3',
    topicIds: ['HH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Khối lập phương cạnh 6cm (như bài trước) có bao nhiêu khối không sơn mặt nào?',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức: $(n-2)^3$ với $n=6$: $4^3 = 64$.', rationale: 'Khối 0 mặt nằm hoàn toàn bên trong.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['64'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-12-EX4',
    topicIds: ['HH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một khối hộp chữ nhật kích thước 4×3×2 (đơn vị: khối lập phương cạnh 1cm) được sơn 6 mặt rồi cắt rời thành các khối lập phương cạnh 1cm. Có bao nhiêu khối sơn đúng 3 mặt (ở góc)?',
    solutionSteps: [
      { order: 1, content: 'Khối hộp chữ nhật luôn có 8 đỉnh, mỗi đỉnh ứng với đúng 1 khối 3 mặt (miễn mỗi kích thước $\\ge 2$).', rationale: 'Số khối 3 mặt không phụ thuộc kích thước cụ thể.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['8'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-12-EX5',
    topicIds: ['HH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Với khối hộp chữ nhật 4×3×2 ở bài trước, có bao nhiêu khối sơn đúng 2 mặt?',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức: $4 \\times [(a-2)+(b-2)+(c-2)]$ với $a=4,b=3,c=2$: $4 \\times [2+1+0] = 4 \\times 3 = 12$.', rationale: 'Cộng tổng các cạnh (a-2)+(b-2)+(c-2) rồi nhân 4.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
  {
    id: 'HH-12-EX6',
    topicIds: ['HH-12'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Với khối hộp chữ nhật 4×3×2 ở bài trước, có bao nhiêu khối không sơn mặt nào?',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức: $(a-2)(b-2)(c-2)$ với $a=4,b=3,c=2$: $2 \\times 1 \\times 0 = 0$.', rationale: 'Vì $c-2=0$ (kích thước 2 quá nhỏ để có khối bên trong theo chiều đó).' },
    ],
    numeric: { kind: 'single', acceptedValues: ['0'], tolerance: 0, isInteger: true },
  },

  // DL-07 — Đọc bảng số liệu
  {
    id: 'DL-07-EX1',
    topicIds: ['DL-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bảng số lượng học sinh giỏi các môn của lớp 5A: Toán 15 bạn, Tiếng Việt 12 bạn, Tiếng Anh 10 bạn, Khoa học 8 bạn. Tính tổng số lượt học sinh giỏi (một bạn có thể giỏi nhiều môn) của lớp.',
    solutionSteps: [
      { order: 1, content: '$15 + 12 + 10 + 8 = 45$.', rationale: 'Cộng tất cả các giá trị trong bảng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['45'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-07-EX2',
    topicIds: ['DL-07'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Bảng số lượng học sinh giỏi các môn của lớp 5A: Toán 15 bạn, Tiếng Việt 12 bạn, Tiếng Anh 10 bạn, Khoa học 8 bạn. Môn nào có số học sinh giỏi nhiều hơn môn Tiếng Anh?',
    solutionSteps: [
      { order: 1, content: 'So sánh với môn Tiếng Anh (10 bạn): Toán $15>10$, Tiếng Việt $12>10$, Khoa học $8<10$.', rationale: 'So sánh từng môn với môn Tiếng Anh.' },
      { order: 2, content: 'Vậy Toán và Tiếng Việt đều nhiều hơn Tiếng Anh.', rationale: 'Kết luận.' },
    ],
    mcq: { options: ['Toán và Tiếng Việt', 'Chỉ Toán', 'Chỉ Tiếng Việt', 'Khoa học'], answerIndex: 0 },
  },
  {
    id: 'DL-07-EX3',
    topicIds: ['DL-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bảng số km 4 bạn đi xe đạp trong tuần: An 12km, Bình 15km, Chi 9km, Dũng 20km. Tính quãng đường trung bình mỗi bạn đi được.',
    solutionSteps: [
      { order: 1, content: 'Tổng: $12+15+9+20=56$km.', rationale: 'Cộng các giá trị trong bảng.' },
      { order: 2, content: 'Trung bình $= 56 : 4 = 14$km.', rationale: 'Chia cho số bạn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['14'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-07-EX4',
    topicIds: ['DL-07'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Bảng số km 4 bạn đi xe đạp trong tuần: An 12km, Bình 15km, Chi 9km, Dũng 20km (trung bình 14km). Bạn nào đi được quãng đường nhiều hơn quãng đường trung bình?',
    solutionSteps: [
      { order: 1, content: 'So sánh với trung bình $14$km: Bình $15>14$, Dũng $20>14$; An $12<14$, Chi $9<14$.', rationale: 'So sánh từng bạn với trung bình.' },
    ],
    mcq: { options: ['Bình và Dũng', 'Chỉ An', 'Chỉ Chi', 'Cả 4 bạn'], answerIndex: 0 },
  },
  {
    id: 'DL-07-EX5',
    topicIds: ['DL-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bảng sản lượng cam thu hoạch được của 3 vườn: Vườn 1: 240kg, Vườn 2: 180kg, Vườn 3: 300kg. Hỏi vườn 3 thu hoạch nhiều hơn vườn 2 bao nhiêu kg?',
    solutionSteps: [
      { order: 1, content: '$300 - 180 = 120$kg.', rationale: 'Lấy sản lượng vườn 3 trừ vườn 2.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['120'], tolerance: 0, isInteger: true },
  },
  {
    id: 'DL-07-EX6',
    topicIds: ['DL-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Bảng số lượng sách trong thư viện theo 4 thể loại: Truyện 320 quyển, Khoa học 180 quyển, Lịch sử 150 quyển, Thơ 100 quyển. Tính tổng số sách trong thư viện.',
    solutionSteps: [
      { order: 1, content: '$320+180+150+100=750$.', rationale: 'Cộng tất cả các giá trị trong bảng.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['750'], tolerance: 0, isInteger: true },
  },

  // DL-08 — Lịch và đồng hồ
  {
    id: 'DL-08-EX1',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Ngày 1/6/2024 là thứ Bảy. Hỏi ngày 15/6/2024 là thứ mấy?',
    solutionSteps: [
      { order: 1, content: 'Khoảng cách: $15 - 1 = 14$ ngày.', rationale: 'Tính số ngày sau.' },
      { order: 2, content: '$14 : 7 = 2$ dư $0$, nghĩa là đúng 2 tuần sau, cùng thứ.', rationale: 'Số dư 0 nghĩa là trùng thứ với ngày ban đầu.' },
      { order: 3, content: 'Vậy ngày 15/6/2024 là thứ Bảy.', rationale: 'Kết luận.' },
    ],
    mcq: { options: ['Thứ Bảy', 'Thứ Sáu', 'Chủ Nhật', 'Thứ Năm'], answerIndex: 0 },
  },
  {
    id: 'DL-08-EX2',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Ngày 3/3/2024 là Chủ Nhật. Hỏi ngày 20/3/2024 là thứ mấy?',
    solutionSteps: [
      { order: 1, content: 'Khoảng cách: $20-3=17$ ngày.', rationale: 'Tính số ngày sau.' },
      { order: 2, content: '$17 : 7 = 2$ dư $3$.', rationale: 'Chia cho 7 tìm số dư.' },
      { order: 3, content: 'Chủ Nhật $+3$ ngày: Chủ Nhật $\\to$ Thứ Hai(1) $\\to$ Thứ Ba(2) $\\to$ Thứ Tư(3).', rationale: 'Đếm tiếp theo số dư.' },
    ],
    mcq: { options: ['Thứ Tư', 'Thứ Ba', 'Thứ Bảy', 'Chủ Nhật'], answerIndex: 0 },
  },
  {
    id: 'DL-08-EX3',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'mcq',
    statement: 'Ngày 25/4/2024 là thứ Năm. Tháng 4 có 30 ngày. Hỏi ngày 5/5/2024 là thứ mấy?',
    solutionSteps: [
      { order: 1, content: 'Số ngày từ 25/4 đến hết tháng 4: $30-25=5$ ngày; cộng thêm 5 ngày đầu tháng 5: $5+5=10$ ngày sau.', rationale: 'Tính khoảng cách qua ranh giới tháng.' },
      { order: 2, content: '$10:7=1$ dư $3$.', rationale: 'Chia cho 7 tìm số dư.' },
      { order: 3, content: 'Thứ Năm $+3$ ngày: Năm $\\to$ Sáu(1) $\\to$ Bảy(2) $\\to$ Chủ Nhật(3).', rationale: 'Đếm tiếp theo số dư.' },
    ],
    mcq: { options: ['Chủ Nhật', 'Thứ Hai', 'Thứ Bảy', 'Thứ Sáu'], answerIndex: 0 },
  },
  {
    id: 'DL-08-EX4',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính góc giữa kim giờ và kim phút lúc 2 giờ đúng.',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức với $H=2,M=0$: $|30\\times2 - 5{,}5\\times0| = 60°$.', rationale: 'Thay số vào công thức.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['60'], tolerance: 0, isInteger: true, unit: 'độ' },
  },
  {
    id: 'DL-08-EX5',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính góc giữa kim giờ và kim phút lúc 8 giờ đúng.',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức với $H=8,M=0$: $|30\\times8-0|=240°$.', rationale: 'Thay số vào công thức.' },
      { order: 2, content: 'Vì $240°>180°$ nên góc thực tế $= 360°-240°=120°$.', rationale: 'Lấy góc nhỏ hơn giữa hai kim.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['120'], tolerance: 0, isInteger: true, unit: 'độ' },
  },
  {
    id: 'DL-08-EX6',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính góc giữa kim giờ và kim phút lúc 3 giờ 30 phút.',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức với $H=3,M=30$: $|30\\times3 - 5{,}5\\times30| = |90-165| = 75°$.', rationale: 'Thay số vào công thức.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['75'], tolerance: 0, isInteger: true, unit: 'độ' },
  },
  {
    id: 'DL-08-EX7',
    topicIds: ['DL-08'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Tính góc giữa kim giờ và kim phút lúc 10 giờ 30 phút.',
    solutionSteps: [
      { order: 1, content: 'Áp dụng công thức với $H=10,M=30$: $|30\\times10 - 5{,}5\\times30| = |300-165| = 135°$.', rationale: 'Thay số vào công thức.' },
      { order: 2, content: '$135° < 180°$ nên đây chính là góc cần tìm.', rationale: 'Không cần lấy 360° trừ đi.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['135'], tolerance: 0, isInteger: true, unit: 'độ' },
  },

  // TD-07 — Biểu đồ Ven
  {
    id: 'TD-07-EX1',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một lớp có 25 bạn thích đọc truyện, 18 bạn thích xem phim, 12 bạn thích cả 2. Hỏi có bao nhiêu bạn thích ít nhất 1 trong 2 hoạt động?',
    solutionSteps: [
      { order: 1, content: '$25 + 18 - 12 = 31$.', rationale: 'Áp dụng công thức bao hàm-loại trừ.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['31'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-07-EX2',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Lớp học ở bài trước có 40 học sinh (25 thích đọc truyện, 18 thích xem phim, 12 thích cả 2). Hỏi có bao nhiêu bạn không thích cả đọc truyện lẫn xem phim?',
    solutionSteps: [
      { order: 1, content: 'Số bạn thích ít nhất 1 hoạt động: $25+18-12=31$.', rationale: 'Áp dụng công thức bao hàm-loại trừ.' },
      { order: 2, content: 'Số bạn không thích hoạt động nào: $40-31=9$.', rationale: 'Lấy tổng số học sinh trừ đi số thích ít nhất 1.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['9'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-07-EX3',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Theo dữ kiện (25 thích đọc truyện, 18 thích xem phim, 12 thích cả 2), có bao nhiêu bạn chỉ thích đọc truyện (không thích xem phim)?',
    solutionSteps: [
      { order: 1, content: '$25 - 12 = 13$.', rationale: 'Lấy số thích đọc truyện trừ đi phần giao (thích cả 2).' },
    ],
    numeric: { kind: 'single', acceptedValues: ['13'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-07-EX4',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Theo dữ kiện (25 thích đọc truyện, 18 thích xem phim, 12 thích cả 2), có bao nhiêu bạn chỉ thích xem phim (không thích đọc truyện)?',
    solutionSteps: [
      { order: 1, content: '$18 - 12 = 6$.', rationale: 'Lấy số thích xem phim trừ đi phần giao (thích cả 2).' },
    ],
    numeric: { kind: 'single', acceptedValues: ['6'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-07-EX5',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một câu lạc bộ có 50 thành viên. Có 30 người biết bơi, 25 người biết đá cầu, 12 người biết cả 2 môn. Hỏi có bao nhiêu người không biết môn nào trong 2 môn đó?',
    solutionSteps: [
      { order: 1, content: 'Số người biết ít nhất 1 môn: $30+25-12=43$.', rationale: 'Áp dụng công thức bao hàm-loại trừ.' },
      { order: 2, content: 'Số người không biết môn nào: $50-43=7$.', rationale: 'Lấy tổng thành viên trừ đi số biết ít nhất 1 môn.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['7'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-07-EX6',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Theo dữ kiện ở bài trước (30 biết bơi, 25 biết đá cầu, 12 biết cả 2), có bao nhiêu người chỉ biết bơi (không biết đá cầu)?',
    solutionSteps: [
      { order: 1, content: '$30 - 12 = 18$.', rationale: 'Lấy số biết bơi trừ đi phần giao (biết cả 2).' },
    ],
    numeric: { kind: 'single', acceptedValues: ['18'], tolerance: 0, isInteger: true },
  },
  {
    id: 'TD-07-EX7',
    topicIds: ['TD-07'],
    level: 'advanced',
    answerType: 'numeric',
    statement: 'Một lớp có 45 học sinh, trong đó 28 bạn thích môn Toán, 24 bạn thích môn Tiếng Anh, và 5 bạn không thích môn nào trong 2 môn này. Hỏi có bao nhiêu bạn thích cả 2 môn?',
    solutionSteps: [
      { order: 1, content: 'Số bạn thích ít nhất 1 môn: $45-5=40$.', rationale: 'Lấy tổng số học sinh trừ đi số không thích môn nào.' },
      { order: 2, content: 'Số bạn thích cả 2 môn: $28+24-40=12$.', rationale: 'Suy ra từ công thức bao hàm-loại trừ theo chiều ngược lại.' },
    ],
    numeric: { kind: 'single', acceptedValues: ['12'], tolerance: 0, isInteger: true },
  },
];
